### ISSUE TITLE
Intermittent shasum check failures installing different packages

### ISSUE THREAD

**Issue by nodesocket** [npm/npm#11402]
We are seeing Intermittent failures doing `npm install --production`, from seperate/different packages, with the following error signature:

```
npm ERR! argv "node" "/home/node/.nvm/versions/node/v0.12.7/bin/npm" "install" "--production"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.3

npm ERR! shasum check failed for /tmp/npm-2004-f06358cc/registry.npmjs.org/mmmagic/-/mmmagic-0.4.0.tgz
npm ERR! Expected: 4fe0249e598981aa94a6b6f9551df9fb3667f1c1
npm ERR! Actual:   ab6e6a328eaf52ceee4bfdd1d888d6e0b79f60c4
npm ERR! From:     https://registry.npmjs.org/mmmagic/-/mmmagic-0.4.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

Our node version is `v0.12.7` and npm version is `2.14.3`.

Any ideas? Is this an NPM issue itself?

**Comment by acusti** [comment]
I’ve seen this error (with `npm install --production`) over the last week or so for a wide variety of packages, including:

* npm itself, from `https://registry.npmjs.org/npm/-/npm-2.14.3.tgz`
* webfontloader, from `https://registry.npmjs.org/webfontloader/-/webfontloader-1.6.6.tgz`
* lessjs, from `https://registry.npmjs.org/less/-/less-1.7.0.tgz`

At first, I thought it might’ve been related to npm packages published from node v0.11.x, as suggested in https://github.com/npm/npm/issues/5519#issuecomment-46745908, but now it seems unlikely that is the case.

**Comment by haoliu119** [comment]
:+1: +1 please fix this, thanks.

**Comment by othiym23** [comment]
This is probably due to a race condition in the registry (that's been fixed within the last couple days) that would get exercised when multiple publishes of the same version of a package were happening simultaneously, i.e. people were publishing from a Travis build that tried publishing from several versions of Node simultaneously. If this bug is reproducible consistently with a given `package@version` specifier, an issue should be opened on the affected package requesting that the maintainers publish a new version  (this problem shouldn't recur, even when publishing from Travis). If it comes and goes, it's possible there's an issue with the network or with our content delivery network.

I'm going to leave this open for a bit for further feedback and as a landing page for other people encountering this issue, and after that will close it, as I'm pretty sure this isn't due to the CLI. Thanks for your time!

**Comment by acusti** [comment]
Thanks for the response! I’ve definitely been continuing to see the shasum check errors intermittently as recently as this morning, so I’m not sure if it is related to the race condition issue. Though based on your description, it sounds like that race condition on multiple publish issue is also the likely cause of https://github.com/npm/npm/issues/11218.

I’ve been trying to update to newer versions of packages, hoping that there would be less of a chance of those published packages having this issue, but it sounds like that isn’t likely to help.

**Comment by nodesocket** [comment]
Seen this issue today. Additionally, we pin a specific versions in our `package.json`.

    "mmmagic": "0.4.0"

**Comment by soldair** [comment]
I have checked all of the tarballs for these packages on all of our tarball hosts and they match the published shasums.

Because you are still getting shasum errors this must mean there is an issue in the pipes. I will investigate the pipes that tar bits flow through on our side so see if i can find any :space_invader: 

Thanks for bringing this up!

**Comment by soldair** [comment]
@nodesocket if you wouldn't mind it might help if you could check to see if the tmp file is still there?
`/tmp/npm-2004-f06358cc/registry.npmjs.org/mmmagic/-/mmmagic-0.4.0.tgz`
if it is what's it's size? if you look at the contents it is it really binary data or some other kind of server error response?

**Comment by nodesocket** [comment]
Trying to replicate. Stay tuned.

**Comment by nodesocket** [comment]
Ok, just replicated:

```
npm ERR! shasum check failed for /tmp/npm-1968-d39ee729/registry.npmjs.org/npm/-/npm-2.14.3.tgz
npm ERR! Expected: 1f22c96e9ac34d326121f7e8010301d60a37f011
npm ERR! Actual:   04d24bc34a140da05219622f94cd244071d17422
npm ERR! From:     https://registry.npmjs.org/npm/-/npm-2.14.3.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/Brandcast/npm-debug.log
```

What do you want from my end?

**Comment by soldair** [comment]
Does the tmp file exist still?
If it does I'm curious about its contents.

**Comment by nodesocket** [comment]
Indeed that file `/tmp/npm-1968-d39ee729/registry.npmjs.org/npm/-/npm-2.14.3.tgz` exists. What would you like?

**Comment by soldair** [comment]
If you have a way to just send me the file that would be great. Otherwise.

The size. stat output would be fine.
If you look at the file are the contents binary? Or some server error message.

**Comment by nodesocket** [comment]
Let me know if you need anything else.

```
$ stat npm-2.14.3.tgz
  File: ‘npm-2.14.3.tgz’
  Size: 2588136   	Blocks: 5056       IO Block: 4096   regular file
Device: ca01h/51713d	Inode: 2621868     Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1001/    node)   Gid: ( 1001/    node)
Access: 2016-02-04 00:52:00.242932209 +0000
Modify: 2016-02-04 00:52:00.238932184 +0000
Change: 2016-02-04 00:52:00.238932184 +0000
 Birth: -
```

**Comment by soldair** [comment]
Thanks. I see that it's a couple mb. It's very unlikely that it's a server error response at that size. I'm going to dig in more. This helped a lot!

**Comment by soldair** [comment]
We cleared these tarballs from cdn which should fix the intermittent tarball issue.
ill keep investigating to see if any others are effectedetc.

If this happens again please let me know along with the size of the tmp tarball in the error message.

thanks!

**Comment by klemmster** [comment]
We're seing the same error with 
`node-gyp rebuild` when building iconv on travis-ci
The relevant parts from `npm install --no-optional --verbose --no-progress`
```
gyp http GET https://nodejs.org/dist/v0.10.36/node-v0.10.36.tar.gz
gyp http 200 https://nodejs.org/dist/v0.10.36/node-v0.10.36.tar.gz
…
gyp verb content checksum node-v0.10.36.tar.gz e910af136374a05c7f301e09c01fc9d1d1f56bb26c80a5c5d43a98c289b72bec
…
gyp verb check download content checksum, need to download `SHASUMS256.txt`... 
gyp verb checksum url https://nodejs.org/dist/v0.10.36/SHASUMS256.txt
gyp http GET https://nodejs.org/dist/v0.10.36/SHASUMS256.txt
gyp http 200 https://nodejs.org/dist/v0.10.36/SHASUMS256.txt
… "node-v0.10.36.tar.gz":"b9d7d1d0294bce46686b13a05da6fc5b1e7743b597544aa888e8e64a9f178c81"
…
gyp verb download contents checksum {"node-v0.10.36.tar.gz":"e910af136374a05c7f301e09c01fc9d1d1f56bb26c80a5c5d43a98c289b72bec"}
gyp verb validating download checksum for node-v0.10.36.tar.gz (e910af136374a05c7f301e09c01fc9d1d1f56bb26c80a5c5d43a98c289b72bec == b9d7d1d0294bce46686b13a05da6fc5b1e7743b597544aa888e8e64a9f178c81)
```

Infortunately,  the `~/.node-gyp` directory is cleared even with `npm config set rollback false` or `NPM_CONFIG_ROLLBACK=false npm install…` so I can't really get the file that the script downloads.

However, 
```bash
cd /tmp
wget  https://nodejs.org/dist/v0.10.36/node-v0.10.36.tar.gz`
node test.js
```

where test.js (inspired by node-gyp install code https://github.com/nodejs/node-gyp/blob/v3.0.3/lib/install.js#L152)
```javascript
var crypto = require('crypto')
var fs = require('fs')
fs.readFile('/tmp/node-v0.10.36.tar.gz', function(err, data) {
  if(err) {throw err;} 
  var shasum = crypto.createHash('sha256');
  shasum.update(data); 
  console.log(shasum.digest('hex'));
});
```
outputs the correct checksum.

**Comment by klemmster** [comment]
#11000 seems to have the same problem

**Comment by soldair** [comment]
@klemmster Downloads for node binaries do not come from the registry so it's a different issue. In any case It means that the download failed for whatever reason and you / code should try again. It's interesting though.

**Comment by nodesocket** [comment]
Still seeing this error for `npm@2.14.3` happened this morning. Also, it is definitely intermittent *(not consistent)*.

Let me know what you need?

**Comment by acusti** [comment]
I have a copy of the actual npm-2.14.3.tgz file that failed the shasum check, if that could help. Here’s a [download link](https://www.dropbox.com/s/9d5fwcke4h0uajh/npm-2.14.3.tgz?dl=1) to the file.

The error was:

```
npm ERR! shasum check failed for /tmp/npm-1974-b2836144/registry.npmjs.org/npm/-/npm-2.14.3.tgz
npm ERR! Expected: 1f22c96e9ac34d326121f7e8010301d60a37f011
npm ERR! Actual:   9542e873850b802d0ca1151c34788bc97af42040
npm ERR! From:     https://registry.npmjs.org/npm/-/npm-2.14.3.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by soldair** [comment]
Thanks! I'll take a look

**Comment by zkat** [comment]
Closing as a duplicate of https://github.com/npm/npm/issues/14626
