### ISSUE TITLE
"possible EventEmitter memory leak detected." warning during npm install

### ISSUE THREAD

**Issue by markvincze** [npm/npm#13806]
### I'm opening this issue because:

  - [ ] npm is producing a concerning warning during `npm install`.

### What's going wrong?

During `npm install` I get several of the following warning message:
```
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:680:33)
    at Request.<anonymous> (/home/mvincze/.nvm/versions/node/v4.4.7/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/home/mvincze/.nvm/versions/node/v4.4.7/lib/node_modules/npm/node_modules/request/request.js:791:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
```

To me this is happening with `2.15.10`. I haven't pinpointed the particular version this started happening with, but it doesn't happen with `2.10`.

### How can the CLI team reproduce the problem?

I'd expect this to be happening with many repositories, one example is https://github.com/Travix-International/frint.
Simply clone the repo and do `npm install` with npm version `2.15.10`.

### Supporting information:

 - `npm -v` prints: 2.15.10
 - `node -v` prints: v4.4.7
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: Linux

Btw. I tried to google this problem, and found a couple of threads, but they were related to earlier versions of npm, so this might be a regression.

**Comment by KenanY** [comment]
I believe this is a duplicate of https://github.com/npm/npm/issues/13656. Both `npm@2.15.10` and `npm@3.10.7` released with the update to `request@2.74.0` which seems to be causing this warning (ref. https://github.com/npm/npm/issues/13656#issuecomment-239575653).

**Comment by devnidhinraj** [comment]
I still get this error 

"possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:252:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:153:7)"

The node version is v5.12.0
The npm version is v3.10.7

**Comment by addaleax** [comment]
@devnidhinraj `(sudo) npm install -g npm@next` might fix that for you. :)

**Comment by TomKarachristos** [comment]
(sudo) npm install -g npm@next solve my problem, thx @addaleax .

**Comment by sholladay** [comment]
I am also seeing these when installing my [build-version](https://github.com/sholladay/build-version) module. It seems like the number of warnings has a strong correlation with the depth or size of the dependency tree. Without looking at the code, I'm guessing a concurrency limit is accidentally being exceeded.

I see it intermittently if I run:

```sh
npm install read-pkg-up username
```

But I never see it if I run those installs separately as:

```sh
npm install read-pkg-up && npm install username
```

**Comment by addaleax** [comment]
> Without looking at the code, I'm guessing a concurrency limit is accidentally being exceeded.

Yes, it occurs each time one of the connections used for downloading packages is re-used more than 10 times (see [here](https://github.com/npm/npm-registry-client/pull/142#issue-173578669) for the fix if you’re interested in what exactly the problem is).

> I am also seeing these when installing my build-version module.

Don’t worry about it! There is no change in behaviour, the warning is just printed to the console. As said above, this is already fixed and using npm v3.10.8 (aka `npm@next` right now) should remove the warnings for you, too. :)

**Comment by prakash118** [comment]
Thanks, same here `npm install -g npm@next` fixed my issue

**Comment by dnagyelek** [comment]
The above one haven't fixed it but I found this which had,
require('events').EventEmitter.defaultMaxListeners = Infinity;

**Comment by KenanY** [comment]
@dnagyelek You mean you are still seeing this issue with `npm@>=3.10.8`?

**Comment by dnagyelek** [comment]
yes, I got that issue.
first I updated the npn@next then I added the Infinity to my gulp file.
these both have fixed the warning message

**Comment by dnagyelek** [comment]
ps: my npm is 4.0.1

**Comment by KenanY** [comment]
@dnagyelek Interesting, might be worth opening a new issue to begin debugging that. Also, I don't understand how a gulp file would affect `npm`'s behavior.

**Comment by addaleax** [comment]
> Also, I don't understand how a gulp file would affect `npm`'s behavior.

@dnagyelek @KenanY yeah, I doubt this has anything to do with `npm` itself.

**Comment by dnagyelek** [comment]
the gulp file itself isn't affect the npm at all, the above one was just a workout to my specific problem, which was or not caused by npm.

**Comment by tetreault** [comment]
I just received this for the first time and its causing my React Native CLI project init command to fail. The same stack trace gets spit out each time before the `react-native init ProjectName` step dies. 


**(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:252:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:90:13)
    at Request.emit (events.js:182:7)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:791:10)
    at emitOne (events.js:95:20)
    at ClientRequest.emit (events.js:182:7)
    at tickOnSocket (_http_client.js:530:7)
    at onSocketNT (_http_client.js:542:5)**

**Comment by KenanY** [comment]
@tetreault What is the result of `npm --version`?

**Comment by tetreault** [comment]
@KenanY node v5.9.1 and npm v3.10.7

**Comment by KenanY** [comment]
@tetreault As mentioned above, this was fixed in `npm@3.10.8`.

**Comment by tetreault** [comment]
@KenanY crap, i should've read closer sorry and thanks!

**Comment by pagalasoujanya** [comment]
data received: �
(node) warning: possible EventEmitter memory leak detected. 11 data1 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at SerialPort.addListener (events.js:239:17)
    at SerialPort.<anonymous> (/home/polmon/Desktop/datalogger.js:21:14)
    at emitOne (events.js:77:13)
    at SerialPort.emit (events.js:169:7)
    at SerialPort.module.exports.raw (/home/polmon/Desktop/node_modules/serialport/lib/parsers.js:7:13)
    at SerialPort._emitData (/home/polmon/Desktop/node_modules/serialport/lib/serialport.js:313:18)
    at SerialPort.<anonymous> (/home/polmon/Desktop/node_modules/serialport/lib/serialport.js:293:14)
    at SerialPort.<anonymous> (/home/polmon/Desktop/node_modules/serialport/lib/serialport.js:306:7)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:614:17)
<Buffer 82>
data received: �


i'm getting the above error when i reading through the serialport.

**Comment by pagalasoujanya** [comment]
can any one give the solution

**Comment by KenanY** [comment]
@pagalasoujanya Sorry, that doesn't look like an issue with `npm` to me.

**Comment by pagalasoujanya** [comment]
how can we add multiple requests in the npm

**Comment by dsinghr** [comment]
While working with https://github.com/nodezoo/nodezoo-system, during installation I got the same issue. I agree with @KenanY that this is not `npm` issue but is `node` issue which occurs while we work with `docker`, especially multiple docker images.

**Comment by jali** [comment]
Also the same issue here today. I got npm 3.10.7 and node 6.0.0 

(node:20171) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit

Reading above and trying to update npm is worthless as v'3.10.8' is not in the npm registry. yet

**Comment by dsinghr** [comment]
@jali You can try yarn package manager.

**Comment by gitdang** [comment]
After having this error in my Sails project which uses grunt, I _was_ using npm 3.10.3 and node 6.7.0. I upgraded to npm 4.1.1 (via npm install -g npm@next) first, then upgraded to node 6.9.2, but got the warning after both upgrades. Although Sails uses grunt (by default), I get the error after everything is installed and the sails server is started and then I initiate an import process that uses KUE and does a bunch of POSTs to MongoDB.
```(node:1644) Warning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit```
Sorry for the crosspost--I guess this is for those who think it's disappeared... it might come back.

**Comment by KenanY** [comment]
@jali I see `npm@3.10.8` in the registry just fine; it's been there for quite some time now. Even if you don't see it for whatever reason, you could always install an even newer version of `npm`.

@gitdang Are you sure that what you're seeing is an issue with `npm` specifically? If so, feel free to open a new issue with some steps to reproduce :), otherwise it's a bit more likely that it's the fault of your own code :(

**Comment by odrzutowiec** [comment]
Hi guys, I just go the same

`(node:20659) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit`

I think in my case it's because I promisifiedAll and on top of that i'm transpiring from es7 async/await.

Please help..

**Comment by addaleax** [comment]
Hi everyone! Just fyi: If upgrading `npm` does not help you, then this issue is not about the problem you are having, and chances are it’s not related to `npm` at all (which also means that people here may not really be *able* to help you).

If you need help with a `Possible EventEmitter memory leak detected` warning, I would suggest that you open a new issue/question at a general Q&A site like StackOverflow or https://github.com/nodejs/help.

In your report you should definitely include:
- The command you are running
- The source code you are running, if possible
- If you are using Node 6 or Node 7, try using `node --trace-warnings <your program>` on the command line and see if that shows more helpful information
- Or generally, any other way of making the problem reproducible for somebody else

Also, keep in mind that the warning does not keep your program from working, it’s just saying “hey, maybe this is a bug in your code, you might want to take a look at it”.

**Comment by helzgate** [comment]
I got this because I have more than 10 calls to: 
    ` process.on('exit', () => dispose$.onNext());`
...too many process.on() listeners.
