### ISSUE TITLE
NPM install keeps hanging

### ISSUE THREAD

**Issue by TheDG** [npm/npm#13890]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X ] npm is producing an incorrect install.
  - [ X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
NPM keeps hanging when doing npm install (or install -g). It usually gets stuck while trying to do:
```fetchMetadata: sill mapToRegistry uri https://www.registry.npmjs.org/q```
This problem appeared out of the blue...

###LOG
[npm-debug.txt](https://github.com/npm/npm/files/459692/npm-debug.txt)

**Comment by lholmquist** [comment]
@TheDG what is the result from `npm config get registry`,  if you haven't made any changes it should be `https://registry.npmjs.org`

looking at your log, this error makes me think something is not set correctly,  `info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND www.registry.npmjs.org www.registry.npmjs.org:443`

or maybe your behind a proxy?

**Comment by pascalduez** [comment]
I'm having a similar behaviour since recent npm update. 
`npm i` hang either at the begining or at some point in install process, and I have to `killall -9 npm` cause it's sucking 100% CPU.

`npm config get registry` --> `https://registry.npmjs.org/`

No proxy here.

**Comment by addaleax** [comment]
@pascalduez Could it be that you are an Arch Linux user? See https://github.com/npm/npm/issues/13782 in that case. (Your problem is very likely not the same as the one described by @TheDG ).

**Comment by pascalduez** [comment]
@addaleax Arch it is :) Thanks for the quick feedback, going to crawl that other issue.
Strange thing is some `npm i ` on other repos went well.

**Comment by addaleax** [comment]
@pascalduez Yeah, that’s a bug that’s only in the Node.js executables for Arch Linux, it happens with other applications, too (but only `npm` hangs). A lot of people are happy with reverting to 6.4.0 (I do feel uncomfortable about that because the bug is also present there, it just shows up less often…), or you can install the binaries from https://nodejs.org/ (quick script for copy & paste [here](https://github.com/npm/npm/issues/13782#issuecomment-245887255)).

**Comment by pascalduez** [comment]
@addaleax Not sure if of any help, but I got that repo to install after several tries. It outputs a bunch of `(node:6163) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit`

**Comment by addaleax** [comment]
@pascalduez Yeah, that’s another known problem, see https://github.com/npm/npm/issues/13656 – `(sudo) npm install -g npm@next` should fix that for you. It’s definitely nothing to worry about! :)

**Comment by addaleax** [comment]
btw, both of these issues have been fixed, it’s just a matter of time until Node v6.6.0 comes out (which will have the fix for Arch, so you can use the binaries by your OS again), and until npm@3.10.8 is released officially with the fix for the `EventEmitter` warning.

**Comment by addaleax** [comment]
I think this can be closed now that Node v6.6.0 is out and everything works again on Arch.

**Comment by laustdeleuran** [comment]
I'm having [a similar issue](https://cl.ly/3S3J2Z112i26) on MacOS El Capitan using iTerm.  It only happens during `fetchMetadata`. This issue is[ posted on StackOverflow](http://stackoverflow.com/questions/37860219/npm-gets-stuck-on-fetchmetadata-network) as well.

**Comment by KenanY** [comment]
Closing per @addaleax.

**Comment by powerpbx** [comment]
Having this problem now.  Lots of people posting this issue all over the internet.  It's not fixed.

**Comment by SalahAdDin** [comment]
@laustdeleuran I have the same problem in a `AWS EC2` instance.
