### ISSUE TITLE
NPM 3.10.8 tries to install optional dep on unsupported platform when using npm-shrinkwrap.json

### ISSUE THREAD

**Issue by paglias** [npm/npm#14042]
#### I'm opening this issue because:
- [x] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

This problem started appearing with NPM 3.10.8, with 3.10.7 it worked well. With 3.10.8 TravisCI tries to install `fsevents` which is an optional dependency of a dev dependency that only works on OS X / mac OS and so it fails.

```
matteo@macbook~/dev/habitrpg/habitrpg$ npm ls fsevents
habitica@3.42.1 /Users/matteo/dev/habitrpg/habitrpg
└─┬ karma@1.3.0
  └─┬ chokidar@1.6.0
    └── fsevents@1.0.14
```

If it can help we're using npm shrinkwrap where the package is listed as `optional: true`

```
"fsevents": {
  "version": "1.0.14",
  "from": "fsevents@>=1.0.0 <2.0.0",
  "resolved": "https://registry.npmjs.org/fsevents/-/fsevents-1.0.14.tgz",
  "optional": true,
  "dependencies": {
    ...
  }
},
```

An example of a failing build is https://travis-ci.org/HabitRPG/habitrpg/builds/161951399, I don't have access to npm-debug.log

```
npm ERR! Linux 3.13.0-92-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v4.3.1/bin/node" "/home/travis/.nvm/versions/node/v4.3.1/bin/npm" "install"
npm ERR! node v4.3.1
npm ERR! npm  v3.10.8
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/HabitRPG/habitrpg/npm-debug.log

```

**Comment by paglias** [comment]
Just verified that this is happening on our production server that runs Linux.

**Comment by paglias** [comment]
Some more info, I created the shrinkwrap file with `npm shrinkwrap` (no options) with a just installed node_modules folder on mac OS using npm 3.10.8

According to `npm ls fsevents` it's a dependency of a dev dep (karma) that isn't included in the shrinkwrap so I'm also wondering why `fsevents` was added at all

**Comment by paglias** [comment]
Just tried a 100% exactly build but without the `npm-shrinkwrap.json` file and it works so the problem seems to be with it https://travis-ci.org/HabitRPG/habitrpg/builds/161957509

**Comment by chodorowicz** [comment]
Exactly same situation here, builds failing in Heroku because of `fsevents` being dependency of dev `browser-sync`
`npm ERR! notsup Unsupported platform for fsevents@1.0.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})`
Downgrading to npm `3.10.7` solves the issue.

**Comment by sebreh** [comment]
We are seeing the same issue. Like @chodorowicz mentioned, downgrading to 3.10.7 works.

**Comment by psylence303** [comment]
Also happens for us, we had to downgrade to 3.10.7

**Comment by paglias** [comment]
For now we've been generating npm-shrinkwrap.json on Linux and it works
with 3.10.8 but would like to have a lasting solution

Il 23 set 2016 11:13, "Artem Levik" <notifications@github.com> ha scritto:

**Comment by zdavis** [comment]
We're seeing this as well in our Travis builds.

**Comment by albertstill** [comment]
We also have this problem. At work we have Windows devs, Mac devs, CircleCI Linux, and AWS Linux. A hack fix for us is to manually delete `fsevents` (or what ever non-cross platform dep) from the shrinkwrap when we do an install on Mac.

I was hoping in 3.10.8 npm install would check if the optional shrinkwrap dep was compatible before installing. Because now the deps contain a optional boolean field. Much like an npm install works when there is no shrinkwrap, for example it checks the fsevents os [field](https://github.com/strongloop/fsevents/blob/master/package.json#L10) against the target OS.

However I understand there is an argument that this would be defeating the point of shrinkwrap if it's output varies depending on the target machine.

We are moving to Docker soon so this will problem will disappear for us. Interested to see what the solution is though.

**Comment by mfn** [comment]
FTR, having the same problem (duplicate reported at #14089 ) and our team needs to stay at 3.10.7 because of this.

**Comment by joefiorini** [comment]
I ran into this issue for `fsevents` as well, and it seems that adding:

```
  "optionalDependencies": {
    "fsevents": "*"
  },
```

to my project's `package.json` and then installing with `--no-optional` fixed it for me.

**Comment by bardiharborow** [comment]
Just hit this over at twbs/bootstrap. Exactly the same issue of shrinkwrapping on a mac and then installing on Travis.

**Comment by wavded** [comment]
Same.  Downgrading to 3.10.7 fixed it for now.

**Comment by amakhrov** [comment]
Downgrading `npm` from 3.10.8 to 3.10.7 solved the issue so far

**Comment by MilosMosovsky** [comment]
Confirming that downgrading `npm` works.

**Comment by mgol** [comment]
What's funny is that even if I invoke `npm install --no-optional` on a project using shrinkwrap it fails on `fsevents` which it shouldn't even be looking at...

**Comment by j2l** [comment]
Donwgrading to 3.10.7 then npm install threw a warn on linux:
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14

**Comment by AlexChesters** [comment]
@joefiorini
> I ran into this issue for fsevents as well, and it seems that adding:
  "optionalDependencies": {
    "fsevents": "*"
  },
to my project's package.json and then installing with --no-optional fixed it for me without downgrading to 3.10.7 (still on 3.10.8 on my server).

This does work, however it looks like `--no-optional` is unnecessary :)

**Comment by mgol** [comment]
Since it's a regression from a previous patch release and it does seem to affect a lot of people (basically everyone on a Linux or Windows using shrinkwrap who uses a package relying on `fsevents`) it'd be good to have it fixed in v3 even though v4 has already been released and npm@3 is in maintenance mode.

**Comment by watilde** [comment]
I actually have the same issue. Well, this issue should be labeled as a `big-bug` since probably it's easy to happen in the general cases, and I hope the patch for this issue will be merged into not only v4 but also v3 as well https://github.com/npm/npm/pull/14117

**Comment by mateatslc** [comment]
anyone knows if this still persist on npm@3.10.9?

**Comment by franher** [comment]
@mateatslc I just checked and it's not working with `npm@3.10.9` yet.

```
16:16:56 npm ERR! node v4.6.0
16:16:56 npm ERR! npm  v3.10.9
16:16:56 npm ERR! code EBADPLATFORM
16:16:56 
16:16:56 npm ERR! notsup Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
16:16:56 npm ERR! notsup Valid OS:    darwin
16:16:56 npm ERR! notsup Valid Arch:  any
16:16:56 npm ERR! notsup Actual OS:   linux
16:16:56 npm ERR! notsup Actual Arch: x64
```

**Comment by iarna** [comment]
There was actually a patch for something that sounds suspicious like this in 4.0.0…

**Comment by zkat** [comment]
https://github.com/npm/npm/issues/14117 was released with `npm@4.0.0`, which should fix this issue. Closing as resolved. `npm@4` will become `latest` next week (Nov 3), and things should be alright after that!

**Comment by iarna** [comment]
I've reproed this with 3.10.9 and can confirm that is indeed fixed with #14117 in 4.0.0.

**Comment by watilde** [comment]
@iarna @zkat Sounds nice! Will v3.x have bug fixes, like v2 had when it was LTS?

**Comment by zkat** [comment]
@watilde As discussed in https://github.com/nodejs/node/pull/9284#issuecomment-256267385 -- not unless they're considered critical or security-related issues. `npm@3` is now considered to be in maintenance mode.

**Comment by fraserxu** [comment]
@zkat @iarna Thanks for the fix! Will the fixed version of npm ship to new version of Node.js LTS? Manually downgrade or upgrade `npm` in a CI/CD environment could consume lots of time when running code in Docker.

**Comment by mgol** [comment]
@zkat I think this issue is a critical one. This is a regression from a previous patch and it affects everyone having `fsevents` in their dependency tree (which is used by *a lot* of packages), using shrinkwrap and running Linux (which even Mac users usually have in their CI). This bug has broken my CI setup and I think there are a lot of people sharing my situation.

Not everyone's setup makes it easy to change the built-in npm version and this is the version that's included in the latest Node 6.x. I think it'd be harsh to leave people on this broken version by default.

Note that I'm not asking for a little bugfix for a problem that has existed for a while. This is a big regression and a lot of people are hitting it.

**Comment by TheSavior** [comment]
This issue makes npm 3 completely unusable in a production setting. An LTS version of Node shipping with a version of npm that businesses **can't** rely on seems pretty serious.

If nothing else, the recommendations for users in that situation should be very explicit and clearly communicated.

As a related issue, it's pretty unfortunate that node's TSC and npm picked the same week to ship an LTS with a maintenance mode version of npm. Hopefully we can get these teams to include this in the implications of that decision for future releases.

**Comment by zkat** [comment]
@mgol your assessment that this is a critical issue for an LTS, specially since it's a regression, seems pretty reasonable. While #14117 provides an initial patch, @iarna has another PR coming up soon (probably next week), that will address the regression closer to the core. By then, the whole team should be in one place again, so we'll be able to give you a more concrete reply about whether we'll tag `npm@3.10.10` (which seems likely to me, personally!). Thanks y'all for the input. I'm gonna reopen this issue in the meantime because it seems significant enough in how it affects folks on LTS.

@TheSavior as I've mentioned over at https://github.com/nodejs/node/pull/9284, our rule of thumb for whether to ship new versions of `npm@2` and `npm@3` is whether we're able to provide a default version for Node that will Work™. That's what "maintenance mode" means for us right now. It's what we've talked with the LTS WG members about doing, and it's likely what we'll continue doing for the time being. As I said in the previous paragraph, since this is such a serious, recent regression on a version of npm that is already included in `node@6` LTS, we'll likely toss a patch over. Release week is next week, too :)

**Comment by fbe** [comment]
Lol npm

![](https://memecrunch.com/meme/A41AO/npm-install/image.jpg?w=400&c=1)

**Comment by TheSavior** [comment]
@zkat, I was surprised to see release day yesterday went out without an update for v3. Is this still something we should be expecting to get backported?

**Comment by othiym23** [comment]
> Is this still something we should be expecting to get backported?

Probably not. We're still discussing how best to get changes like this into the hands of more users, but in all likelihood that looks more like encouraging people to get on the latest version of npm, and not through backports. It _may_ mean encouraging the Node project to allow floating patches over the versions of npm in their distributions, or we may develop a separate (paid?) LTS release of our own. As I've said elsewhere, the team is too small to support many lines of development, and I'm encouraging the team to look at ways we can stick to only a single line of development.

**Comment by rmurphey** [comment]
@othiym23 getting my entire company on NPM 4 after *just* getting (most of) them on NPM 3 is a non-starter and does little to help me grow goodwill around a Node ecosystem that is still unfamiliar to many here. I hope you will reconsider this decision; otherwise we're going to be installing an outdated version of Node to get an NPM 3 that works :(

**Comment by othiym23** [comment]
> getting my entire company on NPM 4 after *just* getting (most of) them on NPM 3 is a non-starter and does little to help me grow goodwill around a Node ecosystem that is still unfamiliar to many here.

By contrast, if your organization is new to `npm@3`, the odds are very good that the upgrade to `npm@4`, which will, shortly, be as easy as running `npm -g install npm@latest`, will be completely smooth. If you look at the [breaking changes for `npm@4` in the new CHANGELOG](https://github.com/npm/npm/blob/release-next/CHANGELOG.md#brief-overview-of-breaking-changes), you'll see that it's a relatively modest set of changes, and at the margins of the tool.

The CLI team supporting multiple release lines at once was originally something meant to ease the process of transition from `npm@2` to `npm@3`, which was a much more disruptive change than previous major updates, and (the team hopes) subsequent ones. In my opinion, we kind of let that get out of hand with `npm@2` and `npm@3`, to the detriment of the team's ability to ship. I [talked about this recently](https://gist.github.com/othiym23/c98bd4ef5d9fb3f496835bd481ef40ae), so I'll leave that link in lieu of going on too long here. I'm trying to eliminate a significant source of overhead for my team, because I believe we can't afford it in order to respond to the other things I think we need to do.

It may seem like I'm drawing a needlessly hard line here. Why not do one or two more `npm@3` releases? I'm not being inflexible just to be a rules lawyer, though. The team has been fully preoccupied over the last two weeks just getting the stuff together that's in `npm@4.0.2` (and a few things that, for whatever reason, we weren't ready to ship yesterday). Time spent on backporting and running another release would have taken time away from making `npm@4` what it needs to be to be a successful, smooth upgrade. I know I say this with tedious frequency, but the CLI team is _very small_ and the amount of work before us is _very large_.

**Comment by mgol** [comment]
> It may seem like I'm drawing a needlessly hard line here. Why not do one or two more `npm@3` releases?

I think you're seeing it too much in black & white. We're not asking for new features for npm@3; we're not even asking for regular bug fixes for bugs that existed before. We're only asking to patch one big bug that is totally breaking a lot of people and is a recent regression. Updating npm included in Node is not always possible, on Windows it's difficult etc. It's important that the built-in version works.

npm 3.10.8 that introduced this bug included new features like #10073 (it's surprising it landed in a patch release, btw). New features almost always mean new bugs so various big popular projects apply a strategy of still doing up to a few patch releases with fixes for a previous major after a new major gets released. These patch releases are only supposed to fix critical issues which decreases the chance of introducing new regressions.

I understand you don't have resources to provide such support for months like e.g. Node.js does. But deciding on a low fixed number of patch releases including only critical patches seems like a responsible thing to do. Especially that even [people in the Node.js team](https://github.com/nodejs/node/pull/9284#issuecomment-256267385) like @Fishrock123 weren't aware of your plans for npm 2 & 3. I think it's too disruptive for the community to completely cut support like that in a moment.

Since Node.js is not updating its built-in npm to a new major until it bumps its own major, it's **very** important that the latest npm version in each major line is not broken. If you don't have resources to provide even a little overlap of releasing patches to accommodate critical issues in previous npm, it'd be better for the ecosystem if a month or two before you release a new major you stopped accepting non-critical fixes for the previous one. At least we wouldn't be now left with a broken version.

**Comment by rmurphey** [comment]
Without getting in to too many details, let's just say that switching to NPM 4 is more involved than you may wish (it's certainly more involved than I wish) due to various organizational and infrastructure realities that are what they are. 

As I understand it, this is a regression in the version of NPM that ships with the current LTS version of Node; to developers unfamiliar with the JS/Node ecosystem, this can be (is?) perceived as a regression in Node itself. As I said, barring an NPM 3 fix, I'm going to need to put us on a version of Node that ships with a working NPM until we have the organizational bandwidth to do the work involved in switching to NPM 4.

**Comment by jasonrhodes** [comment]
I have to echo what @rmurphey is saying here, I think. I totally understand the constraints of a small team and the reasons you've described for trying to move forward whenever possible. But this case seems rather clearly defined and differentiated from regular bug-fixes or features: a mid-major-version regression was introduced and identified as a "big-bug", in a version shipping with the current LTS version of nodejs (that node LTS part seems really relevant/important, I'm not sure what discussions you all have had re: that schedule and how it affects npm). 

In a general triage sense, this case feels like something most reasonable people would expect to be fixed within the major version where it was introduced, even if that fix comes more slowly due to constraints, etc. I don't envy your balancing act at all, but that's how it seems from here. Thanks for all your work as usual. :heart:

**Comment by othiym23** [comment]
After discussing it further with the rest of the team, these feature tip me back over the edge into releasing a `npm@3.10.10` containing only bc84012c2c615024b08868acbd8df53a7ca8d146 (and enough of the testing changes that we can be assured of a clean Travis build):

1. We haven't yet had a chance to sync up with the Node project about the CLI's shift in approach to managing old release lines of npm. Our new policy is that _only_ critical bugs (those that block usage of the new version of npm _entirely_ for a substantial majority of npm users) or security flaws will receive new releases. By that standard, this isn't a critical bug. It's a serious, but not grave, regression to shrinkwrap's behavior, but otherwise doesn't prevent use of npm. 

   The CLI team and the Node team should together come up with a strategy to better spread the load of supporting the release lines of npm bundled with the various LTS releases of Node.js. This is a problem that's been growing in urgency since the advent of Node LTS, and is something we (collectively) must resolve sooner rather than later, but it's not something the community should take the brunt of. 
2. This _is_ right after the release not just of `npm@4` (which hasn't even hit `latest` yet) but of Node 6 LTS, which is going to be LTS for a while. I agree that sticking everyone with a bad release of npm, especially in a new release line, is a bad idea.
3. @zkat kinda sorta committed us to this above.

That said! This isn't a general precedent. I stand by everything else I said previously, which is why I'm doing this release myself, and why this is likely to be a one-off. As @iarna said in conversation, if we committed to fixing all the `big-bug`s we know about within the major release in which they were introduced, we'd never do another big release. There are a lot of them. The bar for this sort of thing needs to be kept _very_ high, and we need a better strategy for figuring out how to share the load of dealing with this stuff between the npm and Node.js projects.

**Comment by jasonrhodes** [comment]
lol my timing there ... thanks @othiym23

**Comment by othiym23** [comment]
#14532 is the candidate for `npm@3.10.10`, if you want to keep an eye on its progress through CI & release. Keep in mind it will need to go through the usual CLI bake-in cycle even before it gets downstreamed to Node, which will then have to schedule it for inclusion in a subsequent maintenance release of Node 6, so it may be a while before it hits Node 6 LTS.

**Comment by othiym23** [comment]
This is fixed by 9aebe982114ea2107f46baa1dcb11713b4aaad04, included in `npm@3.10.10`, which is currently `npm@next-3`. Upon completion of its two-week testing period, it will be downstreamed to Node.js for inclusion in a subsequent release of Node.js 6 LTS 'Boron'. It's also addressed by bc84012c2c615024b08868acbd8df53a7ca8d146, included in `npm@4.0.0`, which is part of a testing series that will (probably) be released as `npm@latest` / `npm@4.0.2` in two weeks' time. Thanks to all for their patience and attention!

**Comment by othiym23** [comment]
(Also, those of you affected by this bug should run `npm install -g npm@next-3` and verify that it addressed this problem for you. Thanks!)

**Comment by TheSavior** [comment]
@othiym23 Thank you very much for taking care of us LTS users. I don't envy your prioritization situation, but I hope it pays your team back dividends by doing this release.

**Comment by mfn** [comment]
> (Also, those of you affected by this bug should run npm install -g npm@next-3 and verify that it addressed this problem for you. Thanks!)

I can confirm that our test-suite runs again with this version!

Thanks a lot to everyone involved being able that this happened, very much appreciated 😍

**Comment by buley** [comment]
`3.10.10` did not fix this for me

~~~

npm ERR! Linux 4.8.1-x86_64-linode75
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--no-optional"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.10
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported platform for fsevents@1.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

**Comment by watilde** [comment]
The original issue seems to be fixed by 'npm@3.10.10'. See the results on CI:
+ Before https://travis-ci.org/HabitRPG/habitica/builds/165119294
+ After https://travis-ci.org/watilde/habitica/builds/173535410

To verify it, I've reproduced the same situation first by

```
$ reset --hard fc30456
```

and then replaced `npm@3` with `npm@3.10.10` in `.travis.yml`:  https://github.com/watilde/habitica/commit/8c68b3c084501c24bb5b74868836d5a7146f10a7

**Comment by watilde** [comment]
@buley If it's possible, let me see your `package.json` and `npm-debug.log` when re-shrinkwrap doesn't resolve your issue

**Comment by othiym23** [comment]
Thank you, @watilde, and thank you (again) for the patch!

**Comment by ngokli** [comment]
@watilde I still have this error after upgrading to `v3.10.10`.  I've attached the files you asked for.

[npm_bug.zip](https://github.com/npm/npm/files/581986/npm_bug.zip)

This is my first time touching node.js or npm, so I'm still learning how to poke at this to try to get it to work (e.g. re-shrinkwrapping like @buley said)

**Comment by ngokli** [comment]
Ah, I see that fsevents is not optional in my `npm-shrinkwrap.json`.  So this is probably expected behavior, right?

[npm-shrinkwrap.zip](https://github.com/npm/npm/files/582022/npm-shrinkwrap.zip)

**Comment by legodude17** [comment]
Anyone still having this issue?

**Comment by robertdumitrescu** [comment]
Having the same problem on:

Node: v6.8.0
NPM: v3.10.10

Here are the final lines of my npm-debug

```
2936 verbose pkgid fsevents@1.0.14
2937 verbose cwd /home/robert/mGitRepos/universal-redux-template
2938 error Linux 4.7.9-200.fc24.x86_64
2939 error argv "/home/robert/.nvm/versions/node/v6.8.0/bin/node" "/home/robert/.nvm/versions/node/v6.8.0/bin/npm" "install"
2940 error node v6.8.0
2941 error npm  v3.10.10
2942 error code EBADPLATFORM
2943 error notsup Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2944 error notsup Valid OS:    darwin
2944 error notsup Valid Arch:  any
2944 error notsup Actual OS:   linux
2944 error notsup Actual Arch: x64
2945 verbose exit [ 1, true ]
```

What is really weird is that I have this error just on Fedora 24. I tried to NPM Install exactly the same app on my personal Ubuntu 16.04 and it works like a charm. No problem at all.

**Comment by dimsolution** [comment]
It's time to use Yarn package manger ;) !
It has solved my problem.

**Comment by legodude17** [comment]
Do you have a `npm-shrinkwrap.json`? If yes, what does it look like? If no, what is your `package.json`?

**Comment by peter-mouland** [comment]
@legodude17 I have unfortunately this error also:
```
npm ERR! node v6.9.1
       npm ERR! npm  v3.10.10
       npm ERR! code EBADPLATFORM
       
       npm ERR! notsup Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
       npm ERR! notsup Valid OS:    darwin
       npm ERR! notsup Valid Arch:  any
       npm ERR! notsup Actual OS:   linux
       npm ERR! notsup Actual Arch: x64
```

my shrinkwarp is in [fsevents shrinkwrap gist](https://gist.github.com/peter-mouland/e94358cf9be32fab6ac1aecb9f147b1b)

**Comment by dimsolution** [comment]
@peter-mouland  To fix this issue, you have to add "optionalDependencies" on your package.json:

```
"optionalDependencies": {
    "fsevents": "*"
  },
```

Now you can make 

> npm install --no-optional

**Comment by peter-mouland** [comment]
I was just highlighting that the issue still exists. as it sounded like it was thought to have been solved with v3.10.10.  For now i've downgraded to v3.10.7 which fixed the issue.  I prefer the downgrade route as that mean less cognitive effort.

**Comment by peter-mouland** [comment]
I'm also getting this error when using it at work (on jenkins)
```sh
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
15:10:15 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
15:10:15 npm ERR! Linux 3.16.0-23-generic
15:10:15 npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i"
15:10:15 npm ERR! node v7.1.0
15:10:15 npm ERR! npm  v3.10.9
15:10:15 npm ERR! code EBADPLATFORM
15:10:15 
15:10:15 npm ERR! notsup Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
15:10:15 npm ERR! notsup Valid OS:    darwin
15:10:15 npm ERR! notsup Valid Arch:  any
15:10:15 npm ERR! notsup Actual OS:   linux
15:10:15 npm ERR! notsup Actual Arch: x64
```

**Comment by legodude17** [comment]
Is `fsevents` marked as optional in the `npm-shrinkwrap.json`?

**Comment by evocateur** [comment]
@peter-mouland you're using npm 3.10.9 in that jenkins stack, which explains why it's failing.

**Comment by phobos2077** [comment]
Having the same issue. Tried many different versions of fsevents with no success. 
```
$ npm install --no-optional
celgene@0.0.1 /home/vagrant/development
└── (empty)

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--no-optional"
npm ERR! node v5.10.1
npm ERR! npm  v4.0.2
npm ERR! path ../semver/bin/semver
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall symlink

npm ERR! EPROTO: protocol error, symlink '../semver/bin/semver' -> '/home/vagrant/development/node_modules/accord/node_modules/.bin/semver'
```

**Comment by watilde** [comment]
@phobos2077 That seems a different issue with this thread. Since I couldn't find the same issue with you, it's nice if you could open an issue as a new topic.

**Comment by Ehekatl** [comment]
getting this error on 4.0.2 as well

```
npm WARN bobcat_support_tools@0.0.1 No license field.
☻      ♥npm☻      ) ERR! Linux 4.4.15-25.57.amzn1.x86_64
npm☻      ~ ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "--prefix" "./fe/support" "install" "./fe/support"
npm ERR! node v6.9.1
☻      §npm ERR! npm  v4.0.2
☻      pm ERR! code EBADPLATFORM
☻      ☺
☻      ☼npm ERR! notsup☻      y Unsupported platform for fsevents@1.0.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm☻      * ERR! notsup Valid OS:    darwin
npm ERR! ☻      ∟notsup Valid Arch:  any
npm ☻      .ERR! notsup Actual OS:   linux
npm ERR! notsup☻      ↕ Actual Arch: x64
☻      ☺
☻      jnpm ERR! Please include the following file with any support request:
npm ERR!     /home/app/npm-debug.log
···

**Comment by Ehekatl** [comment]
@zkat npm4.0.2 doesn't fix this, please reopen this issue, I'm using npm-shrinkwarp, I have cleaned cache and remove node_modules and it still not work. However npm 3.10.7 works fine. We have two different build environment, only one has this problem, the only difference is the working one is using npm mirror. That's really strange.

**Comment by dimsolution** [comment]
@Ehekatl +1 : after updated npm 3.10.8 > 4.0.2 same problem...

**Comment by legodude17** [comment]
Everyone with this issue: Make sure that `fsevents` is marked as `optional` everywhere.

**Comment by ngokli** [comment]
I feel like folks are confused and need some clarification, so I'll give it a shot!  Please correct me as needed!

By "everywhere", @legodude17 means in `package.json` and `npm-shrinkwrap.json` (right?).  So wherever you find `fsevents` in these two files, it needs to be marked as `optional`.  And if you do that and use `npm@3.10.10` (or, I assume, `npm@4.0.2`), you don't need `--no-optional` (I'd think you would generally avoid `--no-optional`, to just install everything that is compatible with your system.  My understanding is using `fsevents` is more efficient on a Mac).

With `npm@3.10.10` or `npm@4.0.2`, shrinkwrapping will automatically mark `fsevents` (and other optional modules) as optional in your `npm-shrinkwrap.json`, so you won't have to do it manually in the future.  To avoid some manual work: If `npm install` works properly on your Mac, you could try just regenerating the `npm-shrinkwrap.json` with `npm shrinkwrap`, and see if that works on your Lunix/Windows boxen.

**Comment by ngokli** [comment]
Now a question: Say I need a package with an optional dependency that requires OS X, and another package with an optional dependency that requires Linux, can `npm shrinkwrap` include both of those in my `npm-shrinkwrap.json`?

I'm not dealing with this issue myself (I've only used `npm` for for a pre-interview homework problem I was given the other day), but I assume this is an important use case, and I'm curious.  Is it a use case that has been considered?  Perhaps it's not a common issue?  But some googling leads to a real use case: https://github.com/develar/7zip-bin/blob/master/package.json#L11

**Comment by legodude17** [comment]
Yes. Npm will install everything in optional unless it is incompatible with your system.

**Comment by legodude17** [comment]
@ngokli, I meant in those places, but also in package.json and npm-shrinkwrap.json of all of your deps.

**Comment by ngerritsen** [comment]
How I fixed it:
1. `rm -rf node_modules npm-shrinkwrap.json`
2. `npm install --no-optional`
3. `npm shrinkwrap --dev`

**Comment by dimsolution** [comment]
@ngerritsen Thanks you !

**Comment by bradchesney79** [comment]
--So, wouldn't the best fix be for Mac users to ask that this feature just works natively? The rest of us are incurring problems because we needed to add a work around for Mac users. You all realize this is a work around for a work around-- which to me seems silly-- and this has been in place a long time, Mac OS devs (the guys that actually work on the code that compiles to be the OS, mind you)... you're wearing egg all over your faces, you should get that off.

Just another example of why I feel Macs are the second best dev platform. Win machines a distant fourth or fifth...

**Comment by hieudang9** [comment]
Same Here
```
[~/upterm] : npm --version                                                                                           (master) 10:34:54
4.6.1
[~/upterm] : node --version                                                                                          (master) 11:22:43
v8.1.3
```

**Comment by mikeshow** [comment]
Same here:
npm 5.3.0
node 7.10.1

**Comment by carvalhoviniciusluiz** [comment]
hi!
i'm using node v8.5.0 with npm v5.4.2 in macOS Sierra v10.12.6

***I got the error***

<pre>
$ npm install
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for inotify@1.4.2: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm ERR! notsup Valid OS:    linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/viniciuscarvalho/.npm/_logs/2017-09-21T01_39_04_629Z-debug.log
</pre>

***last lines of the log***

<pre>
8541 verbose unlock done using /Users/viniciuscarvalho/.npm/_locks/staging-155aa32e51b9d4ae.lock for /Users/viniciuscarvalho/Dropbox/server/node_modules/.staging
8542 verbose stack Error: Unsupported platform for inotify@1.4.2: wanted {"name":"inotify","version":"1.4.2","author":{"name":"Camilo Aguilar","email":"camilo.aguilar@gmail.com"},"email":"camilo.aguilar@gmail.com","keywords":["inotify","watch","monitor","watch files","watch directories"],"license":"MIT","description":"inotify bindings for v8 javascript engine","repository":{"type":"git","url":"git+ssh://git@github.com/c4milo/node-inotify.git"},"os":["linux"],"engines":{"node":">=0.8"},"main":"inotify","dependencies":{"bindings":"^1.2.1","nan":"^2.3.3"},"scripts":{"test":"node-gyp configure build","install":"node-gyp rebuild"},"gypfile":true,"contributors":[{"name":"Adrian Estrada","email":"edsadr@gmail.com"},{"name":"Alexander Makarenko","email":"estliberitas@gmail.com"},{"name":"Brian Ingalls","email":"bingalls@compete.com"},{"name":"Brian White","email":"mscdex@mscdex.net"},{"name":"Camilo Aguilar","email":"camilo.aguilar@gmail.com"},{"name":"Dan VerWeire","email":"dverweire@gmail.com"},{"name":"FrozenCow","email":"frozencow@gmail.com"},{"name":"Michael Boe","email":"mschuylerb@gmail.com"},{"name":"Yannick Croissant","email":"k1der.country@free.fr"},{"name":"ikokostya","email":"ikokostya@gmail.com"}],"bugs":{"url":"https://github.com/c4milo/node-inotify/issues"},"homepage":"https://github.com/c4milo/node-inotify#readme","_id":"inotify@1.4.2","bundleDependencies":false,"deprecated":false,"_resolved":"https://registry.npmjs.org/inotify/-/inotify-1.4.2.tgz","_integrity":"sha512-+dq8cO+Um/EiGujOilVGw1AclDq9V4B23z4I+PpytUlgIrWfOG/KxW4k7pRZwHHSoqUzlScCWYuQS8Wa+hYcXg==","_shasum":"fd69d0f6e4a55005e338b3c1852fbb81acfb3ccc","_from":"inotify@>= 0.1.6","_requested":{"type":"range","registry":true,"raw":"inotify@>= 0.1.6","name":"inotify","escapedName":"inotify","rawSpec":">= 0.1.6","saveSpec":null,"fetchSpec":">= 0.1.6"},"_spec":"inotify@>= 0.1.6","_where":"/Users/viniciuscarvalho/Dropbox/server/node_modules/dev"} (current: {"os":"darwin","cpu":"x64"})
8542 verbose stack     at checkPlatform (/Users/viniciuscarvalho/.nvm/versions/node/v8.5.0/lib/node_modules/npm/node_modules/npm-install-checks/index.js:45:14)
8542 verbose stack     at tryCatcher (/Users/viniciuscarvalho/.nvm/versions/node/v8.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
8542 verbose stack     at ret (eval at makeNodePromisifiedEval (/Users/viniciuscarvalho/.nvm/versions/node/v8.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
8542 verbose stack     at readJson.then.catch.then (/Users/viniciuscarvalho/.nvm/versions/node/v8.5.0/lib/node_modules/npm/lib/install/action/refresh-package-json.js:31:12)
8542 verbose stack     at tryCatcher (/Users/viniciuscarvalho/.nvm/versions/node/v8.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
8542 verbose stack     at Promise._settlePromiseFromHandler (/Users/viniciuscarvalho/.nvm/versions/node/v8.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
8542 verbose stack     at Promise._settlePromise (/Users/viniciuscarvalho/.nvm/versions/node/v8.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
8542 verbose stack     at Promise._settlePromise0 (/Users/viniciuscarvalho/.nvm/versions/node/v8.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
8542 verbose stack     at Promise._settlePromises (/Users/viniciuscarvalho/.nvm/versions/node/v8.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
8542 verbose stack     at Promise._fulfill (/Users/viniciuscarvalho/.nvm/versions/node/v8.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
8542 verbose stack     at Promise._settlePromise (/Users/viniciuscarvalho/.nvm/versions/node/v8.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:582:21)
8542 verbose stack     at Promise._settlePromise0 (/Users/viniciuscarvalho/.nvm/versions/node/v8.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
8542 verbose stack     at Promise._settlePromises (/Users/viniciuscarvalho/.nvm/versions/node/v8.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
8542 verbose stack     at Promise._fulfill (/Users/viniciuscarvalho/.nvm/versions/node/v8.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
8542 verbose stack     at Promise._resolveCallback (/Users/viniciuscarvalho/.nvm/versions/node/v8.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:432:57)
8542 verbose stack     at Promise._settlePromiseFromHandler (/Users/viniciuscarvalho/.nvm/versions/node/v8.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:524:17)
8543 verbose pkgid inotify@1.4.2
8544 verbose cwd /Users/viniciuscarvalho/Dropbox/server
8545 verbose Darwin 16.7.0
8546 verbose argv "/Users/viniciuscarvalho/.nvm/versions/node/v8.5.0/bin/node" "/Users/viniciuscarvalho/.nvm/versions/node/v8.5.0/bin/npm" "install"
8547 verbose node v8.5.0
8548 verbose npm  v5.4.2
8549 error code EBADPLATFORM
8550 error notsup Unsupported platform for inotify@1.4.2: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
8551 error notsup Valid OS:    linux
8551 error notsup Valid Arch:  any
8551 error notsup Actual OS:   darwin
8551 error notsup Actual Arch: x64
8552 verbose exit [ 1, true ]
</pre>

**Comment by bylomo** [comment]
Hi, same issue.
└─┬ karma@1.3.0
  └─┬ chokidar@1.6.0
    └── fsevents@1.0.14

BUT, in my log, why it display:
npm ERR! notsup Unsupported platform for fsevents@**0.3.8**: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
it shows 0.3.8 instead of 1.0.14, downgraded and added optionalDependencies are useless....

**Comment by maximlomans** [comment]
same here... 
got while installing nodemon+ then sought a scalpel but it too complained ; 
hell my mother in law isn't this persistent : \ 
2018 and npm is still suffering  
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/nodemon/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
                                          & 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/shrinkwrap-scalpel/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by JipingWang** [comment]
[ERROR] npm : npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules\fsevents):

**Comment by danbao** [comment]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by vvvjo** [comment]
Is there a root cause analysis for this issue? Curious to know
