### ISSUE TITLE
npm install 407 Proxy Authentication Required - cannot get past company proxy

### ISSUE THREAD

**Issue by loofunk** [npm/npm#14421]
#### I'm opening this issue because:

NPM will not let me past the company proxy. I have set it a number of times but keep getting the same error.
#### What's going wrong?

407 Proxy Authentication Required
#### How can the CLI team reproduce the problem?

Try npm install for packages on a system behind a proxy. Get the error. Add proxy settings, still get error.

**Comment by legodude17** [comment]
Can please upload a `npm-debug.log`?

**Comment by loofunk** [comment]
Hi,

here it is below, I am behind a company proxy, looks like it all works until I get to ECONNREFUSED , thanks

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@2.15.9
3 info using node@v4.6.1
4 verbose readDependencies loading dependencies from c:\angular-quickstart\package.json
5 warn package.json angular-quickstart@1.0.0 No description
6 warn package.json angular-quickstart@1.0.0 No repository field.
7 warn package.json angular-quickstart@1.0.0 No README data
8 warn package.json angular-quickstart@1.0.0 No license field.
9 verbose install where, deps [ 'c:\\angular-quickstart',
9 verbose install   [ '@angular/common',
9 verbose install     '@angular/compiler',
9 verbose install     '@angular/core',
9 verbose install     '@angular/forms',
9 verbose install     '@angular/http',
9 verbose install     '@angular/platform-browser',
9 verbose install     '@angular/platform-browser-dynamic',
9 verbose install     '@angular/router',
9 verbose install     '@angular/upgrade',
9 verbose install     'angular-in-memory-web-api',
9 verbose install     'bootstrap',
9 verbose install     'core-js',
9 verbose install     'reflect-metadata',
9 verbose install     'rxjs',
9 verbose install     'systemjs',
9 verbose install     'zone.js',
9 verbose install     '@types/core-js',
9 verbose install     '@types/node',
9 verbose install     'concurrently',
9 verbose install     'lite-server',
9 verbose install     'typescript' ] ]
10 verbose install where, peers [ 'c:\\angular-quickstart', [] ]
11 verbose installManyTop reading for lifecycle c:\angular-quickstart\package.json
12 info preinstall angular-quickstart@1.0.0
13 verbose readDependencies loading dependencies from c:\angular-quickstart\package.json
14 silly cache add args [ '@angular/compiler@~2.1.1', null ]
15 verbose cache add spec @angular/compiler@~2.1.1
16 silly cache add parsed spec Result {
16 silly cache add   raw: '@angular/compiler@~2.1.1',
16 silly cache add   scope: '@angular',
16 silly cache add   name: '@angular/compiler',
16 silly cache add   rawSpec: '~2.1.1',
16 silly cache add   spec: '>=2.1.1 <2.2.0',
16 silly cache add   type: 'range' }
17 silly addNamed @angular/compiler@>=2.1.1 <2.2.0
18 verbose addNamed ">=2.1.1 <2.2.0" is a valid semver range for @angular/compiler
19 silly addNameRange { name: '@angular/compiler',
19 silly addNameRange   range: '>=2.1.1 <2.2.0',
19 silly addNameRange   hasData: false }
20 silly mapToRegistry name @angular/compiler
21 silly mapToRegistry scope (from package name) @angular
22 verbose mapToRegistry no registry URL found in name for scope @angular
23 silly mapToRegistry using default registry
24 silly mapToRegistry registry http://registry.npmjs.org/
25 silly mapToRegistry data Result {
25 silly mapToRegistry   raw: '@angular/compiler',
25 silly mapToRegistry   scope: '@angular',
25 silly mapToRegistry   name: '@angular/compiler',
25 silly mapToRegistry   rawSpec: '',
25 silly mapToRegistry   spec: 'latest',
25 silly mapToRegistry   type: 'tag' }
26 silly mapToRegistry uri http://registry.npmjs.org/@angular%2fcompiler
27 verbose addNameRange registry:http://registry.npmjs.org/@angular%2fcompiler not in flight; fetching
28 silly cache add args [ '@angular/core@~2.1.1', null ]
29 verbose cache add spec @angular/core@~2.1.1
30 silly cache add parsed spec Result {
30 silly cache add   raw: '@angular/core@~2.1.1',
30 silly cache add   scope: '@angular',
30 silly cache add   name: '@angular/core',
30 silly cache add   rawSpec: '~2.1.1',
30 silly cache add   spec: '>=2.1.1 <2.2.0',
30 silly cache add   type: 'range' }
31 silly addNamed @angular/core@>=2.1.1 <2.2.0
32 verbose addNamed ">=2.1.1 <2.2.0" is a valid semver range for @angular/core
33 silly addNameRange { name: '@angular/core',
33 silly addNameRange   range: '>=2.1.1 <2.2.0',
33 silly addNameRange   hasData: false }
34 silly mapToRegistry name @angular/core
35 silly mapToRegistry scope (from package name) @angular
36 verbose mapToRegistry no registry URL found in name for scope @angular
37 silly mapToRegistry using default registry
38 silly mapToRegistry registry http://registry.npmjs.org/
39 silly mapToRegistry data Result {
39 silly mapToRegistry   raw: '@angular/core',
39 silly mapToRegistry   scope: '@angular',
39 silly mapToRegistry   name: '@angular/core',
39 silly mapToRegistry   rawSpec: '',
39 silly mapToRegistry   spec: 'latest',
39 silly mapToRegistry   type: 'tag' }
40 silly mapToRegistry uri http://registry.npmjs.org/@angular%2fcore
41 verbose addNameRange registry:http://registry.npmjs.org/@angular%2fcore not in flight; fetching
42 silly cache add args [ '@angular/forms@~2.1.1', null ]
43 verbose cache add spec @angular/forms@~2.1.1
44 silly cache add parsed spec Result {
44 silly cache add   raw: '@angular/forms@~2.1.1',
44 silly cache add   scope: '@angular',
44 silly cache add   name: '@angular/forms',
44 silly cache add   rawSpec: '~2.1.1',
44 silly cache add   spec: '>=2.1.1 <2.2.0',
44 silly cache add   type: 'range' }
45 silly addNamed @angular/forms@>=2.1.1 <2.2.0
46 verbose addNamed ">=2.1.1 <2.2.0" is a valid semver range for @angular/forms
47 silly addNameRange { name: '@angular/forms',
47 silly addNameRange   range: '>=2.1.1 <2.2.0',
47 silly addNameRange   hasData: false }
48 silly mapToRegistry name @angular/forms
49 silly mapToRegistry scope (from package name) @angular
50 verbose mapToRegistry no registry URL found in name for scope @angular
51 silly mapToRegistry using default registry
52 silly mapToRegistry registry http://registry.npmjs.org/
53 silly mapToRegistry data Result {
53 silly mapToRegistry   raw: '@angular/forms',
53 silly mapToRegistry   scope: '@angular',
53 silly mapToRegistry   name: '@angular/forms',
53 silly mapToRegistry   rawSpec: '',
53 silly mapToRegistry   spec: 'latest',
53 silly mapToRegistry   type: 'tag' }
54 silly mapToRegistry uri http://registry.npmjs.org/@angular%2fforms
55 verbose addNameRange registry:http://registry.npmjs.org/@angular%2fforms not in flight; fetching
56 silly cache add args [ '@angular/http@~2.1.1', null ]
57 verbose cache add spec @angular/http@~2.1.1
58 silly cache add parsed spec Result {
58 silly cache add   raw: '@angular/http@~2.1.1',
58 silly cache add   scope: '@angular',
58 silly cache add   name: '@angular/http',
58 silly cache add   rawSpec: '~2.1.1',
58 silly cache add   spec: '>=2.1.1 <2.2.0',
58 silly cache add   type: 'range' }
59 silly addNamed @angular/http@>=2.1.1 <2.2.0
60 verbose addNamed ">=2.1.1 <2.2.0" is a valid semver range for @angular/http
61 silly addNameRange { name: '@angular/http',
61 silly addNameRange   range: '>=2.1.1 <2.2.0',
61 silly addNameRange   hasData: false }
62 silly mapToRegistry name @angular/http
63 silly mapToRegistry scope (from package name) @angular
64 verbose mapToRegistry no registry URL found in name for scope @angular
65 silly mapToRegistry using default registry
66 silly mapToRegistry registry http://registry.npmjs.org/
67 silly mapToRegistry data Result {
67 silly mapToRegistry   raw: '@angular/http',
67 silly mapToRegistry   scope: '@angular',
67 silly mapToRegistry   name: '@angular/http',
67 silly mapToRegistry   rawSpec: '',
67 silly mapToRegistry   spec: 'latest',
67 silly mapToRegistry   type: 'tag' }
68 silly mapToRegistry uri http://registry.npmjs.org/@angular%2fhttp
69 verbose addNameRange registry:http://registry.npmjs.org/@angular%2fhttp not in flight; fetching
70 silly cache add args [ '@angular/platform-browser@~2.1.1', null ]
71 verbose cache add spec @angular/platform-browser@~2.1.1
72 silly cache add parsed spec Result {
72 silly cache add   raw: '@angular/platform-browser@~2.1.1',
72 silly cache add   scope: '@angular',
72 silly cache add   name: '@angular/platform-browser',
72 silly cache add   rawSpec: '~2.1.1',
72 silly cache add   spec: '>=2.1.1 <2.2.0',
72 silly cache add   type: 'range' }
73 silly addNamed @angular/platform-browser@>=2.1.1 <2.2.0
74 verbose addNamed ">=2.1.1 <2.2.0" is a valid semver range for @angular/platform-browser
75 silly addNameRange { name: '@angular/platform-browser',
75 silly addNameRange   range: '>=2.1.1 <2.2.0',
75 silly addNameRange   hasData: false }
76 silly mapToRegistry name @angular/platform-browser
77 silly mapToRegistry scope (from package name) @angular
78 verbose mapToRegistry no registry URL found in name for scope @angular
79 silly mapToRegistry using default registry
80 silly mapToRegistry registry http://registry.npmjs.org/
81 silly mapToRegistry data Result {
81 silly mapToRegistry   raw: '@angular/platform-browser',
81 silly mapToRegistry   scope: '@angular',
81 silly mapToRegistry   name: '@angular/platform-browser',
81 silly mapToRegistry   rawSpec: '',
81 silly mapToRegistry   spec: 'latest',
81 silly mapToRegistry   type: 'tag' }
82 silly mapToRegistry uri http://registry.npmjs.org/@angular%2fplatform-browser
83 verbose addNameRange registry:http://registry.npmjs.org/@angular%2fplatform-browser not in flight; fetching
84 silly cache add args [ '@angular/platform-browser-dynamic@~2.1.1', null ]
85 verbose cache add spec @angular/platform-browser-dynamic@~2.1.1
86 silly cache add parsed spec Result {
86 silly cache add   raw: '@angular/platform-browser-dynamic@~2.1.1',
86 silly cache add   scope: '@angular',
86 silly cache add   name: '@angular/platform-browser-dynamic',
86 silly cache add   rawSpec: '~2.1.1',
86 silly cache add   spec: '>=2.1.1 <2.2.0',
86 silly cache add   type: 'range' }
87 silly addNamed @angular/platform-browser-dynamic@>=2.1.1 <2.2.0
88 verbose addNamed ">=2.1.1 <2.2.0" is a valid semver range for @angular/platform-browser-dynamic
89 silly addNameRange { name: '@angular/platform-browser-dynamic',
89 silly addNameRange   range: '>=2.1.1 <2.2.0',
89 silly addNameRange   hasData: false }
90 silly mapToRegistry name @angular/platform-browser-dynamic
91 silly mapToRegistry scope (from package name) @angular
92 verbose mapToRegistry no registry URL found in name for scope @angular
93 silly mapToRegistry using default registry
94 silly mapToRegistry registry http://registry.npmjs.org/
95 silly mapToRegistry data Result {
95 silly mapToRegistry   raw: '@angular/platform-browser-dynamic',
95 silly mapToRegistry   scope: '@angular',
95 silly mapToRegistry   name: '@angular/platform-browser-dynamic',
95 silly mapToRegistry   rawSpec: '',
95 silly mapToRegistry   spec: 'latest',
95 silly mapToRegistry   type: 'tag' }
96 silly mapToRegistry uri http://registry.npmjs.org/@angular%2fplatform-browser-dynamic
97 verbose addNameRange registry:http://registry.npmjs.org/@angular%2fplatform-browser-dynamic not in flight; fetching
98 silly cache add args [ '@angular/router@~3.1.1', null ]
99 verbose cache add spec @angular/router@~3.1.1
100 silly cache add parsed spec Result {
100 silly cache add   raw: '@angular/router@~3.1.1',
100 silly cache add   scope: '@angular',
100 silly cache add   name: '@angular/router',
100 silly cache add   rawSpec: '~3.1.1',
100 silly cache add   spec: '>=3.1.1 <3.2.0',
100 silly cache add   type: 'range' }
101 silly addNamed @angular/router@>=3.1.1 <3.2.0
102 verbose addNamed ">=3.1.1 <3.2.0" is a valid semver range for @angular/router
103 silly addNameRange { name: '@angular/router',
103 silly addNameRange   range: '>=3.1.1 <3.2.0',
103 silly addNameRange   hasData: false }
104 silly mapToRegistry name @angular/router
105 silly mapToRegistry scope (from package name) @angular
106 verbose mapToRegistry no registry URL found in name for scope @angular
107 silly mapToRegistry using default registry
108 silly mapToRegistry registry http://registry.npmjs.org/
109 silly mapToRegistry data Result {
109 silly mapToRegistry   raw: '@angular/router',
109 silly mapToRegistry   scope: '@angular',
109 silly mapToRegistry   name: '@angular/router',
109 silly mapToRegistry   rawSpec: '',
109 silly mapToRegistry   spec: 'latest',
109 silly mapToRegistry   type: 'tag' }
110 silly mapToRegistry uri http://registry.npmjs.org/@angular%2frouter
111 verbose addNameRange registry:http://registry.npmjs.org/@angular%2frouter not in flight; fetching
112 silly cache add args [ '@angular/upgrade@~2.1.1', null ]
113 verbose cache add spec @angular/upgrade@~2.1.1
114 silly cache add parsed spec Result {
114 silly cache add   raw: '@angular/upgrade@~2.1.1',
114 silly cache add   scope: '@angular',
114 silly cache add   name: '@angular/upgrade',
114 silly cache add   rawSpec: '~2.1.1',
114 silly cache add   spec: '>=2.1.1 <2.2.0',
114 silly cache add   type: 'range' }
115 silly addNamed @angular/upgrade@>=2.1.1 <2.2.0
116 verbose addNamed ">=2.1.1 <2.2.0" is a valid semver range for @angular/upgrade
117 silly addNameRange { name: '@angular/upgrade',
117 silly addNameRange   range: '>=2.1.1 <2.2.0',
117 silly addNameRange   hasData: false }
118 silly mapToRegistry name @angular/upgrade
119 silly mapToRegistry scope (from package name) @angular
120 verbose mapToRegistry no registry URL found in name for scope @angular
121 silly mapToRegistry using default registry
122 silly mapToRegistry registry http://registry.npmjs.org/
123 silly mapToRegistry data Result {
123 silly mapToRegistry   raw: '@angular/upgrade',
123 silly mapToRegistry   scope: '@angular',
123 silly mapToRegistry   name: '@angular/upgrade',
123 silly mapToRegistry   rawSpec: '',
123 silly mapToRegistry   spec: 'latest',
123 silly mapToRegistry   type: 'tag' }
124 silly mapToRegistry uri http://registry.npmjs.org/@angular%2fupgrade
125 verbose addNameRange registry:http://registry.npmjs.org/@angular%2fupgrade not in flight; fetching
126 silly cache add args [ 'angular-in-memory-web-api@~0.1.13', null ]
127 verbose cache add spec angular-in-memory-web-api@~0.1.13
128 silly cache add parsed spec Result {
128 silly cache add   raw: 'angular-in-memory-web-api@~0.1.13',
128 silly cache add   scope: null,
128 silly cache add   name: 'angular-in-memory-web-api',
128 silly cache add   rawSpec: '~0.1.13',
128 silly cache add   spec: '>=0.1.13 <0.2.0',
128 silly cache add   type: 'range' }
129 silly addNamed angular-in-memory-web-api@>=0.1.13 <0.2.0
130 verbose addNamed ">=0.1.13 <0.2.0" is a valid semver range for angular-in-memory-web-api
131 silly addNameRange { name: 'angular-in-memory-web-api',
131 silly addNameRange   range: '>=0.1.13 <0.2.0',
131 silly addNameRange   hasData: false }
132 silly mapToRegistry name angular-in-memory-web-api
133 silly mapToRegistry using default registry
134 silly mapToRegistry registry http://registry.npmjs.org/
135 silly mapToRegistry data Result {
135 silly mapToRegistry   raw: 'angular-in-memory-web-api',
135 silly mapToRegistry   scope: null,
135 silly mapToRegistry   name: 'angular-in-memory-web-api',
135 silly mapToRegistry   rawSpec: '',
135 silly mapToRegistry   spec: 'latest',
135 silly mapToRegistry   type: 'tag' }
136 silly mapToRegistry uri http://registry.npmjs.org/angular-in-memory-web-api
137 verbose addNameRange registry:http://registry.npmjs.org/angular-in-memory-web-api not in flight; fetching
138 silly cache add args [ 'bootstrap@^3.3.7', null ]
139 verbose cache add spec bootstrap@^3.3.7
140 silly cache add parsed spec Result {
140 silly cache add   raw: 'bootstrap@^3.3.7',
140 silly cache add   scope: null,
140 silly cache add   name: 'bootstrap',
140 silly cache add   rawSpec: '^3.3.7',
140 silly cache add   spec: '>=3.3.7 <4.0.0',
140 silly cache add   type: 'range' }
141 silly addNamed bootstrap@>=3.3.7 <4.0.0
142 verbose addNamed ">=3.3.7 <4.0.0" is a valid semver range for bootstrap
143 silly addNameRange { name: 'bootstrap', range: '>=3.3.7 <4.0.0', hasData: false }
144 silly mapToRegistry name bootstrap
145 silly mapToRegistry using default registry
146 silly mapToRegistry registry http://registry.npmjs.org/
147 silly mapToRegistry data Result {
147 silly mapToRegistry   raw: 'bootstrap',
147 silly mapToRegistry   scope: null,
147 silly mapToRegistry   name: 'bootstrap',
147 silly mapToRegistry   rawSpec: '',
147 silly mapToRegistry   spec: 'latest',
147 silly mapToRegistry   type: 'tag' }
148 silly mapToRegistry uri http://registry.npmjs.org/bootstrap
149 verbose addNameRange registry:http://registry.npmjs.org/bootstrap not in flight; fetching
150 silly cache add args [ 'core-js@^2.4.1', null ]
151 verbose cache add spec core-js@^2.4.1
152 silly cache add parsed spec Result {
152 silly cache add   raw: 'core-js@^2.4.1',
152 silly cache add   scope: null,
152 silly cache add   name: 'core-js',
152 silly cache add   rawSpec: '^2.4.1',
152 silly cache add   spec: '>=2.4.1 <3.0.0',
152 silly cache add   type: 'range' }
153 silly addNamed core-js@>=2.4.1 <3.0.0
154 verbose addNamed ">=2.4.1 <3.0.0" is a valid semver range for core-js
155 silly addNameRange { name: 'core-js', range: '>=2.4.1 <3.0.0', hasData: false }
156 silly mapToRegistry name core-js
157 silly mapToRegistry using default registry
158 silly mapToRegistry registry http://registry.npmjs.org/
159 silly mapToRegistry data Result {
159 silly mapToRegistry   raw: 'core-js',
159 silly mapToRegistry   scope: null,
159 silly mapToRegistry   name: 'core-js',
159 silly mapToRegistry   rawSpec: '',
159 silly mapToRegistry   spec: 'latest',
159 silly mapToRegistry   type: 'tag' }
160 silly mapToRegistry uri http://registry.npmjs.org/core-js
161 verbose addNameRange registry:http://registry.npmjs.org/core-js not in flight; fetching
162 silly cache add args [ 'reflect-metadata@^0.1.8', null ]
163 verbose cache add spec reflect-metadata@^0.1.8
164 silly cache add parsed spec Result {
164 silly cache add   raw: 'reflect-metadata@^0.1.8',
164 silly cache add   scope: null,
164 silly cache add   name: 'reflect-metadata',
164 silly cache add   rawSpec: '^0.1.8',
164 silly cache add   spec: '>=0.1.8 <0.2.0',
164 silly cache add   type: 'range' }
165 silly addNamed reflect-metadata@>=0.1.8 <0.2.0
166 verbose addNamed ">=0.1.8 <0.2.0" is a valid semver range for reflect-metadata
167 silly addNameRange { name: 'reflect-metadata',
167 silly addNameRange   range: '>=0.1.8 <0.2.0',
167 silly addNameRange   hasData: false }
168 silly mapToRegistry name reflect-metadata
169 silly mapToRegistry using default registry
170 silly mapToRegistry registry http://registry.npmjs.org/
171 silly mapToRegistry data Result {
171 silly mapToRegistry   raw: 'reflect-metadata',
171 silly mapToRegistry   scope: null,
171 silly mapToRegistry   name: 'reflect-metadata',
171 silly mapToRegistry   rawSpec: '',
171 silly mapToRegistry   spec: 'latest',
171 silly mapToRegistry   type: 'tag' }
172 silly mapToRegistry uri http://registry.npmjs.org/reflect-metadata
173 verbose addNameRange registry:http://registry.npmjs.org/reflect-metadata not in flight; fetching
174 silly cache add args [ 'rxjs@5.0.0-beta.12', null ]
175 verbose cache add spec rxjs@5.0.0-beta.12
176 silly cache add parsed spec Result {
176 silly cache add   raw: 'rxjs@5.0.0-beta.12',
176 silly cache add   scope: null,
176 silly cache add   name: 'rxjs',
176 silly cache add   rawSpec: '5.0.0-beta.12',
176 silly cache add   spec: '5.0.0-beta.12',
176 silly cache add   type: 'version' }
177 silly addNamed rxjs@5.0.0-beta.12
178 verbose addNamed "5.0.0-beta.12" is a plain semver version for rxjs
179 silly mapToRegistry name rxjs
180 silly mapToRegistry using default registry
181 silly mapToRegistry registry http://registry.npmjs.org/
182 silly mapToRegistry data Result {
182 silly mapToRegistry   raw: 'rxjs',
182 silly mapToRegistry   scope: null,
182 silly mapToRegistry   name: 'rxjs',
182 silly mapToRegistry   rawSpec: '',
182 silly mapToRegistry   spec: 'latest',
182 silly mapToRegistry   type: 'tag' }
183 silly mapToRegistry uri http://registry.npmjs.org/rxjs
184 verbose addNameVersion registry:http://registry.npmjs.org/rxjs not in flight; fetching
185 silly cache add args [ 'systemjs@0.19.39', null ]
186 verbose cache add spec systemjs@0.19.39
187 silly cache add parsed spec Result {
187 silly cache add   raw: 'systemjs@0.19.39',
187 silly cache add   scope: null,
187 silly cache add   name: 'systemjs',
187 silly cache add   rawSpec: '0.19.39',
187 silly cache add   spec: '0.19.39',
187 silly cache add   type: 'version' }
188 silly addNamed systemjs@0.19.39
189 verbose addNamed "0.19.39" is a plain semver version for systemjs
190 silly mapToRegistry name systemjs
191 silly mapToRegistry using default registry
192 silly mapToRegistry registry http://registry.npmjs.org/
193 silly mapToRegistry data Result {
193 silly mapToRegistry   raw: 'systemjs',
193 silly mapToRegistry   scope: null,
193 silly mapToRegistry   name: 'systemjs',
193 silly mapToRegistry   rawSpec: '',
193 silly mapToRegistry   spec: 'latest',
193 silly mapToRegistry   type: 'tag' }
194 silly mapToRegistry uri http://registry.npmjs.org/systemjs
195 verbose addNameVersion registry:http://registry.npmjs.org/systemjs not in flight; fetching
196 silly cache add args [ 'zone.js@^0.6.25', null ]
197 verbose cache add spec zone.js@^0.6.25
198 silly cache add parsed spec Result {
198 silly cache add   raw: 'zone.js@^0.6.25',
198 silly cache add   scope: null,
198 silly cache add   name: 'zone.js',
198 silly cache add   rawSpec: '^0.6.25',
198 silly cache add   spec: '>=0.6.25 <0.7.0',
198 silly cache add   type: 'range' }
199 silly addNamed zone.js@>=0.6.25 <0.7.0
200 verbose addNamed ">=0.6.25 <0.7.0" is a valid semver range for zone.js
201 silly addNameRange { name: 'zone.js', range: '>=0.6.25 <0.7.0', hasData: false }
202 silly mapToRegistry name zone.js
203 silly mapToRegistry using default registry
204 silly mapToRegistry registry http://registry.npmjs.org/
205 silly mapToRegistry data Result {
205 silly mapToRegistry   raw: 'zone.js',
205 silly mapToRegistry   scope: null,
205 silly mapToRegistry   name: 'zone.js',
205 silly mapToRegistry   rawSpec: '',
205 silly mapToRegistry   spec: 'latest',
205 silly mapToRegistry   type: 'tag' }
206 silly mapToRegistry uri http://registry.npmjs.org/zone.js
207 verbose addNameRange registry:http://registry.npmjs.org/zone.js not in flight; fetching
208 silly cache add args [ '@types/core-js@^0.9.34', null ]
209 verbose cache add spec @types/core-js@^0.9.34
210 silly cache add parsed spec Result {
210 silly cache add   raw: '@types/core-js@^0.9.34',
210 silly cache add   scope: '@types',
210 silly cache add   name: '@types/core-js',
210 silly cache add   rawSpec: '^0.9.34',
210 silly cache add   spec: '>=0.9.34 <0.10.0',
210 silly cache add   type: 'range' }
211 silly addNamed @types/core-js@>=0.9.34 <0.10.0
212 verbose addNamed ">=0.9.34 <0.10.0" is a valid semver range for @types/core-js
213 silly addNameRange { name: '@types/core-js',
213 silly addNameRange   range: '>=0.9.34 <0.10.0',
213 silly addNameRange   hasData: false }
214 silly mapToRegistry name @types/core-js
215 silly mapToRegistry scope (from package name) @types
216 verbose mapToRegistry no registry URL found in name for scope @types
217 silly mapToRegistry using default registry
218 silly mapToRegistry registry http://registry.npmjs.org/
219 silly mapToRegistry data Result {
219 silly mapToRegistry   raw: '@types/core-js',
219 silly mapToRegistry   scope: '@types',
219 silly mapToRegistry   name: '@types/core-js',
219 silly mapToRegistry   rawSpec: '',
219 silly mapToRegistry   spec: 'latest',
219 silly mapToRegistry   type: 'tag' }
220 silly mapToRegistry uri http://registry.npmjs.org/@types%2fcore-js
221 verbose addNameRange registry:http://registry.npmjs.org/@types%2fcore-js not in flight; fetching
222 silly cache add args [ '@types/node@^6.0.45', null ]
223 verbose cache add spec @types/node@^6.0.45
224 silly cache add parsed spec Result {
224 silly cache add   raw: '@types/node@^6.0.45',
224 silly cache add   scope: '@types',
224 silly cache add   name: '@types/node',
224 silly cache add   rawSpec: '^6.0.45',
224 silly cache add   spec: '>=6.0.45 <7.0.0',
224 silly cache add   type: 'range' }
225 silly addNamed @types/node@>=6.0.45 <7.0.0
226 verbose addNamed ">=6.0.45 <7.0.0" is a valid semver range for @types/node
227 silly addNameRange { name: '@types/node', range: '>=6.0.45 <7.0.0', hasData: false }
228 silly mapToRegistry name @types/node
229 silly mapToRegistry scope (from package name) @types
230 verbose mapToRegistry no registry URL found in name for scope @types
231 silly mapToRegistry using default registry
232 silly mapToRegistry registry http://registry.npmjs.org/
233 silly mapToRegistry data Result {
233 silly mapToRegistry   raw: '@types/node',
233 silly mapToRegistry   scope: '@types',
233 silly mapToRegistry   name: '@types/node',
233 silly mapToRegistry   rawSpec: '',
233 silly mapToRegistry   spec: 'latest',
233 silly mapToRegistry   type: 'tag' }
234 silly mapToRegistry uri http://registry.npmjs.org/@types%2fnode
235 verbose addNameRange registry:http://registry.npmjs.org/@types%2fnode not in flight; fetching
236 silly cache add args [ 'concurrently@^3.0.0', null ]
237 verbose cache add spec concurrently@^3.0.0
238 silly cache add parsed spec Result {
238 silly cache add   raw: 'concurrently@^3.0.0',
238 silly cache add   scope: null,
238 silly cache add   name: 'concurrently',
238 silly cache add   rawSpec: '^3.0.0',
238 silly cache add   spec: '>=3.0.0 <4.0.0',
238 silly cache add   type: 'range' }
239 silly addNamed concurrently@>=3.0.0 <4.0.0
240 verbose addNamed ">=3.0.0 <4.0.0" is a valid semver range for concurrently
241 silly addNameRange { name: 'concurrently', range: '>=3.0.0 <4.0.0', hasData: false }
242 silly mapToRegistry name concurrently
243 silly mapToRegistry using default registry
244 silly mapToRegistry registry http://registry.npmjs.org/
245 silly mapToRegistry data Result {
245 silly mapToRegistry   raw: 'concurrently',
245 silly mapToRegistry   scope: null,
245 silly mapToRegistry   name: 'concurrently',
245 silly mapToRegistry   rawSpec: '',
245 silly mapToRegistry   spec: 'latest',
245 silly mapToRegistry   type: 'tag' }
246 silly mapToRegistry uri http://registry.npmjs.org/concurrently
247 verbose addNameRange registry:http://registry.npmjs.org/concurrently not in flight; fetching
248 silly cache add args [ 'lite-server@^2.2.2', null ]
249 verbose cache add spec lite-server@^2.2.2
250 silly cache add parsed spec Result {
250 silly cache add   raw: 'lite-server@^2.2.2',
250 silly cache add   scope: null,
250 silly cache add   name: 'lite-server',
250 silly cache add   rawSpec: '^2.2.2',
250 silly cache add   spec: '>=2.2.2 <3.0.0',
250 silly cache add   type: 'range' }
251 silly addNamed lite-server@>=2.2.2 <3.0.0
252 verbose addNamed ">=2.2.2 <3.0.0" is a valid semver range for lite-server
253 silly addNameRange { name: 'lite-server', range: '>=2.2.2 <3.0.0', hasData: false }
254 silly mapToRegistry name lite-server
255 silly mapToRegistry using default registry
256 silly mapToRegistry registry http://registry.npmjs.org/
257 silly mapToRegistry data Result {
257 silly mapToRegistry   raw: 'lite-server',
257 silly mapToRegistry   scope: null,
257 silly mapToRegistry   name: 'lite-server',
257 silly mapToRegistry   rawSpec: '',
257 silly mapToRegistry   spec: 'latest',
257 silly mapToRegistry   type: 'tag' }
258 silly mapToRegistry uri http://registry.npmjs.org/lite-server
259 verbose addNameRange registry:http://registry.npmjs.org/lite-server not in flight; fetching
260 silly cache add args [ 'typescript@^2.0.3', null ]
261 verbose cache add spec typescript@^2.0.3
262 silly cache add parsed spec Result {
262 silly cache add   raw: 'typescript@^2.0.3',
262 silly cache add   scope: null,
262 silly cache add   name: 'typescript',
262 silly cache add   rawSpec: '^2.0.3',
262 silly cache add   spec: '>=2.0.3 <3.0.0',
262 silly cache add   type: 'range' }
263 silly addNamed typescript@>=2.0.3 <3.0.0
264 verbose addNamed ">=2.0.3 <3.0.0" is a valid semver range for typescript
265 silly addNameRange { name: 'typescript', range: '>=2.0.3 <3.0.0', hasData: false }
266 silly mapToRegistry name typescript
267 silly mapToRegistry using default registry
268 silly mapToRegistry registry http://registry.npmjs.org/
269 silly mapToRegistry data Result {
269 silly mapToRegistry   raw: 'typescript',
269 silly mapToRegistry   scope: null,
269 silly mapToRegistry   name: 'typescript',
269 silly mapToRegistry   rawSpec: '',
269 silly mapToRegistry   spec: 'latest',
269 silly mapToRegistry   type: 'tag' }
270 silly mapToRegistry uri http://registry.npmjs.org/typescript
271 verbose addNameRange registry:http://registry.npmjs.org/typescript not in flight; fetching
272 silly cache add args [ '@angular/common@~2.1.1', null ]
273 verbose cache add spec @angular/common@~2.1.1
274 silly cache add parsed spec Result {
274 silly cache add   raw: '@angular/common@~2.1.1',
274 silly cache add   scope: '@angular',
274 silly cache add   name: '@angular/common',
274 silly cache add   rawSpec: '~2.1.1',
274 silly cache add   spec: '>=2.1.1 <2.2.0',
274 silly cache add   type: 'range' }
275 silly addNamed @angular/common@>=2.1.1 <2.2.0
276 verbose addNamed ">=2.1.1 <2.2.0" is a valid semver range for @angular/common
277 silly addNameRange { name: '@angular/common',
277 silly addNameRange   range: '>=2.1.1 <2.2.0',
277 silly addNameRange   hasData: false }
278 silly mapToRegistry name @angular/common
279 silly mapToRegistry scope (from package name) @angular
280 verbose mapToRegistry no registry URL found in name for scope @angular
281 silly mapToRegistry using default registry
282 silly mapToRegistry registry http://registry.npmjs.org/
283 silly mapToRegistry data Result {
283 silly mapToRegistry   raw: '@angular/common',
283 silly mapToRegistry   scope: '@angular',
283 silly mapToRegistry   name: '@angular/common',
283 silly mapToRegistry   rawSpec: '',
283 silly mapToRegistry   spec: 'latest',
283 silly mapToRegistry   type: 'tag' }
284 silly mapToRegistry uri http://registry.npmjs.org/@angular%2fcommon
285 verbose addNameRange registry:http://registry.npmjs.org/@angular%2fcommon not in flight; fetching
286 verbose request uri http://registry.npmjs.org/@angular%2fcompiler
287 verbose request no auth needed
288 info attempt registry request try #1 at 9:11:31 AM
289 verbose request id dac7d92f191be2ae
290 http request GET http://registry.npmjs.org/@angular%2fcompiler
291 verbose request uri http://registry.npmjs.org/@angular%2fcore
292 verbose request no auth needed
293 info attempt registry request try #1 at 9:11:31 AM
294 http request GET http://registry.npmjs.org/@angular%2fcore
295 verbose request uri http://registry.npmjs.org/@angular%2fforms
296 verbose request no auth needed
297 info attempt registry request try #1 at 9:11:31 AM
298 http request GET http://registry.npmjs.org/@angular%2fforms
299 verbose request uri http://registry.npmjs.org/@angular%2fhttp
300 verbose request no auth needed
301 info attempt registry request try #1 at 9:11:31 AM
302 http request GET http://registry.npmjs.org/@angular%2fhttp
303 verbose request uri http://registry.npmjs.org/@angular%2fplatform-browser
304 verbose request no auth needed
305 info attempt registry request try #1 at 9:11:31 AM
306 http request GET http://registry.npmjs.org/@angular%2fplatform-browser
307 verbose request uri http://registry.npmjs.org/@angular%2fplatform-browser-dynamic
308 verbose request no auth needed
309 info attempt registry request try #1 at 9:11:31 AM
310 http request GET http://registry.npmjs.org/@angular%2fplatform-browser-dynamic
311 verbose request uri http://registry.npmjs.org/@angular%2frouter
312 verbose request no auth needed
313 info attempt registry request try #1 at 9:11:31 AM
314 http request GET http://registry.npmjs.org/@angular%2frouter
315 verbose request uri http://registry.npmjs.org/@angular%2fupgrade
316 verbose request no auth needed
317 info attempt registry request try #1 at 9:11:31 AM
318 http request GET http://registry.npmjs.org/@angular%2fupgrade
319 verbose request uri http://registry.npmjs.org/angular-in-memory-web-api
320 verbose request no auth needed
321 info attempt registry request try #1 at 9:11:31 AM
322 http request GET http://registry.npmjs.org/angular-in-memory-web-api
323 verbose request uri http://registry.npmjs.org/bootstrap
324 verbose request no auth needed
325 info attempt registry request try #1 at 9:11:31 AM
326 http request GET http://registry.npmjs.org/bootstrap
327 verbose request uri http://registry.npmjs.org/core-js
328 verbose request no auth needed
329 info attempt registry request try #1 at 9:11:31 AM
330 http request GET http://registry.npmjs.org/core-js
331 verbose request uri http://registry.npmjs.org/reflect-metadata
332 verbose request no auth needed
333 info attempt registry request try #1 at 9:11:31 AM
334 http request GET http://registry.npmjs.org/reflect-metadata
335 verbose request uri http://registry.npmjs.org/rxjs
336 verbose request no auth needed
337 info attempt registry request try #1 at 9:11:31 AM
338 http request GET http://registry.npmjs.org/rxjs
339 verbose request uri http://registry.npmjs.org/systemjs
340 verbose request no auth needed
341 info attempt registry request try #1 at 9:11:31 AM
342 http request GET http://registry.npmjs.org/systemjs
343 verbose request uri http://registry.npmjs.org/zone.js
344 verbose request no auth needed
345 info attempt registry request try #1 at 9:11:31 AM
346 http request GET http://registry.npmjs.org/zone.js
347 verbose request uri http://registry.npmjs.org/@types%2fcore-js
348 verbose request no auth needed
349 info attempt registry request try #1 at 9:11:31 AM
350 http request GET http://registry.npmjs.org/@types%2fcore-js
351 verbose request uri http://registry.npmjs.org/@types%2fnode
352 verbose request no auth needed
353 info attempt registry request try #1 at 9:11:31 AM
354 http request GET http://registry.npmjs.org/@types%2fnode
355 verbose request uri http://registry.npmjs.org/concurrently
356 verbose request no auth needed
357 info attempt registry request try #1 at 9:11:31 AM
358 http request GET http://registry.npmjs.org/concurrently
359 verbose request uri http://registry.npmjs.org/lite-server
360 verbose request no auth needed
361 info attempt registry request try #1 at 9:11:31 AM
362 http request GET http://registry.npmjs.org/lite-server
363 verbose request uri http://registry.npmjs.org/typescript
364 verbose request no auth needed
365 info attempt registry request try #1 at 9:11:31 AM
366 http request GET http://registry.npmjs.org/typescript
367 verbose request uri http://registry.npmjs.org/@angular%2fcommon
368 verbose request no auth needed
369 info attempt registry request try #1 at 9:11:31 AM
370 http request GET http://registry.npmjs.org/@angular%2fcommon
371 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
372 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
373 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
374 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
375 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
376 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
377 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
378 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
379 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
380 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
381 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
382 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
383 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
384 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
385 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
386 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
387 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
388 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
389 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
390 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
391 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
392 info attempt registry request try #2 at 9:11:42 AM
393 http request GET http://registry.npmjs.org/@angular%2fplatform-browser-dynamic
394 info attempt registry request try #2 at 9:11:42 AM
395 http request GET http://registry.npmjs.org/@angular%2frouter
396 info attempt registry request try #2 at 9:11:42 AM
397 http request GET http://registry.npmjs.org/@angular%2fupgrade
398 info attempt registry request try #2 at 9:11:42 AM
399 http request GET http://registry.npmjs.org/reflect-metadata
400 info attempt registry request try #2 at 9:11:42 AM
401 http request GET http://registry.npmjs.org/rxjs
402 info attempt registry request try #2 at 9:11:42 AM
403 http request GET http://registry.npmjs.org/concurrently
404 info attempt registry request try #2 at 9:11:42 AM
405 http request GET http://registry.npmjs.org/@angular%2fcommon
406 info attempt registry request try #2 at 9:11:42 AM
407 http request GET http://registry.npmjs.org/@angular%2fcompiler
408 info attempt registry request try #2 at 9:11:42 AM
409 http request GET http://registry.npmjs.org/zone.js
410 info attempt registry request try #2 at 9:11:42 AM
411 http request GET http://registry.npmjs.org/systemjs
412 info attempt registry request try #2 at 9:11:42 AM
413 http request GET http://registry.npmjs.org/@angular%2fcore
414 info attempt registry request try #2 at 9:11:42 AM
415 http request GET http://registry.npmjs.org/lite-server
416 info attempt registry request try #2 at 9:11:42 AM
417 http request GET http://registry.npmjs.org/angular-in-memory-web-api
418 info attempt registry request try #2 at 9:11:42 AM
419 http request GET http://registry.npmjs.org/@angular%2fplatform-browser
420 info attempt registry request try #2 at 9:11:42 AM
421 http request GET http://registry.npmjs.org/typescript
422 info attempt registry request try #2 at 9:11:42 AM
423 http request GET http://registry.npmjs.org/@types%2fnode
424 info attempt registry request try #2 at 9:11:42 AM
425 http request GET http://registry.npmjs.org/core-js
426 info attempt registry request try #2 at 9:11:42 AM
427 http request GET http://registry.npmjs.org/@types%2fcore-js
428 info attempt registry request try #2 at 9:11:42 AM
429 http request GET http://registry.npmjs.org/bootstrap
430 info attempt registry request try #2 at 9:11:42 AM
431 http request GET http://registry.npmjs.org/@angular%2fhttp
432 info attempt registry request try #2 at 9:11:42 AM
433 http request GET http://registry.npmjs.org/@angular%2fforms
434 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
435 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
436 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
437 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
438 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
439 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
440 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
441 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
442 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
443 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
444 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
445 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
446 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
447 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
448 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
449 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
450 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
451 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
452 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
453 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
454 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.16.162:80
455 info attempt registry request try #3 at 9:12:43 AM
456 http request GET http://registry.npmjs.org/@angular%2fplatform-browser-dynamic
457 info attempt registry request try #3 at 9:12:43 AM
458 http request GET http://registry.npmjs.org/@angular%2frouter
459 info attempt registry request try #3 at 9:12:43 AM
460 http request GET http://registry.npmjs.org/@angular%2fupgrade
461 info attempt registry request try #3 at 9:12:43 AM
462 http request GET http://registry.npmjs.org/concurrently
463 info attempt registry request try #3 at 9:12:43 AM
464 http request GET http://registry.npmjs.org/@angular%2fcommon
465 info attempt registry request try #3 at 9:12:43 AM
466 http request GET http://registry.npmjs.org/rxjs
467 info attempt registry request try #3 at 9:12:43 AM
468 http request GET http://registry.npmjs.org/reflect-metadata
469 info attempt registry request try #3 at 9:12:43 AM
470 http request GET http://registry.npmjs.org/typescript
471 info attempt registry request try #3 at 9:12:43 AM
472 http request GET http://registry.npmjs.org/zone.js
473 info attempt registry request try #3 at 9:12:43 AM
474 http request GET http://registry.npmjs.org/lite-server
475 info attempt registry request try #3 at 9:12:43 AM
476 http request GET http://registry.npmjs.org/angular-in-memory-web-api
477 info attempt registry request try #3 at 9:12:43 AM
478 http request GET http://registry.npmjs.org/@angular%2fforms
479 info attempt registry request try #3 at 9:12:43 AM
480 http request GET http://registry.npmjs.org/@angular%2fhttp
481 info attempt registry request try #3 at 9:12:43 AM
482 http request GET http://registry.npmjs.org/@types%2fnode
483 info attempt registry request try #3 at 9:12:43 AM
484 http request GET http://registry.npmjs.org/core-js
485 info attempt registry request try #3 at 9:12:43 AM
486 http request GET http://registry.npmjs.org/@angular%2fcore
487 info attempt registry request try #3 at 9:12:43 AM
488 http request GET http://registry.npmjs.org/@types%2fcore-js
489 info attempt registry request try #3 at 9:12:43 AM
490 http request GET http://registry.npmjs.org/@angular%2fplatform-browser
491 info attempt registry request try #3 at 9:12:43 AM
492 http request GET http://registry.npmjs.org/@angular%2fcompiler
493 info attempt registry request try #3 at 9:12:43 AM
494 http request GET http://registry.npmjs.org/systemjs
495 info attempt registry request try #3 at 9:12:43 AM
496 http request GET http://registry.npmjs.org/bootstrap
497 verbose stack Error: connect ECONNREFUSED 151.101.16.162:80
497 verbose stack     at Object.exports._errnoException (util.js:907:11)
497 verbose stack     at exports._exceptionWithHostPort (util.js:930:20)
497 verbose stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)
498 verbose cwd c:\angular-quickstart
499 error Windows_NT 6.1.7601
500 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
501 error node v4.6.1
502 error npm  v2.15.9
503 error code ECONNREFUSED
504 error errno ECONNREFUSED
505 error syscall connect
506 error Error: connect ECONNREFUSED 151.101.16.162:80
506 error     at Object.exports._errnoException (util.js:907:11)
506 error     at exports._exceptionWithHostPort (util.js:930:20)
506 error     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)
506 error  { [Error: connect ECONNREFUSED 151.101.16.162:80]
506 error   code: 'ECONNREFUSED',
506 error   errno: 'ECONNREFUSED',
506 error   syscall: 'connect',
506 error   address: '151.101.16.162',
506 error   port: 80,
506 error   parent: 'angular-quickstart' }
507 error If you are behind a proxy, please make sure that the
507 error 'proxy' config is set properly.  See: 'npm help config'
508 verbose exit [ 1, true ]
```

**Comment by netpoetica** [comment]
I got this as well when trying to install newest npm from 5.3.0 to latest

```
407 Proxy Authentication Required: npm@latest
```

Logs:
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/rosenbek/.nvm/versions/node/v8.6.0/bin/node',
1 verbose cli   '/Users/rosenbek/.nvm/versions/node/v8.6.0/bin/npm',
1 verbose cli   'i',
1 verbose cli   '-g',
1 verbose cli   'npm' ]
2 info using npm@5.3.0
3 info using node@v8.6.0
4 verbose npm-session 18df254ce9eb20b8
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 407 https://registry.npmjs.org/npm 117ms
8 silly fetchPackageMetaData error for npm@latest 407 Proxy Authentication Required: npm@latest
9 verbose stack Error: 407 Proxy Authentication Required: npm@latest
9 verbose stack     at fetch.then.res (/Users/rosenbek/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:41:19)
9 verbose stack     at tryCatcher (/Users/rosenbek/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (/Users/rosenbek/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
9 verbose stack     at Promise._settlePromise (/Users/rosenbek/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (/Users/rosenbek/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
9 verbose stack     at Promise._settlePromises (/Users/rosenbek/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
9 verbose stack     at Async._drainQueue (/Users/rosenbek/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
9 verbose stack     at Async._drainQueues (/Users/rosenbek/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues (/Users/rosenbek/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
9 verbose stack     at runCallback (timers.js:781:20)
9 verbose stack     at tryOnImmediate (timers.js:743:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:714:5)
10 verbose cwd /Users/rosenbek/workspace/my-project
11 verbose Darwin 16.7.0
12 verbose argv "/Users/rosenbek/.nvm/versions/node/v8.6.0/bin/node" "/Users/rosenbek/.nvm/versions/node/v8.6.0/bin/npm" "i" "-g" "npm"
13 verbose node v8.6.0
14 verbose npm  v5.3.0
15 error code E407
16 error 407 Proxy Authentication Required: npm@latest
17 verbose exit [ 1, true ]
```

I am definitely behind a corporate proxy, but I am inlining credentials (http_proxy and https_proxy, and no_proxy) at the time I run `npm i` - this works all of the time for npm installs.

```
node -v
> v8.6.0

npm -v
> 5.3.0
```

Update: solved with https://github.com/npm/npm/issues/17396#issuecomment-334123228

**Comment by sverissimo** [comment]
The only way I got my problem fixed was adding proxy to environmental variables:

https://docs.cloudfoundry.org/cf-cli/http-proxy.html#windows

(then using the npm set proxy command)

**Comment by kratipantjoshi** [comment]
I have tried adding the proxy and https-proxy to environment variables as described but I am still getting the 'Authentication error'.

Command I executed: 
$ npm install -g gulp

Extract of Logs:

12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "gulp"
13 verbose node v8.11.1
14 verbose npm  v5.6.0
15 error code E407
16 error 407 Proxy Authentication Required: gulp@latest
17 verbose exit [ 1, true ]

**Comment by Viet27th** [comment]
You can try change proxy in file .npmrc , check user name, password and proxy in this file.
How to find .npmrc file : click icon window in bottom left taskbar -> enter .npmrc for search
Sorry for my English.

**Comment by nathanaelking** [comment]
I faced the same problem. It is sorted by changing the `https-proxy=<your` proxy name>:8080


This line is in .npmrc under your `c:\users\<your` name>

**Comment by EstherLacan** [comment]
npm config set proxy http://user:password@domain_proxy:port/
npm config set https-proxy http://user:password@domain_proxy:port

be careful the url should be encoded. for example this password 01xx!tr should be introduced as 01xx%21tr. use this site to encode your url https://www.url-encode-decode.com/

example:
user/password => user1/01xx!tr
domain:port of the proxy => mydomain.org:8000
=> in that case :

npm config set proxy http://user1:01xx%21tr@mydomain.org:8000/
npm config set https-proxy http://user1:01xx%21tr@mydomain.org:8000
method2 (edit node conifugration file):

the method 2 is easier because we will not be botherd with encoding the urls

1- edit node configuration file (in windows it's located in %USERPROFILE%\.npmrc, example C:\Users\Jack\.npmrc)

2- add these lines
proxy=http://user:password@domain_proxy:port/
https-proxy=https-proxy http://user:passwor`enter code here`d@domain_proxy:port

example :
if the :
user/password => user1/01xx!tr
domain:port of the proxy => mydomain.org:8000

=> the configuration file should be look like this:

proxy=http://user1:01xx!tr@mydomain.org:8000/
https-proxy=http://user1:01xx!tr@mydomain.org:8000
