### ISSUE TITLE
registry error parsing json

### ISSUE THREAD

**Issue by mahdiraad** [npm/npm#14612]
npm ERR! registry error parsing json
npm ERR! SyntaxError: Unexpected token 
�&m ERR! �SMo�0�+ȇ\�k>�S��Rsʡ_�$Z{o[�iBW����l7UU���x���ٓ��@6Ă�F9�&
  ���j�TL#cD��Fjw��lϺ.Ъ�j��Z����w���I�$�tg�e�fOX�I��
npm ERR! n�Gc���
npm ERR! |<���%�[\\�(]��1���N�i�@ڈ�H�أ��w�s�n���XQ���l�SB��4�/F�{��H��<�CP5K���;u� lt�2�Ʊ���_��I����>��jlf��o!JkG��U=h�xԷ ��(�0��1�D����NYYW,�ߤ�uR%Q�KQ�EYz/l�/8~�l��m�{ܐaYY%yQ<<-ꬌ˴�+�<+V)�9��#�F��׃�mEWt=G��S8CF��_-���Ӎb�j��1xyJ���}�[mO���c�B�#�o9��@�pf��g�2�+G��W���3ꚟ��
npm ERR! �JG������r����`�J�]
~��V�S��G��e�f�#�-GҾ/
                        �z����W��8��"ZEq��6�y�$��,"��Y6����_�&�쟞~��BR]
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/usr/lib/node_modules/npm-registry-client/lib/request.js:238:23)
npm ERR!     at Request.self.callback (/usr/lib/node_modules/request/index.js:148:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/node_modules/request/index.js:891:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/node_modules/request/index.js:842:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:929:16
npm ERR!     at process._tickCallback (node.js:419:13)
npm ERR! If you need help, you may report this log at:

**Comment by KenanY** [comment]
@mahdiraad Could you upload the full `npm-debug.log` to <https://gist.github.com/> and post the link here?

**Comment by AdamJacobMuller** [comment]
Hi,

I'm having the same issue. npm-debug.log is at https://gist.github.com/AdamJacobMuller/18a63f2a82415466227a09ba175cba78

I was able to work around it by hard-setting registry.npmjs.org to another IP in /etc/hosts so it seems like perhaps your CDN has some badly-cached/corrupted data on one node. (If you happen to need or are interested in a new CDN, I know a good one :) )

**Comment by kgryte** [comment]
I am also encountering this error. I have several builds on AppVeyor which have now started to randomly fail due to this error, and I recently found a job on Travis CI which failed for the same reason. 

The following issues seem related:

* npm/npm#14619
* npm/npm#14618
* npm/npm#14576

**Comment by legodude17** [comment]
This could be a `registry` issue, in  which case it should be filed there.

**Comment by kgryte** [comment]
@legodude17 Filed an issue: npm/registry#83.

**Comment by legodude17** [comment]
Looks like it was fixed over there. 😄 Can this be closed for now @KenanY?

**Comment by KenanY** [comment]
🎉

**Comment by KenanY** [comment]
Actually, is @mahdiraad also getting a 400 error or is it something else? Looks like garbage text to me.

**Comment by jlevym** [comment]
I am still having the same problem... error parsing jason. It started about 4 days ago and I have not managed since (tried about 15 minutes ago)
> default:  https://registry.npmjs.org/inherits/2.0.1
==> default: npm
==> default:  
==> default: ERR!
==> default:  
==> default: registry
==> default:  error parsing json
==> default: npm
==> default:  
==> default: ERR!
==> default:  SyntaxError: Unexpected token 
==> default: npm
==> default:  
==> default: ERR!
==> default:  ��R�n�0����)�Nۧ 9�\��"0Hq)ёD�K�P�{w�p�KЃ��>ff�s��A�kJ.�X��F�*<FK4�ꓩS59$��(���U��
==> default: npm
==> default:  
==> default: ERR!
==> default:  ���e�Q5F�4ހ<�<�߾�_8B��Jf�y����Aq�3�`t���B��:�{�җ�'��ҳ��2��Q/%���^�,D��#ӹ���7}��ɱ#@��Ezq��ط|��E�B5Ƈ4�L�iI�H*���H\�r94ȓ�?�hr�0mL����|�d��]w�P	�[���(�d��3�6/�0��8f�,v5u��ެvf��껻�~lw`�}���L�t�kc�{��UЪ�UY			P\�e��'�>�e��-\�2o�.<�J<����
2���)����2gW��������P�ciS~�H?"�������[�|��
==> default: npm
==> default:  
==> default: ERR!
==> default:  %�m
==> default: npm
==> default:  
==> default: ERR!
==> default:      at Object.parse (native)
==> default: npm
==> default:  
==> default: ERR!
==> default:      at RegClient.<anonymous> (/home/ubuntu/.nvm/v0.10.25/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:241:23)
==> default: npm
==> default:  
==> default: ERR!

**Comment by legodude17** [comment]
I know, but they both seems like registry errors, some give 400's others give garbage text. Anyway both were solved by the registry team. 😄

**Comment by legodude17** [comment]
That is very odd. I thought that @soldair fixed it. Pinging him.

**Comment by soldair** [comment]
shoot i was invalidating a different url pattern. let me fix my follower and you;ll be right as rain. thanks for your patience @jlevym

**Comment by soldair** [comment]
@jlevym i did purge this url just now so if its the only one you may be out of the woods.

**Comment by jlevym** [comment]
great, thanks.  I will try it again

**Comment by soldair** [comment]
ok a process is in place that will match these urls. if you request a url with a broken response it will repair it. on a second try it will work.

**Comment by jlevym** [comment]
so the build ran successfully - thanks VERY much.
