### ISSUE TITLE
npm install nock error 

### ISSUE THREAD

**Issue by bettyzhenya** [npm/npm#15390]
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\betty.lee\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "nock"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! code ENOSELF

npm ERR! Refusing to install nock as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\git\prototypes\mockServiceExamples\Nock\npm-debug.log

**Comment by KenanY** [comment]
@bettyzhenya Make sure that the `"name"` property in your `package.json` is not set to `"nock"`.

**Comment by KenanY** [comment]
@bettyzhenya I'm gonna assume this is resolved after https://github.com/npm/npm/issues/15392 :)

**Comment by bettyzhenya** [comment]
Yes

**Comment by bettyzhenya** [comment]
Hi Kenan
I am having new issue, can I just ask you here directly?

thanks

**Comment by bettyzhenya** [comment]
I changed my script file my_test.js , after I ran npm test, it still shows it ran on top of  my_test.spec.js under /test folder. Do I need to do npm clean?

Thanks

**Comment by KenanY** [comment]
@bettyzhenya I got no idea; `npm` has nothing to do with how your tests are executed.

**Comment by bettyzhenya** [comment]
Ok, may I ask what NPM do by run > npm test

Thanks


Betty

**Comment by KenanY** [comment]
@bettyzhenya `npm test` simply executes the `"test"` script that you have defined in your `package.json`.

**Comment by bettyzhenya** [comment]
I meant can I just create a file name test.js with
var nock = require('nock');

var couchdb = nock('http://myapp.iriscouch.com')
                .get('/users/1')
                .reply(200, {
                  _id: '123ABC',
                  _rev: '946B7D1C',
                  username: 'pgte',
                  email: 'pedro.teixeira@gmail.com'
                 });

Then run > npm test?


Regards

**Comment by bettyzhenya** [comment]
I see
