### ISSUE TITLE
npm crashes with symlinked packages in a monorepo

### ISSUE THREAD

**Issue by the-spyke** [npm/npm#19322]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I have a monorepo of several packages on the same level which depend on each other (I think this is pretty common in modern world). For local development dependencies are specified with `file:`, so they will be symlinks in npm 5.

1. npm 5.5.1 can't even do a fresh install in one of my packages:

```
npm ERR! /home/user/Projects/xxx/packages/package-a/node_modules/fsevents/node_modules/abbrev is not a child of /home/user/Projects/xxx/packages/package-b
```

2. npm 5.6.0 doesn't fail (as I understand has this issue fixed) gives me a hundred of similar warnings:

```
npm WARN rollback Rolling back abbrev@1.1.0 failed (this is probably harmless): /home/user/Projects/xxx/packages/package-a/node_modules/fsevents/node_modules/abbrev is not a child of /home/user/Projects/xxx/packages/package-b
```

I think it gives such a warning for every dependency of `fsevents`. And it is super slow while installing: 75 seconds instead of 21 second without symlinks.

### supporting information:

 - `npm -v` prints: 5.6.0
 - `node -v` prints: v8.9.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Ubuntu 17.04 x64 (4.10.0-40-generic)

**Comment by the-spyke** [comment]
Looks like it wasn't fixed properly in `5.6.0`. In some of my other modules:

```
npm WARN rollback Rolling back btoa-lite@1.0.0 failed (this is probably harmless): /home/user/Projects/xxx/packages/package-m/node_modules/btoa-lite is not a child of /home/user/Projects/xxx/packages/package-k
npm ERR! path /home/user/Projects/xxx/packages/package-k/node_modules/.staging/btoa-lite-1ddc739c
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/home/user/Projects/xxx/packages/package-k/node_modules/.staging/btoa-lite-1ddc739c' -> '/home/user/Projects/xxx/packages/package-m/node_modules/btoa-lite'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

The case is with 3 packages and a transient dependency:
```
package K --> package L
          --> package M
package L --> package M
package M --> btoa-lite
```

**Comment by sgnn7** [comment]
I'm getting two distinct modules with this same error (`npm WARN rollback Rolling back <some package> failed (this is probably harmless)` on Node v8.11.1 that fail the whole `npm install`. I automated a loop to download and install all available versions of npm to check which ones have this issue and all npm versions that work with Node v.8.11.1 (npm `v6.0.0-next` and below) all had this issue but `yarn` worked just fine.

My test scripts that run a Dockerfile that does an npm/yarn install of the relevant package.json to find the highest version that's working:

- `test_package_manager.sh`:
``` 
#!/bin/bash -e

npm_versions=$(npm show npm@* version | sort -r | awk '{ print $2 }' | tr -d "'")
yarn_versions=$(npm show yarn@* version | sort -r | awk '{ print $2 }' | tr -d "'")

# for version in $yarn_versions; do
for version in $npm_versions; do
  echo "------------------------------------------------------------------"
  echo "Trying: v$version..."
  echo
  echo

  echo "Pruning untagged images..."
  sudo docker image rm test_image -f &>/dev/null || true

  sudo docker images prune -f &>/dev/null || true

  echo "Pruning stale containers..."
  sudo docker container prune -f  &>/dev/null || true

  echo "Running: docker build --build-arg NPM_VERSION="$version" --build-arg YARN_VERSION="$version" ."
  sudo docker build --build-arg NPM_VERSION="$version" --build-arg YARN_VERSION="$version" -t test_image . || continue

  echo
  echo
  echo "Found working version: $version"
  echo
  exit 0
done
```

- `Dockerfile`:
```
FROM ubuntu:18.04

# Build args with some defaults that get overridden on CLI
ARG NPM_VERSION="5.6.0"
ARG YARN_VERSION="1.8.0"

RUN apt-get update && \
    apt-get dist-upgrade -y && \
    apt-get install -y apt-transport-https \
                       curl \
                       software-properties-common && \
    apt-get autoremove -y && \
    apt-get clean

RUN mkdir -p /root && \
    groupadd -r testgroup && \
    useradd -r -m -g testgroup testuser

# Get Node v8 directly from upstream
RUN curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - && \
    echo 'deb https://deb.nodesource.com/node_8.x bionic main' > /etc/apt/sources.list.d/nodesource.list && \
    apt-get update && \
    apt-get install -y nodejs && \
    apt-get clean

RUN npm install -g npm@$NPM_VERSION
# RUN npm install -g yarn@$YARN_VERSION

USER testuser
WORKDIR /home/testuser

COPY package.json /home/testuser
RUN npm install
# RUN yarn
```
- `package.json` is proprietary so I sadly cannot include it here

As a sidenote, if this is useful to include as a test harness for NPM, I can open a PR for it.

**Comment by sgnn7** [comment]
Ok - I found the minimum viable consistent way to reproduce the error and it's probably a race condition 
 (that @the-spyke mentioned as well) somewhere in mutually dependent module installations like this:
```
A -> B -> D
A -> C -> B -> D
```

To reproduce the test, create the file below and run it with:
```
sudo docker build --no-cache --build-arg NPM_VERSION=5.8.0 -t test_image .
```

`Dockerfile`:
```
FROM node:8

RUN groupadd -r testgroup && \
    useradd -r -m -g testgroup testuser

# Build args with some defaults
ARG NPM_VERSION="5.8.0"
RUN npm install -g npm@$NPM_VERSION

RUN mkdir -p /opt/dep1 /opt/dep2 /opt/main && \
    chown -R testuser:testgroup /opt

USER testuser
WORKDIR /opt/main

RUN echo '{"name":"dep1", "version":"0.0.1", "dependencies":{"dep2":"file:../dep2"}}' > /opt/dep1/package.json
RUN echo '{"name":"dep2", "version":"0.0.1", "dependencies":{"protobufjs":"^1.0.0"}}' > /opt/dep2/package.json
RUN echo '{"name":"main", "version":"0.0.1", "dependencies":{"dep1":"file:../dep1", "dep2":"file:../dep2"}}' > /opt/main/package.json

RUN npm install
```

The error that you should see should be something like this though I've seen a few different ones too:
```
npm WARN rollback Rolling back colour@0.7.1 failed (this is probably harmless): /opt/dep2/node_modules/colour is not a child of /opt/main
<snip>                                               
npm ERR! path /opt/main/node_modules/.staging/colour-989e150e
npm ERR! code ENOENT
npm ERR! errno -2                                                               
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/opt/main/node_modules/.staging/colour-989e150e' -> '/opt/dep2/node_modules/colour'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/testuser/.npm/_logs/2018-04-18T14_03_07_881Z-debug.log
```

**Comment by sgnn7** [comment]
If I had to take a guess, both parallel dependency resolutions (dep1 and dep2) try to install packages (`protobuf` in my test example) in the `dep2/node_modules` folder at the same time so they trample on each other's work.

In other news, I don't understand why dependencies aren't copied into the main module then resolved rather than the current approach where dependencies are resolved in their respective folders themselves - seems like a really bad design approach to me.

**Comment by the-spyke** [comment]
Still happens with `5.8.0` and basically makes `npm` useless for monorepos. `yarn` works fine and it also doesn't treat symlinks different: while `npm` installs all their dependencies privately, `yarn` uses the same approach as without symlinks (hoisting). I'd also like to see some `npm install` options to control this behavior. The `npm`'s current approach doesn't make sense to me most of the time.

**Comment by walerun** [comment]
This is also an issue for me.

**Comment by garthk** [comment]
I don't think this is just symlinks: replacing all my in-monorepo dependency “versions” with `../otherpkg` also causes `npm install --production` to consistently fail with `rolling back… failed (this is probably harmless)`, followed by the `sys call rename` as above.

**Comment by the-spyke** [comment]
@garthk Starting with `npm@5` specifying `../otherpkg` instead of a version will lead to a symlink creation instead of copying.
