### ISSUE TITLE
.npmignore not ignoring files when "files" is used in package.json

### ISSUE THREAD

**Issue by agrieve** [npm/npm#4479]
NPM docs say:

You can also provide a ".npmignore" file in the root of your package, which will keep files from being included, even if they would be picked up by the files array. The ".npmignore" file works just like a ".gitignore".

However, if you create a project with:
npm init
mkdir -p a/b/c
echo hi > a/b/c/foo
echo a/b/c > .npmignore

then a/b/c will be ignored (this is expected).

If you add "files": ["a"] to package.json, then a/b/c is _not_ ignored. (this is a bug I believe, as it's listed in .npmignore)

**Comment by Turbo87** [comment]
@iarna will this be fixed at some point? having the documentation tell something completely different than the actual (and even unit tested) behavior is really confusing and has caused quite a few packaging issues already... 😞

**Comment by iarna** [comment]
@Turbo87 It's not on our immediate todo list (which is currently consumed with npm@4 and fixing bugs in `npm shrinkwrap`). We'd be happy to take a PR for this though.

Overall the interaction between `.npmignore` and `files` is poorly documented and poorly understood, even on the CLI team.

**Comment by SimonSchick** [comment]
Also ran into this today when trying to clean up our `.npmignore`s.
`glob` support for `files` would be great.

Also in case of a conflict between `files` and `.npmignore` ideally you'd throw an error.

**Comment by Turbo87** [comment]
@npm-robot FWIW I don't agree with just closing issues even though the root problem still exists...

**Comment by robv8r** [comment]
Me either.  This issue still exists in node v6.11.2 with npm v5.4.0.  I do not have a files section, only a .npmignore file.

**Comment by mlynch** [comment]
One way around this is to add a `.gitignore` in a subfolder. For example, if you are including `assets/` in your `files` but want to ignore `assets/blah`, then add a `.gitignore` in `assets/` with `blah/`

**Comment by SimonSchick** [comment]
Hey, I came up with this solution:

```
/*
!/dist
```
this effectively negates the `.npmignore`, works pretty well for us!
