### ISSUE TITLE
Windows: NPM globalconfig path is a non-global, user-specific location

### ISSUE THREAD

**Issue by splatteredbits** [npm/npm#5753]
The npm globalconfig option is set to a user-specific location. In our environmet, node runs as an unprivileged user. We use DSC to configure our machines and run our automated setup scripts, which runs as the SYSTEM account. Because the account running node and configuring node are different, I can't configure node system-wide to use a specific prefix.

Steps to Reproduce:

 1. Install Node on Windows
 2. Run `npm config ls -l --global` and note that the `globalconfig` options points to the current user's APPDATA directory.
 3. Log in as another user, and run `npm config ls -l --global` and note the `globalconfig` options points to that users's APPDATA.

Thus, I have no way of configuring NPM for all users across the entire computer.

**Comment by smikes** [comment]
Is this still a problem for you?

I think that part of the issue here is that `global` means "across all modules" and stands opposed to "for this module only".  

For example, when I use `npm` I am using `nvm` to switch between versions of `node` and `npm`, and `npm install --global` actually winds up installing somewhere under `~/.nvm/versions...` -- this directory is only visible to me, and not shared with other users.

In any case, it sounds like you are trying to configure `npm` such that a globally installed module is available to all users on a specific machine.  `npm` works this way by default on Unix-like machines, where the `bin` scripts specified by `package.json` are installed to `/usr/local/bin` or similar.  If this is not working on Windows, then it should be classified as a bug.

When you reported this, you were using a then-current version of `npm`, but there have been a lot of improvements to npm since 1.4.14. Can you try updating your npm installation and let us know if the problem is still present in `npm@latest`

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
The location of `globalconfig` on Windows has done some changes, and is set via the `npmrc` file that the Node Windows installer drops into the npm folder on install. There's also some support inside npm for moving that configuration along when npm is used to upgrade itself that was broken for a while, but has been fixed for the last four months or so (one of the weirdest tests in npm makes sure that stays working). At this point I think we do have it pretty much sorted out, and so @smikes's advice about upgrading is sound, and I can close this issue as resolved.

**Comment by michahell** [comment]
This is definitely still an issue, and it is still the case for node stable v5.5.0 with a fresh install. Installing packages """globally""" installs packages in ```C:\Users\AppData\Roaming\npm\```.
Also the prefix is definitely accounted for in ```C:\Program Files (x86)\nodejs\node_modules\npm.npmrc``` in a fresh install on v5.5.0... Why isn't anybody experiencing issues with this? it seems kind of stupid :/

**Comment by mim-Armand** [comment]
Globally doesn't mean for "all users" it means accessible throughout the system since it's being injected in the sys env.
to use npm without (annoying) elaborated user it's way more convenient if it keeps installing the modules on the users local folder!

**Comment by jmtvms** [comment]
I just executed the command 
```batch
npm config set prefix "%ProgramFiles%\nodejs"
```
And now all users can use the installed node modules.
Make sure that the folder _%ProgramFiles%\nodejs_ is in the path system wide.

to undo the change just execute
```batch
npm config rm prefix
```
Removing the config make it goes back to the default settings.

**Comment by aTable** [comment]
I've run into this issue while provisioning a CI server on Windows and it was made so much more difficult than it should be imo.

I'm sure there's a reason why npm considers global to be on a per user basis however, I'd like to see @jmtvms solution above ship with node + npm by default as the current prefix of "%AppData%\npm" causing unnecessary issues.

**Comment by yorambi** [comment]
npm global directories should use the **%ProgramData%\npm** folder as per [KNOWNFOLDERID ](https://msdn.microsoft.com/en-us/library/windows/desktop/dd378457.aspx)and [CSIDL](https://msdn.microsoft.com/en-us/library/windows/desktop/bb762494.aspx) %APPDATA% is PERUSER "Folder Type" and not a global one.
Many applications on windows are using this global folder. And yes only Administrators can write there but anyone can read.

See git for example [installer: honor `%PROGRAMDATA%\Git\config` #50](https://github.com/git-for-windows/build-extra/pull/50/files) ...

**Comment by arangas** [comment]
@smikes This is still an issue...

- using `npm config set` saves the config to `c:\users\%username%\
- using `npm config set --global` saves the config to `c:\users\%username%\AppData\Roaming\npm\etc`

There doesn't seem to be a way to do this at the machine level.

**Comment by Go4th** [comment]
npm on my machine will not let me set the AppData\Roaming\npm as the config prefix so none of my packages are installed there but in my project directory which causes a mess with all of the .cmd files etc. When I run npm config get prefix -g it just shows me whichever directory I'm currently in, then when I run npm config set prefix "${APPDATA}/npm" -g it shows that it does "something". Then when I run npm config get prefix -g again, it still just shows me the folder I'm currently in. It does not change my npm prefix directory to the AppData directory. The npm folder in that directory is empty and never gets anything added to it when i use the -g when installing packages. Anyone have an idea? All other workstations work fine but this one.
