### ISSUE TITLE
npm installing without end (infinitely)

### ISSUE THREAD

**Issue by lucenty** [npm/npm#7318]
I have a trouble with npm and I haven't found solution in web.

Today I wanted to start my adventure with nodejs, npm, bower etc.

I use Windows 8.1.

I installed the newest nodejs (v0.12.0). I tried these steps with both x64 and x86 builds. I opened nodejs command line with administrative privileges. I updated npm to 2.5.0 version. When I run npm install bower -g I see a char that seems to show progress (it'is rolling) but nothing happens. Even if I leave it "working" for a 30 minutes, nothing happens. It never ends. When I type np ls -g it shows only npm@2.5.0 and it's dependencies.

Logs:

```
npm info it worked if it ends with ok
npm verb cli [ 'node',
npm verb cli   'C:\\Users\\Lucek\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   '--verbose',
npm verb cli   'install',
npm verb cli   'bower',
npm verb cli   '-g' ]
npm info using npm@2.5.0
npm info using node@v0.12.0
npm verb cache add spec bower
npm verb addNamed bower@*
npm verb addNameRange registry:https://registry.npmjs.org/bower not in flight; fetching
npm verb request uri https://registry.npmjs.org/bower
npm verb request no auth needed
npm info attempt registry request try #1 at 08:43:01
npm verb request id 8d309c5e387572c0
npm verb etag "CQDT3LW680UJR78VNWVFLN8Q7"
npm http request GET https://registry.npmjs.org/bower
npm http 200 https://registry.npmjs.org/bower
npm verb get saving bower to C:\Users\Lucek\AppData\Roaming\npm-cache\registry.npmjs.org\bower\.cache.json
npm verb addNamed bower@1.3.12
npm verb addRemoteTarball https://registry.npmjs.org/bower/-/bower-1.3.12.tgz not in flight; adding
npm verb addRemoteTarball [ 'https://registry.npmjs.org/bower/-/bower-1.3.12.tgz',
npm verb addRemoteTarball   '37de0edb3904baf90aee13384a1a379a05ee214c' ]
```

On stackoverflow (http://stackoverflow.com/questions/28384040/npm-install-does-nothing-how-make-it-work) I was proposed to try solution from https://github.com/npm/npm/issues/1198 but it didn't work for me. Please, help.

**Comment by tjlongo** [comment]
I have the exact same issue and log.

**Comment by othiym23** [comment]
This isn't a behavior I've seen, nor can I reproduce this with `npm@2.5.1` and Node.js 0.12.0 on either OS X Yosemite or Windows 8.1. When running that same command, I get a much much greater volume of output, so it seems that for the two of you something is getting hung up early in the installation process. 

Does this problem persist if you run `npm cache clean`?

If so, are you able to install packages aside from Bower? If so, can you run `npm -g install rimraf` and then run `rimraf C:\Users\Lucek\AppData\Roaming\npm-cache`?

**Comment by tjlongo** [comment]
We cleaned the cache and tried installing rpm again, same result, cleaned cache, tried installing rimraf, with same error.

**Comment by lucenty** [comment]
Cleaning cache doesn't help

**Comment by lucenty** [comment]
I tried to find solution myself.
I've substituted npm directory by npm 2.6.1 downloaded from https://github.com/npm/npm/releases and tried again - nothing changes.
I tried also npm info - and it showed me this code:

```
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\Users\\Lucek\\AppData\\Roaming\\npm\\node_modules\\npm
\\bin\\npm-cli.js" "info"
npm ERR! node v0.12.0
npm ERR! npm  v2.6.1

npm ERR! Invalid package.json
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\npm-debug.log
```

D:\npm-debug.log is:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   'C:\\Users\\Lucek\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'info' ]
2 info using npm@2.6.1
3 info using node@v0.12.0
4 verbose stack Error: Invalid package.json
4 verbose stack     at C:\Users\Lucek\AppData\Roaming\npm\node_modules\npm\lib\view.js:79:30
4 verbose stack     at C:\Users\Lucek\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:51:40
4 verbose stack     at C:\Users\Lucek\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:97:49
4 verbose stack     at evalmachine.<anonymous>:265:20
4 verbose stack     at OpenReq.Req.done (C:\Users\Lucek\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:141:5)
4 verbose stack     at OpenReq.done (C:\Users\Lucek\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:61:22)
4 verbose stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:99:15)
5 verbose cwd C:\Windows\System32
6 error Windows_NT 6.3.9600
7 error argv "node" "C:\\Users\\Lucek\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "info"
8 error node v0.12.0
9 error npm  v2.6.1
10 error Invalid package.json
11 error If you need help, you may report this error at:
11 error     <http://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

I'm still unable to work with npm to learn all other web-development stuff. Help me, please!

**Comment by othiym23** [comment]
@lucenty In that example, it looks like you're running `npm info` in `D:\`. Unless there's a `package.json` files in `D:\`, you're going to get that error message because it's trying to get info on the default package (that is, the package in the current working directory). Try running `npm info npm` to see what kind of output `npm info` normally gives.

**Comment by baconisthecure** [comment]
I'm getting the same problem on Windows 7.  I have tried doing npm init in a new directory create a clean project then install Express or other package.    Same error/hanging.

**Comment by thetoast** [comment]
I recently ran into this exact same issue, so I decided to `wget` a package and attempt to install the tarball directly with `npm`.  When I did so, I saw an additional verbose log message saying something to the effect of `unpacking to C:\users\{myuser}\AppData\Temp;C:\Python27\{package name}` which seemed awful strange.

I checked my environment variables, and sure enough, my `TEMP` had somehow gotten `;C:\Python27` appended to the end of it.  I corrected `TEMP` to be just the normal temp folder again, and then `npm install` started working again.  Perhaps this is similar to what folks here are reporting?

What I find interesting is that the verbose message about unpacking and referencing the temp folder wasn't logged in the normal `npm install` case.  At any rate, I do remember that just before this happened I had attempted to install a package with a native component through npm.  I'm wondering if the build script for that was monkeying with my environment variables somehow...

**Comment by lucenty** [comment]
@thetoast You are great! My TEMP was also composed by two paths separated by semicolon. I fixed it and now I am able to install packages. Thanks!

**Comment by thetoast** [comment]
@lucenty Glad it worked!  I was beating my head against the keyboard for a good couple hours last night trying to figure out what happened.  I had uninstalled node, reinstalled node, uninstalled and installed io.js, sacrificed one of my cats... all to no avail until I tried the manual install as described above.

**Comment by lucenty** [comment]
Your determination can save the world! (but not cats ;))
What now? Should I close the issue? Or maybe some code contributor could provide a fix to npm - maybe npm should warn user if the TEMP variable is incorrect. This is the first issue I opened, so I don't know how it works.

**Comment by ethanclevenger91** [comment]
Also had this issue with an incorrect TEMP variable. It was `%USERPROFILE%\AppData\Local\Temp`, which seemed fine. I deleted it and recreated it, which seems to have resolved all issues.

**Comment by adisak1618** [comment]
I already fix TEMP variable, but it still have not resolved issue for me TT

**Comment by lubaba17** [comment]
Yes, I have also fixed the TEMP variable, but npm install is still not working.

**Comment by gabrielfgularte** [comment]
Same issue here. I'm on Ubuntu 15.04 and I've tried these steps:

curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
sudo apt-get install -y nodejs
// Sometimes it stops here

sudo npm install -g yo gulp bower
// Sometimes it stops here
sudo npm install -g generator-gulp-angular
// Sometimes it stops here

**Comment by Shankar016** [comment]
fixing TEMP Variable fixed the issue for me , Thank u

**Comment by rahulbussa** [comment]
@thetoast it worked .Thanks a lot
:+1:

**Comment by anitamv05** [comment]
Is this ok? (yes) .. while running _npm init_ in my command line , at the end of the processit asks 'Is this ok? (yes)' and I hit enter , it goes to the next line and the process never ends.. if I press control +c ,the process aborts.. what should I do?

**Comment by legodude17** [comment]
@anitamv05, that has already been reported in #14257.

**Comment by gonejack** [comment]
it is the temp variable, thank you all.
