### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by hxshandle** [npm/npm#7497]
Hi I met a problem with npm under iojs. following is the log. I worked under a proxy server, and I'm sure the proxy server setting is correct.
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\iojs\\\\node.exe',
1 verbose cli   'C:\\iojs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'koa' ]
2 info using npm@2.6.0
3 info using node@v1.4.1
4 verbose node symlink C:\iojs\\node.exe
5 silly cache add args [ 'koa', null ]
6 verbose cache add spec koa
7 silly cache add parsed spec { raw: 'koa',
7 silly cache add   scope: null,
7 silly cache add   name: 'koa',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed koa@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'koa', range: '*', hasData: false }
12 silly mapToRegistry name koa
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/koa
16 verbose addNameRange registry:https://registry.npmjs.org/koa not in flight; fetching
17 verbose request uri https://registry.npmjs.org/koa
18 verbose request no auth needed
19 info attempt registry request try #1 at 14:52:57
20 verbose request id 3f8957a6545ccb7f
21 http request GET https://registry.npmjs.org/koa
22 verbose stack TypeError: Cannot read property 'setServername' of null
22 verbose stack     at TLSSocket.setServername (_tls_wrap.js:507:15)
22 verbose stack     at Object.exports.connect (_tls_wrap.js:895:12)
22 verbose stack     at C:\iojs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:195:28
22 verbose stack     at ClientRequest.onConnect (C:\iojs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:154:7)
22 verbose stack     at ClientRequest.g (events.js:257:16)
22 verbose stack     at emitThree (events.js:97:13)
22 verbose stack     at ClientRequest.emit (events.js:172:7)
22 verbose stack     at Socket.socketOnData (_http_client.js:325:11)
22 verbose stack     at emitOne (events.js:77:13)
22 verbose stack     at Socket.emit (events.js:166:7)
23 verbose cwd C:\temp
24 error Windows_NT 6.1.7601
25 error argv "C:\\iojs\\\\node.exe" "C:\\iojs\\node_modules\\npm\\bin\\npm-cli.js" "install" "koa"
26 error node v1.4.1
27 error npm  v2.6.0
28 error Cannot read property 'setServername' of null
29 error If you need help, you may report this error at:
29 error     <http://github.com/npm/npm/issues>
30 verbose exit [ 1, true ]
```

**Comment by smikes** [comment]
This is a bug in `io.js@1.4.1` -- https stopped working on Windows only -- which is now fixed in the codebase and will come out in the next release, 1.4.2.  In the meantime you can either switch to `http` access to the registry or use io.js@1.4.0

Ref: https://github.com/iojs/io.js/issues/988

**Comment by othiym23** [comment]
Oh goddddd, really? Thanks for digging this up, @smikes, I wasn't aware of this. :imp:

**Comment by mzgol** [comment]
> or use io.js@1.4.0

@smikes 1.3.0, not 1.4.0. The latter was borked & never got released.

**Comment by rvagg** [comment]
Is it just `npm install` that stopped working? if that works on a test build of 1.4.2 would you consider this "fixed"? Note that we still have some outstanding issues on Windows to be fixed but the main one will be addressed in 1.4.2, I just don't want to push it out and find that the other issues are more important than they appear to be.

**Comment by othiym23** [comment]
@rvagg If you can run `npm install koa` while pointing at the default registry (`https://registry.npmjs.org`), then that's probably good enough to confirm that 1.4.2 is fixed for npm.

Unfortunately, the npm test suite is still kind of a dog's breakfast on Windows – fixing it is [on the roadmap](https://github.com/npm/npm/wiki/rewriting-npm's-tests:-a-plan-maybe). Sorry :disappointed:.

**Comment by rvagg** [comment]
s'ok @othiym23, I'm not expecting the world from npm, just searching for a more advanced use-case than the 20-liner we have to work on in iojs/io.js. Testing now.

**Comment by smikes** [comment]
@mzgol Thanks for catching that -- I was just guessing. I should have checked.

**Comment by rvagg** [comment]
![screen shot 2015-02-28 at 3 01 28 pm](https://cloud.githubusercontent.com/assets/495647/6428121/c92e3aaa-bf5a-11e4-8611-8019af4258e2.png)

With 1.4.2 RC: https://iojs.org/download/nightly/v1.4.2-nightly201502281ab7e80838/

**Comment by rvagg** [comment]
`npm i hapi` is fine too, going to release this

**Comment by rvagg** [comment]
1.4.2 is out, but probably not the end of this story, expect a 1.4.3 soon for some unrelated problems

**Comment by smikes** [comment]
@hxshandle , can you please try updating your `io.js` to 1.4.2 and let us know if this is now working for you?  Thanks!

**Comment by othiym23** [comment]
@smikes, I'm waiting for 1.4.3 before issuing the all-clear. Also, I'll probably jump onto Windows and do some testing of my own.

**Comment by hxshandle** [comment]
@smikes I tested 1.4.2 it works fine now. thanks.
![npm-install-issue-for-iojs1 4 1](https://cloud.githubusercontent.com/assets/1249471/6435619/c6547e6a-c0dc-11e4-9257-06014b200843.PNG)

**Comment by othiym23** [comment]
Closing as resolved. I'll say something more publicly once 1.4.3 is released, but for now, for those stumbling across this issue via Google: `io.js@1.4.1` is a bad release on Windows, at least for use with HTTPS npm registries. Please upgrade to at least `io.js@1.4.2`. Thank you! And especial thanks to @rvagg for sacrificing a chunk of his weekend to get this dealt with. You're a champ, Rod.
