### ISSUE TITLE
npm does not work on IPv6

### ISSUE THREAD

**Issue by hobarrera** [npm/npm#8731]
On an IPv6 network with NAT64, npm fails to install any packages. I need to set up some complicated tunnel, or walk over to starbucks to use npm:

```
npm ERR! Linux 4.0.5-1-ARCH
npm ERR! argv "node" "/usr/bin/npm" "--userconfig=/tmp/pacaurtmp-hugo/atom-editor/src/atom-1.0.0/build/.npmrc" "install" "--loglevel" "error"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.2
npm ERR! code ENETUNREACH
npm ERR! errno ENETUNREACH
npm ERR! syscall connect

npm ERR! connect ENETUNREACH
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/pacaurtmp-hugo/atom-editor/src/atom-1.0.0/build/npm-debug.log
```

npm-debu.log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   '--userconfig=/tmp/pacaurtmp-hugo/atom-editor/src/atom-1.0.0/build/.npmrc',
1 verbose cli   'install',
1 verbose cli   '--loglevel',
1 verbose cli   'error' ]
2 info using npm@2.11.2
3 info using node@v0.12.4
4 verbose config Skipping project config: /tmp/pacaurtmp-hugo/atom-editor/src/atom-1.0.0/build/.npmrc. (matches userconfig)
5 verbose readDependencies loading dependencies from /tmp/pacaurtmp-hugo/atom-editor/src/atom-1.0.0/build/package.json
6 warn package.json atom-build@ No license field.
7 verbose install where, deps [ '/tmp/pacaurtmp-hugo/atom-editor/src/atom-1.0.0/build',
7 verbose install   [ 'asar',
7 verbose install     'async',
7 verbose install     'donna',
7 verbose install     'formidable',
7 verbose install     'fs-plus',
7 verbose install     'github-releases',
7 verbose install     'grunt',
7 verbose install     'grunt-atom-shell-installer',
7 verbose install     'grunt-cli',
7 verbose install     'grunt-coffeelint',
7 verbose install     'grunt-contrib-coffee',
7 verbose install     'grunt-contrib-csslint',
7 verbose install     'grunt-contrib-less',
7 verbose install     'grunt-cson',
7 verbose install     'grunt-download-atom-shell',
7 verbose install     'grunt-lesslint',
7 verbose install     'grunt-peg',
7 verbose install     'grunt-shell',
7 verbose install     'harmony-collections',
7 verbose install     'legal-eagle',
7 verbose install     'minidump',
7 verbose install     'npm',
7 verbose install     'rcedit',
7 verbose install     'request',
7 verbose install     'rimraf',
7 verbose install     'runas',
7 verbose install     'tello',
7 verbose install     'temp',
7 verbose install     'underscore-plus',
7 verbose install     'unzip',
7 verbose install     'vm-compatibility-layer',
7 verbose install     'webdriverio' ] ]
8 verbose install where, peers [ '/tmp/pacaurtmp-hugo/atom-editor/src/atom-1.0.0/build', [] ]
9 verbose installManyTop reading for lifecycle /tmp/pacaurtmp-hugo/atom-editor/src/atom-1.0.0/build/package.json
10 info preinstall atom-build@
11 verbose readDependencies loading dependencies from /tmp/pacaurtmp-hugo/atom-editor/src/atom-1.0.0/build/package.json
12 silly cache add args [ 'donna@1.0.10', null ]
13 verbose cache add spec donna@1.0.10
14 silly cache add parsed spec { raw: 'donna@1.0.10',
14 silly cache add   scope: null,
14 silly cache add   name: 'donna',
14 silly cache add   rawSpec: '1.0.10',
14 silly cache add   spec: '1.0.10',
14 silly cache add   type: 'version' }
15 silly addNamed donna@1.0.10
16 verbose addNamed "1.0.10" is a plain semver version for donna
17 silly mapToRegistry name donna
18 silly mapToRegistry using default registry
19 silly mapToRegistry registry https://registry.npmjs.org/
20 silly mapToRegistry uri https://registry.npmjs.org/donna
21 verbose addNameVersion registry:https://registry.npmjs.org/donna not in flight; fetching
22 silly cache add args [ 'formidable@~1.0.14', null ]
23 verbose cache add spec formidable@~1.0.14
24 silly cache add parsed spec { raw: 'formidable@~1.0.14',
24 silly cache add   scope: null,
24 silly cache add   name: 'formidable',
24 silly cache add   rawSpec: '~1.0.14',
24 silly cache add   spec: '>=1.0.14 <1.1.0',
24 silly cache add   type: 'range' }
25 silly addNamed formidable@>=1.0.14 <1.1.0
26 verbose addNamed ">=1.0.14 <1.1.0" is a valid semver range for formidable
27 silly addNameRange { name: 'formidable', range: '>=1.0.14 <1.1.0', hasData: false }
28 silly mapToRegistry name formidable
29 silly mapToRegistry using default registry
30 silly mapToRegistry registry https://registry.npmjs.org/
31 silly mapToRegistry uri https://registry.npmjs.org/formidable
32 verbose addNameRange registry:https://registry.npmjs.org/formidable not in flight; fetching
33 silly cache add args [ 'fs-plus@2.x', null ]
34 verbose cache add spec fs-plus@2.x
35 silly cache add parsed spec { raw: 'fs-plus@2.x',
35 silly cache add   scope: null,
35 silly cache add   name: 'fs-plus',
35 silly cache add   rawSpec: '2.x',
35 silly cache add   spec: '>=2.0.0 <3.0.0',
35 silly cache add   type: 'range' }
36 silly addNamed fs-plus@>=2.0.0 <3.0.0
37 verbose addNamed ">=2.0.0 <3.0.0" is a valid semver range for fs-plus
38 silly addNameRange { name: 'fs-plus', range: '>=2.0.0 <3.0.0', hasData: false }
39 silly mapToRegistry name fs-plus
40 silly mapToRegistry using default registry
41 silly mapToRegistry registry https://registry.npmjs.org/
42 silly mapToRegistry uri https://registry.npmjs.org/fs-plus
43 verbose addNameRange registry:https://registry.npmjs.org/fs-plus not in flight; fetching
44 silly cache add args [ 'github-releases@~0.2.0', null ]
45 verbose cache add spec github-releases@~0.2.0
46 silly cache add parsed spec { raw: 'github-releases@~0.2.0',
46 silly cache add   scope: null,
46 silly cache add   name: 'github-releases',
46 silly cache add   rawSpec: '~0.2.0',
46 silly cache add   spec: '>=0.2.0 <0.3.0',
46 silly cache add   type: 'range' }
47 silly addNamed github-releases@>=0.2.0 <0.3.0
48 verbose addNamed ">=0.2.0 <0.3.0" is a valid semver range for github-releases
49 silly addNameRange { name: 'github-releases',
49 silly addNameRange   range: '>=0.2.0 <0.3.0',
49 silly addNameRange   hasData: false }
50 silly mapToRegistry name github-releases
51 silly mapToRegistry using default registry
52 silly mapToRegistry registry https://registry.npmjs.org/
53 silly mapToRegistry uri https://registry.npmjs.org/github-releases
54 verbose addNameRange registry:https://registry.npmjs.org/github-releases not in flight; fetching
55 silly cache add args [ 'grunt@~0.4.1', null ]
56 verbose cache add spec grunt@~0.4.1
57 silly cache add parsed spec { raw: 'grunt@~0.4.1',
57 silly cache add   scope: null,
57 silly cache add   name: 'grunt',
57 silly cache add   rawSpec: '~0.4.1',
57 silly cache add   spec: '>=0.4.1 <0.5.0',
57 silly cache add   type: 'range' }
58 silly addNamed grunt@>=0.4.1 <0.5.0
59 verbose addNamed ">=0.4.1 <0.5.0" is a valid semver range for grunt
60 silly addNameRange { name: 'grunt', range: '>=0.4.1 <0.5.0', hasData: false }
61 silly mapToRegistry name grunt
62 silly mapToRegistry using default registry
63 silly mapToRegistry registry https://registry.npmjs.org/
64 silly mapToRegistry uri https://registry.npmjs.org/grunt
65 verbose addNameRange registry:https://registry.npmjs.org/grunt not in flight; fetching
66 silly cache add args [ 'grunt-atom-shell-installer@^0.29.0', null ]
67 verbose cache add spec grunt-atom-shell-installer@^0.29.0
68 silly cache add parsed spec { raw: 'grunt-atom-shell-installer@^0.29.0',
68 silly cache add   scope: null,
68 silly cache add   name: 'grunt-atom-shell-installer',
68 silly cache add   rawSpec: '^0.29.0',
68 silly cache add   spec: '>=0.29.0 <0.30.0',
68 silly cache add   type: 'range' }
69 silly addNamed grunt-atom-shell-installer@>=0.29.0 <0.30.0
70 verbose addNamed ">=0.29.0 <0.30.0" is a valid semver range for grunt-atom-shell-installer
71 silly addNameRange { name: 'grunt-atom-shell-installer',
71 silly addNameRange   range: '>=0.29.0 <0.30.0',
71 silly addNameRange   hasData: false }
72 silly mapToRegistry name grunt-atom-shell-installer
73 silly mapToRegistry using default registry
74 silly mapToRegistry registry https://registry.npmjs.org/
75 silly mapToRegistry uri https://registry.npmjs.org/grunt-atom-shell-installer
76 verbose addNameRange registry:https://registry.npmjs.org/grunt-atom-shell-installer not in flight; fetching
77 silly cache add args [ 'grunt-cli@~0.1.9', null ]
78 verbose cache add spec grunt-cli@~0.1.9
79 silly cache add parsed spec { raw: 'grunt-cli@~0.1.9',
79 silly cache add   scope: null,
79 silly cache add   name: 'grunt-cli',
79 silly cache add   rawSpec: '~0.1.9',
79 silly cache add   spec: '>=0.1.9 <0.2.0',
79 silly cache add   type: 'range' }
80 silly addNamed grunt-cli@>=0.1.9 <0.2.0
81 verbose addNamed ">=0.1.9 <0.2.0" is a valid semver range for grunt-cli
82 silly addNameRange { name: 'grunt-cli', range: '>=0.1.9 <0.2.0', hasData: false }
83 silly mapToRegistry name grunt-cli
84 silly mapToRegistry using default registry
85 silly mapToRegistry registry https://registry.npmjs.org/
86 silly mapToRegistry uri https://registry.npmjs.org/grunt-cli
87 verbose addNameRange registry:https://registry.npmjs.org/grunt-cli not in flight; fetching
88 silly cache add args [ 'grunt-coffeelint@git+https://github.com/atom/grunt-coffeelint.git#cfb99aa99811d52687969532bd5a98011ed95bfe',
88 silly cache add   null ]
89 verbose cache add spec grunt-coffeelint@git+https://github.com/atom/grunt-coffeelint.git#cfb99aa99811d52687969532bd5a98011ed95bfe
90 silly cache add args [ 'grunt-contrib-coffee@~0.12.0', null ]
91 verbose cache add spec grunt-contrib-coffee@~0.12.0
92 silly cache add parsed spec { raw: 'grunt-contrib-coffee@~0.12.0',
92 silly cache add   scope: null,
92 silly cache add   name: 'grunt-contrib-coffee',
92 silly cache add   rawSpec: '~0.12.0',
92 silly cache add   spec: '>=0.12.0 <0.13.0',
92 silly cache add   type: 'range' }
93 silly addNamed grunt-contrib-coffee@>=0.12.0 <0.13.0
94 verbose addNamed ">=0.12.0 <0.13.0" is a valid semver range for grunt-contrib-coffee
95 silly addNameRange { name: 'grunt-contrib-coffee',
95 silly addNameRange   range: '>=0.12.0 <0.13.0',
95 silly addNameRange   hasData: false }
96 silly mapToRegistry name grunt-contrib-coffee
97 silly mapToRegistry using default registry
98 silly mapToRegistry registry https://registry.npmjs.org/
99 silly mapToRegistry uri https://registry.npmjs.org/grunt-contrib-coffee
100 verbose addNameRange registry:https://registry.npmjs.org/grunt-contrib-coffee not in flight; fetching
101 silly cache add args [ 'grunt-contrib-csslint@~0.2.0', null ]
102 verbose cache add spec grunt-contrib-csslint@~0.2.0
103 silly cache add parsed spec { raw: 'grunt-contrib-csslint@~0.2.0',
103 silly cache add   scope: null,
103 silly cache add   name: 'grunt-contrib-csslint',
103 silly cache add   rawSpec: '~0.2.0',
103 silly cache add   spec: '>=0.2.0 <0.3.0',
103 silly cache add   type: 'range' }
104 silly addNamed grunt-contrib-csslint@>=0.2.0 <0.3.0
105 verbose addNamed ">=0.2.0 <0.3.0" is a valid semver range for grunt-contrib-csslint
106 silly addNameRange { name: 'grunt-contrib-csslint',
106 silly addNameRange   range: '>=0.2.0 <0.3.0',
106 silly addNameRange   hasData: false }
107 silly mapToRegistry name grunt-contrib-csslint
108 silly mapToRegistry using default registry
109 silly mapToRegistry registry https://registry.npmjs.org/
110 silly mapToRegistry uri https://registry.npmjs.org/grunt-contrib-csslint
111 verbose addNameRange registry:https://registry.npmjs.org/grunt-contrib-csslint not in flight; fetching
112 silly cache add args [ 'grunt-contrib-less@~0.8.0', null ]
113 verbose cache add spec grunt-contrib-less@~0.8.0
114 silly cache add parsed spec { raw: 'grunt-contrib-less@~0.8.0',
114 silly cache add   scope: null,
114 silly cache add   name: 'grunt-contrib-less',
114 silly cache add   rawSpec: '~0.8.0',
114 silly cache add   spec: '>=0.8.0 <0.9.0',
114 silly cache add   type: 'range' }
115 silly addNamed grunt-contrib-less@>=0.8.0 <0.9.0
116 verbose addNamed ">=0.8.0 <0.9.0" is a valid semver range for grunt-contrib-less
117 silly addNameRange { name: 'grunt-contrib-less',
117 silly addNameRange   range: '>=0.8.0 <0.9.0',
117 silly addNameRange   hasData: false }
118 silly mapToRegistry name grunt-contrib-less
119 silly mapToRegistry using default registry
120 silly mapToRegistry registry https://registry.npmjs.org/
121 silly mapToRegistry uri https://registry.npmjs.org/grunt-contrib-less
122 verbose addNameRange registry:https://registry.npmjs.org/grunt-contrib-less not in flight; fetching
123 silly cache add args [ 'grunt-cson@0.14.0', null ]
124 verbose cache add spec grunt-cson@0.14.0
125 silly cache add parsed spec { raw: 'grunt-cson@0.14.0',
125 silly cache add   scope: null,
125 silly cache add   name: 'grunt-cson',
125 silly cache add   rawSpec: '0.14.0',
125 silly cache add   spec: '0.14.0',
125 silly cache add   type: 'version' }
126 silly addNamed grunt-cson@0.14.0
127 verbose addNamed "0.14.0" is a plain semver version for grunt-cson
128 silly mapToRegistry name grunt-cson
129 silly mapToRegistry using default registry
130 silly mapToRegistry registry https://registry.npmjs.org/
131 silly mapToRegistry uri https://registry.npmjs.org/grunt-cson
132 verbose addNameVersion registry:https://registry.npmjs.org/grunt-cson not in flight; fetching
133 silly cache add args [ 'grunt-download-atom-shell@~0.14.0', null ]
134 verbose cache add spec grunt-download-atom-shell@~0.14.0
135 silly cache add parsed spec { raw: 'grunt-download-atom-shell@~0.14.0',
135 silly cache add   scope: null,
135 silly cache add   name: 'grunt-download-atom-shell',
135 silly cache add   rawSpec: '~0.14.0',
135 silly cache add   spec: '>=0.14.0 <0.15.0',
135 silly cache add   type: 'range' }
136 silly addNamed grunt-download-atom-shell@>=0.14.0 <0.15.0
137 verbose addNamed ">=0.14.0 <0.15.0" is a valid semver range for grunt-download-atom-shell
138 silly addNameRange { name: 'grunt-download-atom-shell',
138 silly addNameRange   range: '>=0.14.0 <0.15.0',
138 silly addNameRange   hasData: false }
139 silly mapToRegistry name grunt-download-atom-shell
140 silly mapToRegistry using default registry
141 silly mapToRegistry registry https://registry.npmjs.org/
142 silly mapToRegistry uri https://registry.npmjs.org/grunt-download-atom-shell
143 verbose addNameRange registry:https://registry.npmjs.org/grunt-download-atom-shell not in flight; fetching
144 silly cache add args [ 'grunt-lesslint@0.17.0', null ]
145 verbose cache add spec grunt-lesslint@0.17.0
146 silly cache add parsed spec { raw: 'grunt-lesslint@0.17.0',
146 silly cache add   scope: null,
146 silly cache add   name: 'grunt-lesslint',
146 silly cache add   rawSpec: '0.17.0',
146 silly cache add   spec: '0.17.0',
146 silly cache add   type: 'version' }
147 silly addNamed grunt-lesslint@0.17.0
148 verbose addNamed "0.17.0" is a plain semver version for grunt-lesslint
149 silly mapToRegistry name grunt-lesslint
150 silly mapToRegistry using default registry
151 silly mapToRegistry registry https://registry.npmjs.org/
152 silly mapToRegistry uri https://registry.npmjs.org/grunt-lesslint
153 verbose addNameVersion registry:https://registry.npmjs.org/grunt-lesslint not in flight; fetching
154 silly cache add args [ 'grunt-peg@~1.1.0', null ]
155 verbose cache add spec grunt-peg@~1.1.0
156 silly cache add parsed spec { raw: 'grunt-peg@~1.1.0',
156 silly cache add   scope: null,
156 silly cache add   name: 'grunt-peg',
156 silly cache add   rawSpec: '~1.1.0',
156 silly cache add   spec: '>=1.1.0 <1.2.0',
156 silly cache add   type: 'range' }
157 silly addNamed grunt-peg@>=1.1.0 <1.2.0
158 verbose addNamed ">=1.1.0 <1.2.0" is a valid semver range for grunt-peg
159 silly addNameRange { name: 'grunt-peg', range: '>=1.1.0 <1.2.0', hasData: false }
160 silly mapToRegistry name grunt-peg
161 silly mapToRegistry using default registry
162 silly mapToRegistry registry https://registry.npmjs.org/
163 silly mapToRegistry uri https://registry.npmjs.org/grunt-peg
164 verbose addNameRange registry:https://registry.npmjs.org/grunt-peg not in flight; fetching
165 silly cache add args [ 'grunt-shell@~0.3.1', null ]
166 verbose cache add spec grunt-shell@~0.3.1
167 silly cache add parsed spec { raw: 'grunt-shell@~0.3.1',
167 silly cache add   scope: null,
167 silly cache add   name: 'grunt-shell',
167 silly cache add   rawSpec: '~0.3.1',
167 silly cache add   spec: '>=0.3.1 <0.4.0',
167 silly cache add   type: 'range' }
168 silly addNamed grunt-shell@>=0.3.1 <0.4.0
169 verbose addNamed ">=0.3.1 <0.4.0" is a valid semver range for grunt-shell
170 silly addNameRange { name: 'grunt-shell', range: '>=0.3.1 <0.4.0', hasData: false }
171 silly mapToRegistry name grunt-shell
172 silly mapToRegistry using default registry
173 silly mapToRegistry registry https://registry.npmjs.org/
174 silly mapToRegistry uri https://registry.npmjs.org/grunt-shell
175 verbose addNameRange registry:https://registry.npmjs.org/grunt-shell not in flight; fetching
176 silly cache add args [ 'harmony-collections@~0.3.8', null ]
177 verbose cache add spec harmony-collections@~0.3.8
178 silly cache add parsed spec { raw: 'harmony-collections@~0.3.8',
178 silly cache add   scope: null,
178 silly cache add   name: 'harmony-collections',
178 silly cache add   rawSpec: '~0.3.8',
178 silly cache add   spec: '>=0.3.8 <0.4.0',
178 silly cache add   type: 'range' }
179 silly addNamed harmony-collections@>=0.3.8 <0.4.0
180 verbose addNamed ">=0.3.8 <0.4.0" is a valid semver range for harmony-collections
181 silly addNameRange { name: 'harmony-collections',
181 silly addNameRange   range: '>=0.3.8 <0.4.0',
181 silly addNameRange   hasData: false }
182 silly mapToRegistry name harmony-collections
183 silly mapToRegistry using default registry
184 silly mapToRegistry registry https://registry.npmjs.org/
185 silly mapToRegistry uri https://registry.npmjs.org/harmony-collections
186 verbose addNameRange registry:https://registry.npmjs.org/harmony-collections not in flight; fetching
187 silly cache add args [ 'legal-eagle@~0.10.0', null ]
188 verbose cache add spec legal-eagle@~0.10.0
189 silly cache add parsed spec { raw: 'legal-eagle@~0.10.0',
189 silly cache add   scope: null,
189 silly cache add   name: 'legal-eagle',
189 silly cache add   rawSpec: '~0.10.0',
189 silly cache add   spec: '>=0.10.0 <0.11.0',
189 silly cache add   type: 'range' }
190 silly addNamed legal-eagle@>=0.10.0 <0.11.0
191 verbose addNamed ">=0.10.0 <0.11.0" is a valid semver range for legal-eagle
192 silly addNameRange { name: 'legal-eagle',
192 silly addNameRange   range: '>=0.10.0 <0.11.0',
192 silly addNameRange   hasData: false }
193 silly mapToRegistry name legal-eagle
194 silly mapToRegistry using default registry
195 silly mapToRegistry registry https://registry.npmjs.org/
196 silly mapToRegistry uri https://registry.npmjs.org/legal-eagle
197 verbose addNameRange registry:https://registry.npmjs.org/legal-eagle not in flight; fetching
198 silly cache add args [ 'minidump@~0.8', null ]
199 verbose cache add spec minidump@~0.8
200 silly cache add parsed spec { raw: 'minidump@~0.8',
200 silly cache add   scope: null,
200 silly cache add   name: 'minidump',
200 silly cache add   rawSpec: '~0.8',
200 silly cache add   spec: '>=0.8.0 <0.9.0',
200 silly cache add   type: 'range' }
201 silly addNamed minidump@>=0.8.0 <0.9.0
202 verbose addNamed ">=0.8.0 <0.9.0" is a valid semver range for minidump
203 silly addNameRange { name: 'minidump', range: '>=0.8.0 <0.9.0', hasData: false }
204 silly mapToRegistry name minidump
205 silly mapToRegistry using default registry
206 silly mapToRegistry registry https://registry.npmjs.org/
207 silly mapToRegistry uri https://registry.npmjs.org/minidump
208 verbose addNameRange registry:https://registry.npmjs.org/minidump not in flight; fetching
209 silly cache add args [ 'npm@2.5.1', null ]
210 verbose cache add spec npm@2.5.1
211 silly cache add parsed spec { raw: 'npm@2.5.1',
211 silly cache add   scope: null,
211 silly cache add   name: 'npm',
211 silly cache add   rawSpec: '2.5.1',
211 silly cache add   spec: '2.5.1',
211 silly cache add   type: 'version' }
212 silly addNamed npm@2.5.1
213 verbose addNamed "2.5.1" is a plain semver version for npm
214 silly mapToRegistry name npm
215 silly mapToRegistry using default registry
216 silly mapToRegistry registry https://registry.npmjs.org/
217 silly mapToRegistry uri https://registry.npmjs.org/npm
218 verbose addNameVersion registry:https://registry.npmjs.org/npm not in flight; fetching
219 silly cache add args [ 'rcedit@~0.3.0', null ]
220 verbose cache add spec rcedit@~0.3.0
221 silly cache add parsed spec { raw: 'rcedit@~0.3.0',
221 silly cache add   scope: null,
221 silly cache add   name: 'rcedit',
221 silly cache add   rawSpec: '~0.3.0',
221 silly cache add   spec: '>=0.3.0 <0.4.0',
221 silly cache add   type: 'range' }
222 silly addNamed rcedit@>=0.3.0 <0.4.0
223 verbose addNamed ">=0.3.0 <0.4.0" is a valid semver range for rcedit
224 silly addNameRange { name: 'rcedit', range: '>=0.3.0 <0.4.0', hasData: false }
225 silly mapToRegistry name rcedit
226 silly mapToRegistry using default registry
227 silly mapToRegistry registry https://registry.npmjs.org/
228 silly mapToRegistry uri https://registry.npmjs.org/rcedit
229 verbose addNameRange registry:https://registry.npmjs.org/rcedit not in flight; fetching
230 silly cache add args [ 'request@~2.27.0', null ]
231 verbose cache add spec request@~2.27.0
232 silly cache add parsed spec { raw: 'request@~2.27.0',
232 silly cache add   scope: null,
232 silly cache add   name: 'request',
232 silly cache add   rawSpec: '~2.27.0',
232 silly cache add   spec: '>=2.27.0 <2.28.0',
232 silly cache add   type: 'range' }
233 silly addNamed request@>=2.27.0 <2.28.0
234 verbose addNamed ">=2.27.0 <2.28.0" is a valid semver range for request
235 silly addNameRange { name: 'request', range: '>=2.27.0 <2.28.0', hasData: false }
236 silly mapToRegistry name request
237 silly mapToRegistry using default registry
238 silly mapToRegistry registry https://registry.npmjs.org/
239 silly mapToRegistry uri https://registry.npmjs.org/request
240 verbose addNameRange registry:https://registry.npmjs.org/request not in flight; fetching
241 silly cache add args [ 'rimraf@~2.2.2', null ]
242 verbose cache add spec rimraf@~2.2.2
243 silly cache add parsed spec { raw: 'rimraf@~2.2.2',
243 silly cache add   scope: null,
243 silly cache add   name: 'rimraf',
243 silly cache add   rawSpec: '~2.2.2',
243 silly cache add   spec: '>=2.2.2 <2.3.0',
243 silly cache add   type: 'range' }
244 silly addNamed rimraf@>=2.2.2 <2.3.0
245 verbose addNamed ">=2.2.2 <2.3.0" is a valid semver range for rimraf
246 silly addNameRange { name: 'rimraf', range: '>=2.2.2 <2.3.0', hasData: false }
247 silly mapToRegistry name rimraf
248 silly mapToRegistry using default registry
249 silly mapToRegistry registry https://registry.npmjs.org/
250 silly mapToRegistry uri https://registry.npmjs.org/rimraf
251 verbose addNameRange registry:https://registry.npmjs.org/rimraf not in flight; fetching
252 silly cache add args [ 'runas@^2', null ]
253 verbose cache add spec runas@^2
254 silly cache add parsed spec { raw: 'runas@^2',
254 silly cache add   scope: null,
254 silly cache add   name: 'runas',
254 silly cache add   rawSpec: '^2',
254 silly cache add   spec: '>=2.0.0 <3.0.0',
254 silly cache add   type: 'range' }
255 silly addNamed runas@>=2.0.0 <3.0.0
256 verbose addNamed ">=2.0.0 <3.0.0" is a valid semver range for runas
257 silly addNameRange { name: 'runas', range: '>=2.0.0 <3.0.0', hasData: false }
258 silly mapToRegistry name runas
259 silly mapToRegistry using default registry
260 silly mapToRegistry registry https://registry.npmjs.org/
261 silly mapToRegistry uri https://registry.npmjs.org/runas
262 verbose addNameRange registry:https://registry.npmjs.org/runas not in flight; fetching
263 silly cache add args [ 'tello@1.0.5', null ]
264 verbose cache add spec tello@1.0.5
265 silly cache add parsed spec { raw: 'tello@1.0.5',
265 silly cache add   scope: null,
265 silly cache add   name: 'tello',
265 silly cache add   rawSpec: '1.0.5',
265 silly cache add   spec: '1.0.5',
265 silly cache add   type: 'version' }
266 silly addNamed tello@1.0.5
267 verbose addNamed "1.0.5" is a plain semver version for tello
268 silly mapToRegistry name tello
269 silly mapToRegistry using default registry
270 silly mapToRegistry registry https://registry.npmjs.org/
271 silly mapToRegistry uri https://registry.npmjs.org/tello
272 verbose addNameVersion registry:https://registry.npmjs.org/tello not in flight; fetching
273 silly cache add args [ 'temp@~0.8.1', null ]
274 verbose cache add spec temp@~0.8.1
275 silly cache add parsed spec { raw: 'temp@~0.8.1',
275 silly cache add   scope: null,
275 silly cache add   name: 'temp',
275 silly cache add   rawSpec: '~0.8.1',
275 silly cache add   spec: '>=0.8.1 <0.9.0',
275 silly cache add   type: 'range' }
276 silly addNamed temp@>=0.8.1 <0.9.0
277 verbose addNamed ">=0.8.1 <0.9.0" is a valid semver range for temp
278 silly addNameRange { name: 'temp', range: '>=0.8.1 <0.9.0', hasData: false }
279 silly mapToRegistry name temp
280 silly mapToRegistry using default registry
281 silly mapToRegistry registry https://registry.npmjs.org/
282 silly mapToRegistry uri https://registry.npmjs.org/temp
283 verbose addNameRange registry:https://registry.npmjs.org/temp not in flight; fetching
284 silly cache add args [ 'underscore-plus@1.x', null ]
285 verbose cache add spec underscore-plus@1.x
286 silly cache add parsed spec { raw: 'underscore-plus@1.x',
286 silly cache add   scope: null,
286 silly cache add   name: 'underscore-plus',
286 silly cache add   rawSpec: '1.x',
286 silly cache add   spec: '>=1.0.0 <2.0.0',
286 silly cache add   type: 'range' }
287 silly addNamed underscore-plus@>=1.0.0 <2.0.0
288 verbose addNamed ">=1.0.0 <2.0.0" is a valid semver range for underscore-plus
289 silly addNameRange { name: 'underscore-plus',
289 silly addNameRange   range: '>=1.0.0 <2.0.0',
289 silly addNameRange   hasData: false }
290 silly mapToRegistry name underscore-plus
291 silly mapToRegistry using default registry
292 silly mapToRegistry registry https://registry.npmjs.org/
293 silly mapToRegistry uri https://registry.npmjs.org/underscore-plus
294 verbose addNameRange registry:https://registry.npmjs.org/underscore-plus not in flight; fetching
295 silly cache add args [ 'unzip@~0.1.9', null ]
296 verbose cache add spec unzip@~0.1.9
297 silly cache add parsed spec { raw: 'unzip@~0.1.9',
297 silly cache add   scope: null,
297 silly cache add   name: 'unzip',
297 silly cache add   rawSpec: '~0.1.9',
297 silly cache add   spec: '>=0.1.9 <0.2.0',
297 silly cache add   type: 'range' }
298 silly addNamed unzip@>=0.1.9 <0.2.0
299 verbose addNamed ">=0.1.9 <0.2.0" is a valid semver range for unzip
300 silly addNameRange { name: 'unzip', range: '>=0.1.9 <0.2.0', hasData: false }
301 silly mapToRegistry name unzip
302 silly mapToRegistry using default registry
303 silly mapToRegistry registry https://registry.npmjs.org/
304 silly mapToRegistry uri https://registry.npmjs.org/unzip
305 verbose addNameRange registry:https://registry.npmjs.org/unzip not in flight; fetching
306 silly cache add args [ 'vm-compatibility-layer@~0.1.0', null ]
307 verbose cache add spec vm-compatibility-layer@~0.1.0
308 silly cache add parsed spec { raw: 'vm-compatibility-layer@~0.1.0',
308 silly cache add   scope: null,
308 silly cache add   name: 'vm-compatibility-layer',
308 silly cache add   rawSpec: '~0.1.0',
308 silly cache add   spec: '>=0.1.0 <0.2.0',
308 silly cache add   type: 'range' }
309 silly addNamed vm-compatibility-layer@>=0.1.0 <0.2.0
310 verbose addNamed ">=0.1.0 <0.2.0" is a valid semver range for vm-compatibility-layer
311 silly addNameRange { name: 'vm-compatibility-layer',
311 silly addNameRange   range: '>=0.1.0 <0.2.0',
311 silly addNameRange   hasData: false }
312 silly mapToRegistry name vm-compatibility-layer
313 silly mapToRegistry using default registry
314 silly mapToRegistry registry https://registry.npmjs.org/
315 silly mapToRegistry uri https://registry.npmjs.org/vm-compatibility-layer
316 verbose addNameRange registry:https://registry.npmjs.org/vm-compatibility-layer not in flight; fetching
317 silly cache add args [ 'webdriverio@^2.4.5', null ]
318 verbose cache add spec webdriverio@^2.4.5
319 silly cache add parsed spec { raw: 'webdriverio@^2.4.5',
319 silly cache add   scope: null,
319 silly cache add   name: 'webdriverio',
319 silly cache add   rawSpec: '^2.4.5',
319 silly cache add   spec: '>=2.4.5 <3.0.0',
319 silly cache add   type: 'range' }
320 silly addNamed webdriverio@>=2.4.5 <3.0.0
321 verbose addNamed ">=2.4.5 <3.0.0" is a valid semver range for webdriverio
322 silly addNameRange { name: 'webdriverio', range: '>=2.4.5 <3.0.0', hasData: false }
323 silly mapToRegistry name webdriverio
324 silly mapToRegistry using default registry
325 silly mapToRegistry registry https://registry.npmjs.org/
326 silly mapToRegistry uri https://registry.npmjs.org/webdriverio
327 verbose addNameRange registry:https://registry.npmjs.org/webdriverio not in flight; fetching
328 silly cache add args [ 'asar@^0.5.0', null ]
329 verbose cache add spec asar@^0.5.0
330 silly cache add parsed spec { raw: 'asar@^0.5.0',
330 silly cache add   scope: null,
330 silly cache add   name: 'asar',
330 silly cache add   rawSpec: '^0.5.0',
330 silly cache add   spec: '>=0.5.0 <0.6.0',
330 silly cache add   type: 'range' }
331 silly addNamed asar@>=0.5.0 <0.6.0
332 verbose addNamed ">=0.5.0 <0.6.0" is a valid semver range for asar
333 silly addNameRange { name: 'asar', range: '>=0.5.0 <0.6.0', hasData: false }
334 silly mapToRegistry name asar
335 silly mapToRegistry using default registry
336 silly mapToRegistry registry https://registry.npmjs.org/
337 silly mapToRegistry uri https://registry.npmjs.org/asar
338 verbose addNameRange registry:https://registry.npmjs.org/asar not in flight; fetching
339 silly cache add args [ 'async@~0.2.9', null ]
340 verbose cache add spec async@~0.2.9
341 silly cache add parsed spec { raw: 'async@~0.2.9',
341 silly cache add   scope: null,
341 silly cache add   name: 'async',
341 silly cache add   rawSpec: '~0.2.9',
341 silly cache add   spec: '>=0.2.9 <0.3.0',
341 silly cache add   type: 'range' }
342 silly addNamed async@>=0.2.9 <0.3.0
343 verbose addNamed ">=0.2.9 <0.3.0" is a valid semver range for async
344 silly addNameRange { name: 'async', range: '>=0.2.9 <0.3.0', hasData: false }
345 silly mapToRegistry name async
346 silly mapToRegistry using default registry
347 silly mapToRegistry registry https://registry.npmjs.org/
348 silly mapToRegistry uri https://registry.npmjs.org/async
349 verbose addNameRange registry:https://registry.npmjs.org/async not in flight; fetching
350 verbose request uri https://registry.npmjs.org/donna
351 verbose request no auth needed
352 info attempt registry request try #1 at 2:28:35 PM
353 verbose request id da43b2899e23d419
354 http request GET https://registry.npmjs.org/donna
355 verbose request uri https://registry.npmjs.org/formidable
356 verbose request no auth needed
357 info attempt registry request try #1 at 2:28:35 PM
358 http request GET https://registry.npmjs.org/formidable
359 verbose request uri https://registry.npmjs.org/fs-plus
360 verbose request no auth needed
361 info attempt registry request try #1 at 2:28:35 PM
362 http request GET https://registry.npmjs.org/fs-plus
363 verbose request uri https://registry.npmjs.org/github-releases
364 verbose request no auth needed
365 info attempt registry request try #1 at 2:28:35 PM
366 http request GET https://registry.npmjs.org/github-releases
367 verbose request uri https://registry.npmjs.org/grunt
368 verbose request no auth needed
369 info attempt registry request try #1 at 2:28:35 PM
370 http request GET https://registry.npmjs.org/grunt
371 verbose request uri https://registry.npmjs.org/grunt-atom-shell-installer
372 verbose request no auth needed
373 info attempt registry request try #1 at 2:28:35 PM
374 http request GET https://registry.npmjs.org/grunt-atom-shell-installer
375 verbose request uri https://registry.npmjs.org/grunt-cli
376 verbose request no auth needed
377 info attempt registry request try #1 at 2:28:35 PM
378 http request GET https://registry.npmjs.org/grunt-cli
379 silly cache add parsed spec { raw: 'grunt-coffeelint@git+https://github.com/atom/grunt-coffeelint.git#cfb99aa99811d52687969532bd5a98011ed95bfe',
379 silly cache add   scope: null,
379 silly cache add   name: 'grunt-coffeelint',
379 silly cache add   rawSpec: 'git+https://github.com/atom/grunt-coffeelint.git#cfb99aa99811d52687969532bd5a98011ed95bfe',
379 silly cache add   spec: 'git+https://github.com/atom/grunt-coffeelint.git#cfb99aa99811d52687969532bd5a98011ed95bfe',
379 silly cache add   type: 'hosted',
379 silly cache add   hosted:
379 silly cache add    { type: 'github',
379 silly cache add      ssh: 'git@github.com:atom/grunt-coffeelint.git#cfb99aa99811d52687969532bd5a98011ed95bfe',
379 silly cache add      sshUrl: 'git+ssh://git@github.com/atom/grunt-coffeelint.git#cfb99aa99811d52687969532bd5a98011ed95bfe',
379 silly cache add      httpsUrl: 'git+https://github.com/atom/grunt-coffeelint.git#cfb99aa99811d52687969532bd5a98011ed95bfe',
379 silly cache add      gitUrl: 'git://github.com/atom/grunt-coffeelint.git#cfb99aa99811d52687969532bd5a98011ed95bfe',
379 silly cache add      shortcut: 'github:atom/grunt-coffeelint#cfb99aa99811d52687969532bd5a98011ed95bfe',
379 silly cache add      directUrl: 'https://raw.githubusercontent.com/atom/grunt-coffeelint/cfb99aa99811d52687969532bd5a98011ed95bfe/package.json' } }
380 verbose addRemoteGit caching git+https://github.com/atom/grunt-coffeelint.git#cfb99aa99811d52687969532bd5a98011ed95bfe
381 verbose addRemoteGit git+https://github.com/atom/grunt-coffeelint.git#cfb99aa99811d52687969532bd5a98011ed95bfe is a repository hosted by github
382 silly tryClone cloning git+https://github.com/atom/grunt-coffeelint.git#cfb99aa99811d52687969532bd5a98011ed95bfe via git+https://github.com/atom/grunt-coffeelint.git#cfb99aa99811d52687969532bd5a98011ed95bfe
383 verbose tryClone https-github-com-atom-grunt-coffeelint-git-25e0e49f not in flight; caching
384 verbose request uri https://registry.npmjs.org/grunt-contrib-coffee
385 verbose request no auth needed
386 info attempt registry request try #1 at 2:28:35 PM
387 http request GET https://registry.npmjs.org/grunt-contrib-coffee
388 verbose request uri https://registry.npmjs.org/grunt-contrib-csslint
389 verbose request no auth needed
390 info attempt registry request try #1 at 2:28:35 PM
391 http request GET https://registry.npmjs.org/grunt-contrib-csslint
392 verbose request uri https://registry.npmjs.org/grunt-contrib-less
393 verbose request no auth needed
394 info attempt registry request try #1 at 2:28:35 PM
395 http request GET https://registry.npmjs.org/grunt-contrib-less
396 verbose request uri https://registry.npmjs.org/grunt-cson
397 verbose request no auth needed
398 info attempt registry request try #1 at 2:28:35 PM
399 http request GET https://registry.npmjs.org/grunt-cson
400 verbose request uri https://registry.npmjs.org/grunt-download-atom-shell
401 verbose request no auth needed
402 info attempt registry request try #1 at 2:28:35 PM
403 http request GET https://registry.npmjs.org/grunt-download-atom-shell
404 verbose request uri https://registry.npmjs.org/grunt-lesslint
405 verbose request no auth needed
406 info attempt registry request try #1 at 2:28:35 PM
407 http request GET https://registry.npmjs.org/grunt-lesslint
408 verbose request uri https://registry.npmjs.org/grunt-peg
409 verbose request no auth needed
410 info attempt registry request try #1 at 2:28:35 PM
411 http request GET https://registry.npmjs.org/grunt-peg
412 verbose request uri https://registry.npmjs.org/grunt-shell
413 verbose request no auth needed
414 info attempt registry request try #1 at 2:28:35 PM
415 http request GET https://registry.npmjs.org/grunt-shell
416 verbose request uri https://registry.npmjs.org/harmony-collections
417 verbose request no auth needed
418 info attempt registry request try #1 at 2:28:35 PM
419 http request GET https://registry.npmjs.org/harmony-collections
420 verbose request uri https://registry.npmjs.org/legal-eagle
421 verbose request no auth needed
422 info attempt registry request try #1 at 2:28:35 PM
423 http request GET https://registry.npmjs.org/legal-eagle
424 verbose request uri https://registry.npmjs.org/minidump
425 verbose request no auth needed
426 info attempt registry request try #1 at 2:28:35 PM
427 http request GET https://registry.npmjs.org/minidump
428 verbose request uri https://registry.npmjs.org/npm
429 verbose request no auth needed
430 info attempt registry request try #1 at 2:28:35 PM
431 http request GET https://registry.npmjs.org/npm
432 verbose request uri https://registry.npmjs.org/rcedit
433 verbose request no auth needed
434 info attempt registry request try #1 at 2:28:35 PM
435 http request GET https://registry.npmjs.org/rcedit
436 verbose request uri https://registry.npmjs.org/request
437 verbose request no auth needed
438 info attempt registry request try #1 at 2:28:35 PM
439 http request GET https://registry.npmjs.org/request
440 verbose request uri https://registry.npmjs.org/rimraf
441 verbose request no auth needed
442 info attempt registry request try #1 at 2:28:35 PM
443 http request GET https://registry.npmjs.org/rimraf
444 verbose request uri https://registry.npmjs.org/runas
445 verbose request no auth needed
446 info attempt registry request try #1 at 2:28:35 PM
447 http request GET https://registry.npmjs.org/runas
448 verbose request uri https://registry.npmjs.org/tello
449 verbose request no auth needed
450 info attempt registry request try #1 at 2:28:35 PM
451 http request GET https://registry.npmjs.org/tello
452 verbose request uri https://registry.npmjs.org/temp
453 verbose request no auth needed
454 info attempt registry request try #1 at 2:28:35 PM
455 http request GET https://registry.npmjs.org/temp
456 verbose request uri https://registry.npmjs.org/underscore-plus
457 verbose request no auth needed
458 info attempt registry request try #1 at 2:28:35 PM
459 http request GET https://registry.npmjs.org/underscore-plus
460 verbose request uri https://registry.npmjs.org/unzip
461 verbose request no auth needed
462 info attempt registry request try #1 at 2:28:35 PM
463 http request GET https://registry.npmjs.org/unzip
464 verbose request uri https://registry.npmjs.org/vm-compatibility-layer
465 verbose request no auth needed
466 info attempt registry request try #1 at 2:28:35 PM
467 http request GET https://registry.npmjs.org/vm-compatibility-layer
468 verbose request uri https://registry.npmjs.org/webdriverio
469 verbose request no auth needed
470 info attempt registry request try #1 at 2:28:35 PM
471 http request GET https://registry.npmjs.org/webdriverio
472 verbose request uri https://registry.npmjs.org/asar
473 verbose request no auth needed
474 info attempt registry request try #1 at 2:28:35 PM
475 http request GET https://registry.npmjs.org/asar
476 verbose request uri https://registry.npmjs.org/async
477 verbose request no auth needed
478 info attempt registry request try #1 at 2:28:35 PM
479 http request GET https://registry.npmjs.org/async
480 verbose getCacheStat cache creation not in flight; initializing
481 info retry will retry, error on last attempt: Error: connect ENETUNREACH
482 info retry will retry, error on last attempt: Error: connect ENETUNREACH
483 info retry will retry, error on last attempt: Error: connect ENETUNREACH
484 info retry will retry, error on last attempt: Error: connect ENETUNREACH
485 info retry will retry, error on last attempt: Error: connect ENETUNREACH
486 info retry will retry, error on last attempt: Error: connect ENETUNREACH
487 info retry will retry, error on last attempt: Error: connect ENETUNREACH
488 info retry will retry, error on last attempt: Error: connect ENETUNREACH
489 info retry will retry, error on last attempt: Error: connect ENETUNREACH
490 info retry will retry, error on last attempt: Error: connect ENETUNREACH
491 info retry will retry, error on last attempt: Error: connect ENETUNREACH
492 info retry will retry, error on last attempt: Error: connect ENETUNREACH
493 info retry will retry, error on last attempt: Error: connect ENETUNREACH
494 info retry will retry, error on last attempt: Error: connect ENETUNREACH
495 info retry will retry, error on last attempt: Error: connect ENETUNREACH
496 info retry will retry, error on last attempt: Error: connect ENETUNREACH
497 info retry will retry, error on last attempt: Error: connect ENETUNREACH
498 info retry will retry, error on last attempt: Error: connect ENETUNREACH
499 info retry will retry, error on last attempt: Error: connect ENETUNREACH
500 info retry will retry, error on last attempt: Error: connect ENETUNREACH
501 info retry will retry, error on last attempt: Error: connect ENETUNREACH
502 info retry will retry, error on last attempt: Error: connect ENETUNREACH
503 info retry will retry, error on last attempt: Error: connect ENETUNREACH
504 info retry will retry, error on last attempt: Error: connect ENETUNREACH
505 info retry will retry, error on last attempt: Error: connect ENETUNREACH
506 info retry will retry, error on last attempt: Error: connect ENETUNREACH
507 info retry will retry, error on last attempt: Error: connect ENETUNREACH
508 info retry will retry, error on last attempt: Error: connect ENETUNREACH
509 info git [ 'clone',
509 info git   '--template=/home/hugo/.atom/.npm/_git-remotes/_templates',
509 info git   '--mirror',
509 info git   'https://github.com/atom/grunt-coffeelint.git',
509 info git   '/home/hugo/.atom/.npm/_git-remotes/https-github-com-atom-grunt-coffeelint-git-25e0e49f' ]
510 info retry will retry, error on last attempt: Error: connect ENETUNREACH
511 info retry will retry, error on last attempt: Error: connect ENETUNREACH
512 info retry will retry, error on last attempt: Error: connect ENETUNREACH
513 info attempt registry request try #2 at 2:28:46 PM
514 http request GET https://registry.npmjs.org/donna
515 info attempt registry request try #2 at 2:28:46 PM
516 http request GET https://registry.npmjs.org/fs-plus
517 info attempt registry request try #2 at 2:28:46 PM
518 http request GET https://registry.npmjs.org/formidable
519 info attempt registry request try #2 at 2:28:46 PM
520 http request GET https://registry.npmjs.org/github-releases
521 info attempt registry request try #2 at 2:28:47 PM
522 http request GET https://registry.npmjs.org/grunt
523 info attempt registry request try #2 at 2:28:47 PM
524 http request GET https://registry.npmjs.org/grunt-atom-shell-installer
525 info retry will retry, error on last attempt: Error: connect ENETUNREACH
526 info attempt registry request try #2 at 2:28:47 PM
527 http request GET https://registry.npmjs.org/grunt-cli
528 info attempt registry request try #2 at 2:28:47 PM
529 http request GET https://registry.npmjs.org/grunt-contrib-coffee
530 info retry will retry, error on last attempt: Error: connect ENETUNREACH
531 info retry will retry, error on last attempt: Error: connect ENETUNREACH
532 info retry will retry, error on last attempt: Error: connect ENETUNREACH
533 verbose mirrorRemote git+https://github.com/atom/grunt-coffeelint.git#cfb99aa99811d52687969532bd5a98011ed95bfe git clone https://github.com/atom/grunt-coffeelint.git
534 info attempt registry request try #2 at 2:28:48 PM
535 http request GET https://registry.npmjs.org/grunt-contrib-csslint
536 info attempt registry request try #2 at 2:28:48 PM
537 http request GET https://registry.npmjs.org/grunt-contrib-less
538 info attempt registry request try #2 at 2:28:48 PM
539 http request GET https://registry.npmjs.org/grunt-cson
540 info attempt registry request try #2 at 2:28:48 PM
541 http request GET https://registry.npmjs.org/grunt-download-atom-shell
542 info retry will retry, error on last attempt: Error: connect ENETUNREACH
543 info retry will retry, error on last attempt: Error: connect ENETUNREACH
544 info retry will retry, error on last attempt: Error: connect ENETUNREACH
545 info retry will retry, error on last attempt: Error: connect ENETUNREACH
546 info attempt registry request try #2 at 2:28:49 PM
547 http request GET https://registry.npmjs.org/grunt-lesslint
548 info attempt registry request try #2 at 2:28:49 PM
549 http request GET https://registry.npmjs.org/grunt-peg
550 info attempt registry request try #2 at 2:28:49 PM
551 http request GET https://registry.npmjs.org/grunt-shell
552 info attempt registry request try #2 at 2:28:49 PM
553 http request GET https://registry.npmjs.org/harmony-collections
554 info retry will retry, error on last attempt: Error: connect ENETUNREACH
555 info retry will retry, error on last attempt: Error: connect ENETUNREACH
556 info retry will retry, error on last attempt: Error: connect ENETUNREACH
557 info retry will retry, error on last attempt: Error: connect ENETUNREACH
558 info attempt registry request try #2 at 2:28:50 PM
559 http request GET https://registry.npmjs.org/legal-eagle
560 info attempt registry request try #2 at 2:28:50 PM
561 http request GET https://registry.npmjs.org/minidump
562 info attempt registry request try #2 at 2:28:50 PM
563 http request GET https://registry.npmjs.org/npm
564 info attempt registry request try #2 at 2:28:50 PM
565 http request GET https://registry.npmjs.org/rcedit
566 info retry will retry, error on last attempt: Error: connect ENETUNREACH
567 info retry will retry, error on last attempt: Error: connect ENETUNREACH
568 info retry will retry, error on last attempt: Error: connect ENETUNREACH
569 info retry will retry, error on last attempt: Error: connect ENETUNREACH
570 info attempt registry request try #2 at 2:28:51 PM
571 http request GET https://registry.npmjs.org/request
572 info attempt registry request try #2 at 2:28:51 PM
573 http request GET https://registry.npmjs.org/rimraf
574 info attempt registry request try #2 at 2:28:51 PM
575 http request GET https://registry.npmjs.org/runas
576 info attempt registry request try #2 at 2:28:51 PM
577 http request GET https://registry.npmjs.org/tello
578 info retry will retry, error on last attempt: Error: connect ENETUNREACH
579 info retry will retry, error on last attempt: Error: connect ENETUNREACH
580 info retry will retry, error on last attempt: Error: connect ENETUNREACH
581 info retry will retry, error on last attempt: Error: connect ENETUNREACH
582 info attempt registry request try #2 at 2:28:52 PM
583 http request GET https://registry.npmjs.org/temp
584 info attempt registry request try #2 at 2:28:52 PM
585 http request GET https://registry.npmjs.org/underscore-plus
586 info attempt registry request try #2 at 2:28:52 PM
587 http request GET https://registry.npmjs.org/unzip
588 info attempt registry request try #2 at 2:28:52 PM
589 http request GET https://registry.npmjs.org/vm-compatibility-layer
590 info retry will retry, error on last attempt: Error: connect ENETUNREACH
591 info retry will retry, error on last attempt: Error: connect ENETUNREACH
592 info retry will retry, error on last attempt: Error: connect ENETUNREACH
593 info retry will retry, error on last attempt: Error: connect ENETUNREACH
594 info attempt registry request try #2 at 2:28:53 PM
595 http request GET https://registry.npmjs.org/webdriverio
596 info attempt registry request try #2 at 2:28:53 PM
597 http request GET https://registry.npmjs.org/asar
598 info attempt registry request try #2 at 2:28:53 PM
599 http request GET https://registry.npmjs.org/async
600 info retry will retry, error on last attempt: Error: connect ENETUNREACH
601 info retry will retry, error on last attempt: Error: connect ENETUNREACH
602 info retry will retry, error on last attempt: Error: connect ENETUNREACH
603 info retry will retry, error on last attempt: Error: connect ENETUNREACH
604 verbose setPermissions git+https://github.com/atom/grunt-coffeelint.git#cfb99aa99811d52687969532bd5a98011ed95bfe set permissions on /home/hugo/.atom/.npm/_git-remotes/https-github-com-atom-grunt-coffeelint-git-25e0e49f
605 verbose resolveHead git+https://github.com/atom/grunt-coffeelint.git#cfb99aa99811d52687969532bd5a98011ed95bfe original treeish: cfb99aa99811d52687969532bd5a98011ed95bfe
606 info git [ 'rev-list', '-n1', 'cfb99aa99811d52687969532bd5a98011ed95bfe' ]
607 silly resolveHead git+https://github.com/atom/grunt-coffeelint.git#cfb99aa99811d52687969532bd5a98011ed95bfe resolved treeish: cfb99aa99811d52687969532bd5a98011ed95bfe
608 verbose resolveHead git+https://github.com/atom/grunt-coffeelint.git#cfb99aa99811d52687969532bd5a98011ed95bfe resolved Git URL: git+https://github.com/atom/grunt-coffeelint.git#cfb99aa99811d52687969532bd5a98011ed95bfe
609 silly resolveHead Git working directory: /tmp/npm-7325-2cbbbca3/git-cache-2121a5eadcea/cfb99aa99811d52687969532bd5a98011ed95bfe
610 info git [ 'clone',
610 info git   '/home/hugo/.atom/.npm/_git-remotes/https-github-com-atom-grunt-coffeelint-git-25e0e49f',
610 info git   '/tmp/npm-7325-2cbbbca3/git-cache-2121a5eadcea/cfb99aa99811d52687969532bd5a98011ed95bfe' ]
611 verbose cloneResolved git+https://github.com/atom/grunt-coffeelint.git#cfb99aa99811d52687969532bd5a98011ed95bfe clone Cloning into '/tmp/npm-7325-2cbbbca3/git-cache-2121a5eadcea/cfb99aa99811d52687969532bd5a98011ed95bfe'...
611 verbose cloneResolved done.
612 info git [ 'checkout', 'cfb99aa99811d52687969532bd5a98011ed95bfe' ]
613 verbose checkoutTreeish git+https://github.com/atom/grunt-coffeelint.git#cfb99aa99811d52687969532bd5a98011ed95bfe checkout Note: checking out 'cfb99aa99811d52687969532bd5a98011ed95bfe'.
613 verbose checkoutTreeish
613 verbose checkoutTreeish You are in 'detached HEAD' state. You can look around, make experimental
613 verbose checkoutTreeish changes and commit them, and you can discard any commits you make in this
613 verbose checkoutTreeish state without impacting any branches by performing another checkout.
613 verbose checkoutTreeish
613 verbose checkoutTreeish If you want to create a new branch to retain commits you create, you may
613 verbose checkoutTreeish do so (now or later) by using -b with the checkout command again. Example:
613 verbose checkoutTreeish
613 verbose checkoutTreeish   git checkout -b <new-branch-name>
613 verbose checkoutTreeish
613 verbose checkoutTreeish HEAD is now at cfb99aa... Remove bad comma
614 verbose addLocalDirectory /home/hugo/.atom/.npm/grunt-coffeelint/0.0.13/package.tgz not in flight; packing
615 verbose tar pack [ '/home/hugo/.atom/.npm/grunt-coffeelint/0.0.13/package.tgz',
615 verbose tar pack   '/tmp/npm-7325-2cbbbca3/git-cache-2121a5eadcea/cfb99aa99811d52687969532bd5a98011ed95bfe' ]
616 verbose tarball /home/hugo/.atom/.npm/grunt-coffeelint/0.0.13/package.tgz
617 verbose folder /tmp/npm-7325-2cbbbca3/git-cache-2121a5eadcea/cfb99aa99811d52687969532bd5a98011ed95bfe
618 verbose addLocalTarball adding from inside cache /home/hugo/.atom/.npm/grunt-coffeelint/0.0.13/package.tgz
619 verbose addRemoteGit data._from: git+https://github.com/atom/grunt-coffeelint.git#cfb99aa99811d52687969532bd5a98011ed95bfe
620 verbose addRemoteGit data._resolved: git+https://github.com/atom/grunt-coffeelint.git#cfb99aa99811d52687969532bd5a98011ed95bfe
621 silly cache afterAdd grunt-coffeelint@0.0.13
622 verbose afterAdd /home/hugo/.atom/.npm/grunt-coffeelint/0.0.13/package/package.json not in flight; writing
623 verbose afterAdd /home/hugo/.atom/.npm/grunt-coffeelint/0.0.13/package/package.json written
624 info retry will retry, error on last attempt: Error: connect ENETUNREACH
625 info retry will retry, error on last attempt: Error: connect ENETUNREACH
626 info retry will retry, error on last attempt: Error: connect ENETUNREACH
627 info attempt registry request try #3 at 2:29:47 PM
628 http request GET https://registry.npmjs.org/donna
629 info attempt registry request try #3 at 2:29:47 PM
630 http request GET https://registry.npmjs.org/fs-plus
631 info attempt registry request try #3 at 2:29:47 PM
632 http request GET https://registry.npmjs.org/formidable
633 info attempt registry request try #3 at 2:29:47 PM
634 http request GET https://registry.npmjs.org/github-releases
635 info attempt registry request try #3 at 2:29:48 PM
636 http request GET https://registry.npmjs.org/grunt
637 info attempt registry request try #3 at 2:29:48 PM
638 http request GET https://registry.npmjs.org/grunt-atom-shell-installer
639 info attempt registry request try #3 at 2:29:48 PM
640 http request GET https://registry.npmjs.org/grunt-cli
641 info attempt registry request try #3 at 2:29:48 PM
642 http request GET https://registry.npmjs.org/grunt-contrib-coffee
643 info attempt registry request try #3 at 2:29:49 PM
644 http request GET https://registry.npmjs.org/grunt-contrib-csslint
645 info attempt registry request try #3 at 2:29:49 PM
646 http request GET https://registry.npmjs.org/grunt-contrib-less
647 info attempt registry request try #3 at 2:29:50 PM
648 http request GET https://registry.npmjs.org/grunt-cson
649 info attempt registry request try #3 at 2:29:50 PM
650 http request GET https://registry.npmjs.org/grunt-download-atom-shell
651 info attempt registry request try #3 at 2:29:50 PM
652 http request GET https://registry.npmjs.org/grunt-lesslint
653 info attempt registry request try #3 at 2:29:51 PM
654 http request GET https://registry.npmjs.org/grunt-peg
655 info attempt registry request try #3 at 2:29:51 PM
656 http request GET https://registry.npmjs.org/grunt-shell
657 info attempt registry request try #3 at 2:29:51 PM
658 http request GET https://registry.npmjs.org/harmony-collections
659 info attempt registry request try #3 at 2:29:52 PM
660 http request GET https://registry.npmjs.org/legal-eagle
661 info attempt registry request try #3 at 2:29:52 PM
662 http request GET https://registry.npmjs.org/minidump
663 info attempt registry request try #3 at 2:29:52 PM
664 http request GET https://registry.npmjs.org/npm
665 info attempt registry request try #3 at 2:29:52 PM
666 http request GET https://registry.npmjs.org/rcedit
667 info attempt registry request try #3 at 2:29:53 PM
668 http request GET https://registry.npmjs.org/request
669 info attempt registry request try #3 at 2:29:53 PM
670 http request GET https://registry.npmjs.org/rimraf
671 info attempt registry request try #3 at 2:29:53 PM
672 http request GET https://registry.npmjs.org/runas
673 info attempt registry request try #3 at 2:29:53 PM
674 http request GET https://registry.npmjs.org/tello
675 info attempt registry request try #3 at 2:29:54 PM
676 http request GET https://registry.npmjs.org/temp
677 info attempt registry request try #3 at 2:29:54 PM
678 http request GET https://registry.npmjs.org/underscore-plus
679 info attempt registry request try #3 at 2:29:54 PM
680 http request GET https://registry.npmjs.org/unzip
681 info attempt registry request try #3 at 2:29:54 PM
682 http request GET https://registry.npmjs.org/vm-compatibility-layer
683 info attempt registry request try #3 at 2:29:55 PM
684 http request GET https://registry.npmjs.org/webdriverio
685 info attempt registry request try #3 at 2:29:55 PM
686 http request GET https://registry.npmjs.org/asar
687 info attempt registry request try #3 at 2:29:56 PM
688 http request GET https://registry.npmjs.org/async
689 verbose stack Error: connect ENETUNREACH
689 verbose stack     at exports._errnoException (util.js:746:11)
689 verbose stack     at connect (net.js:842:19)
689 verbose stack     at net.js:955:9
689 verbose stack     at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:81:16)
689 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:99:10)
690 verbose cwd /tmp/pacaurtmp-hugo/atom-editor/src/atom-1.0.0/build
691 error Linux 4.0.5-1-ARCH
692 error argv "node" "/usr/bin/npm" "--userconfig=/tmp/pacaurtmp-hugo/atom-editor/src/atom-1.0.0/build/.npmrc" "install" "--loglevel" "error"
693 error node v0.12.4
694 error npm  v2.11.2
695 error code ENETUNREACH
696 error errno ENETUNREACH
697 error syscall connect
698 error connect ENETUNREACH
699 error If you need help, you may report this error at:
699 error     <https://github.com/npm/npm/issues>
700 verbose exit [ 1, true ]
```

Of course, it's not a network issue (I've seen this issue over a year now, IIRC):

```
$ curl -sI https://www.npmjs.com/ | grep HTTP
HTTP/1.1 200 OK
```

**Comment by cristobalpalmer** [comment]
This also affects us.

<pre>
$ ip addr |grep global
    inet6 2610:28:3090:1021::120/64 scope global 
$ dig -t AAAA +noall +answer www.npmjs.com
www.npmjs.com.          300     IN      CNAME   a.sni.fastly.net.
a.sni.fastly.net.       30      IN      AAAA    2610:28:3090:1021:ffff:0:17eb:2ea2
$ HEAD https://www.npmjs.com |grep ^200
200 OK
$ npm install -g grunt-cli
npm ERR! Error: connect ENETUNREACH
npm ERR!     at errnoException (net.js:904:11)
npm ERR!     at connect (net.js:766:19)
npm ERR!     at net.js:845:9
npm ERR!     at asyncCallback (dns.js:68:16)
npm ERR!     at Object.onanswer [as oncomplete] (dns.js:121:9)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "grunt-cli"
npm ERR! cwd /home/cmpalmer/scratch/ghost
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! syscall connect
npm ERR! code ENETUNREACH
npm ERR! errno ENETUNREACH
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/cmpalmer/scratch/ghost/npm-debug.log
npm ERR! not ok code 0
</pre>

Please let me know if the full debug log would actually be helpful.

**Comment by hobarrera** [comment]
Label `support` is wrong: this is a bug (a super-critical one, IMHO).

**Comment by othiym23** [comment]
It's not a bug in the CLI, unfortunately. npm's CDN isn't yet fully IPv6-ready, which is what causes these connectivity issues. Until there's something that the CLI team can do to address this, it remains a (very annoying) support issue.

**Comment by hobarrera** [comment]
@othiym23 
Please read the initial bug report closely. I clearly stated that I'm using NAT64. The remote endpoint *does not need* IPv6 compatibility, since I am using NAT64. I can reach IPv4-only hosts without any issues with any client software that properly suports it. For example, I can reach npm's CDN using curl on this same system.

The issue is npm (or rather, nodejs) not attempting to use IPv6, even when it's the only available protocol.

Done over IPv6/NAT64:

```
$ curl -I https://registry.npmjs.org/
HTTP/1.1 200 OK
server: CouchDB/1.5.0 (Erlang OTP/R16B03)
Content-Type: text/plain
Cache-Control: max-age=60
Content-Length: 260
Accept-Ranges: bytes
Date: Fri, 25 Sep 2015 19:17:18 GMT
Via: 1.1 varnish
Age: 0
Connection: keep-alive
X-Served-By: cache-lax1427-LAX
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1443208638.684559,VS0,VE195
```

**Comment by othiym23** [comment]
OK! There's still not a lot the CLI can do about Node's resolution logic, which changed in 0.12 and higher (and io.js, because the changes were landed in 0.11). Does this problem persist if you revert to Node 0.10.40 (using `npm@3.3.4`)? If not, this is something that will need to be tackled in Node first, as npm does nothing special around resolution.

**Comment by hobarrera** [comment]
The problem started on node 0.10. I digged back a bit, and remember that I'd reported this there, and is supposed to have been fixed on 0.12 branch, according to nodejs/node-v0.x-archive#7637.

I've looked at that closely, and it seems that upstream never fixed the issue properly though. Maybe it's the same problem?

**Comment by othiym23** [comment]
Having looked at that issue (thanks for finding it!), it's almost certainly the same issue. npm uses `http.Agent` and `https.Agent` directly, so if you (or anybody) can figure out how to configure it to do the right thing here, I'm happy to get that tested and integrated. The last time I looked at this, I couldn't figure it out, but that doesn't mean it's not possible.

**Comment by cristobalpalmer** [comment]
Added a me-too on the linked node bug. Please let me know if there's anything else I can test, @hobarrera.

**Comment by dany-on-demand** [comment]
As a hotfix, add this line to the hosts file
```bash
2001:8b0:6464:0:666:616:b91f:12a2 registry.npmjs.org
```

You may also want to add whatever your NAT64 resolves other domains to, node.js won't resolve those properly

**Comment by ldemailly** [comment]
I have the same issue

**Comment by WhyNotHugo** [comment]
This is hilarious. Closed due to three days of inactivity, when it's clearly an issue that makes npm completely unusable for many people. I think severity is high enough to actually keep this open.

**Comment by dany-on-demand** [comment]
@hobarrera have you tried my _"hotfix"_?

**Comment by williamdean** [comment]
it's worth mentioning that their CDN (Fastly) does now support IPv6. ...they just have to enable it. https://www.fastly.com/blog/ipv6-fastly/
