### ISSUE TITLE
npm API key format changed recently ?

### ISSUE THREAD

**Issue by thaiat** [npm/npm#8970]
Running npm publish  from travis i got today this weird error:
```bash
NPM API key format changed recently. If your deployment fails, check your API key in ~/.npmrc.
http://docs.travis-ci.com/user/deployment/npm/
npm ERR! publish Failed PUT 401
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v0.12.7/bin/node" "/home/travis/.nvm/versions/node/v0.12.7/bin/npm" "publish"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code E401
npm ERR! You must be logged in to publish packages : generator-sublime
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/mcfly-io/generator-sublime/npm-debug.log
No stash found.
```

version of node : 0.12.7
version of npm : 2.11.3

Nothing has changed, on my side, i m using the base64 encoded login + password

the `.travis.yml`  is here : https://github.com/mcfly-io/generator-sublime/blob/master/.travis.yml

**Comment by othiym23** [comment]
```
NPM API key format changed recently. If your deployment fails, check your API key in ~/.npmrc.
http://docs.travis-ci.com/user/deployment/npm/
```

This is a message coming from Travis, not npm. It's true that the primary npm registry has recently switched from using password-based credentials to using session tokens, as [described here](http://blog.getpiggybank.com/npm-private-modules-with-heroku/). If you upgrade your settings along the lines described in that post, you should be set. Good luck!

**Comment by falsandtru** [comment]
How to use new api key.

0. Login to npm on local by `$ npm login`.
0. Find and open your `.npmrc` file.
0. Find a line of `//registry.npmjs.org/:_authToken=<apikey>`.
0. Encrypt and add api key to `.travis.yml` by `$ travis encrypt --add deploy.api_key <apikey>`.
0. Logout from npm by `$ npm logout`.
0. Complete.

**Comment by cconcolato** [comment]
Same problem for me here https://travis-ci.org/gpac/mp4box.js/builds/71775451#L554
Updating the key did not change the result.

**Comment by binarykitchen** [comment]
@cconcolato did you exactly do these steps @falsandtru has described?

**Comment by cconcolato** [comment]
yes, I did, except that I had to add the encrypted key manually to the ```.travis.yml``` file because I have several deploy providers and ```travis```was messing up the result. 

I also tried to encrypt a variable:
```
NPM_TOKEN=00000000-0000-0000-0000-000000000000
```
as described in the link given above by @othiym23, but this did not change the result.

**Comment by thaiat** [comment]
it seems i have the same issue, i can't make it work if the key is not encrypted (i would like to use a variable config on server side)

**Comment by falsandtru** [comment]
Fixed my comment. While deployed, there seems to be a need to be logged in to npm on somewhere such as local machine. I append my settings and deploy log.
https://github.com/npm/npm/issues/8970#issuecomment-122854271

**Comment by binarykitchen** [comment]
@falsandtru so, are you implying that, when I am not logged in http://npmjs.com, then Travis cannot automatically `npm publish` the package for me once the automated tests have passed?

**Comment by falsandtru** [comment]
Yes, If you are using only the apikey. I failed to update my package version to v0.3.0-alpha.17. I was restart the job of travis after logged in to npm. Then I was successful in deployment using the same job and same apikey. Necessary conditions for the deployment seems not only apikey.

**Comment by thaiat** [comment]
this is confusing... can a clear explanation be added to the doc?

**Comment by sayedihashimi** [comment]
I tried the steps in https://github.com/npm/npm/issues/8970#issuecomment-122854271 and from Travis I still get the error above in the [generator-aspnet build](https://travis-ci.org/OmniSharp/generator-aspnet/builds/73109514#L491)

**Comment by falsandtru** [comment]
Error message says username or email is wrong.
https://travis-ci.org/OmniSharp/generator-aspnet/builds/73109514#L494-L495
>-npm ERR! need auth auth and email required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`

This is my failed deployment log. Error message is different.
https://travis-ci.org/falsandtru/lazychain/builds/71731556#L706
>-npm ERR! publish Failed PUT 401

**Comment by toddpi314** [comment]
For those having issues here, you need to force update NPM on the Travis-CI servers to something above major 2.*:
```
before_install:
  npm install -g npm@'>=2.13.5'
```

**Comment by sayedihashimi** [comment]
@toddpi314 that looks to have worked for me, thanks for the note.

**Comment by chrisprice** [comment]
Another potential issue: make sure that you're encrypting the token using the public key of the repository from which the build will run (rather than your own fork's key). You can manually specify it using the `-r` option on `travis encrypt`.
