### ISSUE TITLE
npm update -g ERR!s

### ISSUE THREAD

**Issue by abhyaasa** [npm/npm#9034]
Trying to clean up unmet dependency issues, I reinstalled node/npm with new download (OS X). Then ran npm update -g and got a great many errors like the following, and npm is gone from /usr/local/bin !!

```
npm ERR! Cannot find module '/usr/local/lib/node_modules/npm/lib/build.js'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "update" "-g"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module '/usr/local/lib/node_modules/npm/lib/build.js'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/home/npm-debug.log
home~$ cd /usr/local/lib/node_modules/npm/lib
home/usr/local/lib/node_modules/npm/lib$ ls
total 0
0 ./        0 ../       0 cache/    0 config/   0 utils/
home/usr/local/lib/node_modules/npm/lib$ cd
home~$ npm update
bash: /usr/local/bin/npm: No such file or directory
home~$ node -v
v0.12.7
```

**Comment by williamboman** [comment]
Looks like a corrupt installation of `npm`.

Try this;

```sh
curl registry.npmjs.com/npm/-/npm-2.13.1.tgz | tar xz && rm -rf /usr/local/lib/node_modules/npm && mv package $_
```

**Comment by vasudeva-chaynes** [comment]
Lots of permission denied. Tried fixing that as advised elsewhere. Reran your curl w/o errors, but still no npm. Reinstall node pkg? 

....
rm: /usr/local/lib/node_modules/npm/test/tap/view.js: Permission denied
rm: /usr/local/lib/node_modules/npm/test/tap/whoami.js: Permission denied
rm: /usr/local/lib/node_modules/npm/test/tap/zz-cleanup.js: Permission denied
rm: /usr/local/lib/node_modules/npm/test/tap: Permission denied
rm: /usr/local/lib/node_modules/npm/test/update-test.sh: Permission denied
rm: /usr/local/lib/node_modules/npm/test: Directory not empty
rm: /usr/local/lib/node_modules/npm: Directory not empty
home~$ ll /usr/local/lib/node_modules/npm/test/tap/view.js
24 -rw-rw-r--  1 65534  staff  8600 Jul  9 18:18 /usr/local/lib/node_modules/npm/test/tap/view.js
home~$ sudo chown -R home /usr/local
Password:
home~$ curl registry.npmjs.com/npm/-/npm-2.13.1.tgz | tar xz && rm -rf /usr/local/lib/node_modules/npm && mv package $_ &> out.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2821k  100 2821k    0     0  1192k      0  0:00:02  0:00:02 --:--:-- 1193k
home~$ cat out.txt
home~$ rm out.txt
remove out.txt? y
home~$ npm update
bash: /usr/local/bin/npm: No such file or directory
home~$

**Comment by williamboman** [comment]
@vasudeva-chaynes What does 

```sh
$ readlink $(which npm)
$ type -a npm
$ ls -l /usr/local/bin/ | grep npm
$ ls -l /usr/local/lib/node_modules/
```

produce?

**Comment by vasudeva-chaynes** [comment]
home~$ readlink $(which npm)
usage: readlink [-n] [-f] symlink
home~$ readlink /usr/local/bin/npm
home~$ type -a npm
bash: type: npm: not found
home~$ ls -l /usr/local/bin/ | grep npm
home~$ ls -l /usr/local/lib/node_modules/
total 0
0 drwxr-xr-x  14 home  admin   476 Jul 23 07:32 ./
0 drwxrwxr-x  34 home  admin  1156 Jul 21 17:11 ../
0 drwxr-xr-x   8 home  staff   272 May  4 14:20 ant/
0 drwxr-xr-x  19 home  staff   646 Jun  1 11:18 bower/
0 drwxr-xr-x  18 home  admin   612 Jul 22 22:08 cordova/
0 drwxr-xr-x  11 home  admin   374 Jul 21 16:39 gulp/
0 drwxr-xr-x  15 home  staff   510 Jul 20 20:10 ionic/
0 drwxr-xr-x  12 home  admin   408 Jul 22 22:08 ios-sim/
0 drwxr-xr-x   6 home  staff   204 Jul 20 20:16 n/
0 drwxr-xr-x  25 home  staff   850 Jul 23 07:32 npm/
0 drwxr-xr-x  16 home  admin   544 Jul 22 22:08 phonegap/
0 drwxr-xr-x  15 home  admin   510 Jul 22 22:08 plugman/
0 drwxr-xr-x  13 home  staff   442 May  4 14:55 rhoconnect-push/
0 drwxr-xr-x  12 home  staff   408 Jun 10 20:58 tty.js/
home~$

Thanks a lot for sticking with me in resolving this!

**Comment by williamboman** [comment]
@vasudeva-chaynes `ln -s /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm` should fix it!

I recommend using [nvm](https://github.com/creationix/nvm) instead of brew though!

**Comment by vasudeva-chaynes** [comment]
Thanks. The symlink gave me npm back. Yesterday I installed npm with downloaded pkg. Not sure how I installed it originally. I believe I've used brew in the past, but it's not working now (transcript below). 

I think I have current versions of node and nvm by virtue of pkg install:


home~/s$ node -v
v0.12.7
home~/s$ npm -v
2.13.1
home~/s$

I have n but not nvm. They seem to do similar things. With only one unreleased project, I don't see why I need either. Perhaps I need a tutorial recommendation.


 
npm update now runs on my project (only one at present) with lots of unmet dependency warnings.

npm global update fails: transcript appended.

home~$ brew
/usr/local/bin/brew: /usr/local/Library/brew.rb: /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby: bad interpreter: No such file or directory
/usr/local/bin/brew: line 26: /usr/local/Library/brew.rb: Undefined error: 0
home~$

**Comment by vasudeva-chaynes** [comment]
Read about nvm and installed using curl. Used it to install npm, and then npm to reinstall cordova and ionic globally, w/o sudo. npm update, global and local, are clean at last. Project tests seem to be working again.  brew still broken, but it seems at least for present purposes I'm better off without it. Thanks a lot for your help!

**Comment by williamboman** [comment]
@vasudeva-chaynes Nice! About your brew problem, looks like your system Ruby is missing. There is [rbenv](https://github.com/sstephenson/rbenv) and [RVM](https://rvm.io/) for Ruby as well :). I personally use rbenv.

**Comment by williamboman** [comment]
But yeah you should avoid using `sudo` with `npm` unless you're on a Linux system.

**Comment by jokeyrhyme** [comment]
You can configure `npm` to use a different installation prefix for global modules.

```sh
mkdir $HOME/.npm-packages
npm config set prefix $HOME/.npm-packages
```

This means that your global installation of Node and `npm` doesn't get touched by `npm -g update`, and you don't ever need `sudo` for global (un)installations.

Note that the latest NVM is not compatible with this approach anymore.

**Comment by vasudeva-chaynes** [comment]
jokeyrhyme: I'd rather not take an approach that's not compatible with new versions of nvm, but my current default prefix points to a home directory:

~/f/s$ npm config get prefix
/Users/home/.nvm/versions/node/v0.12.7
~/f/s$ npm config list
; cli configs
user-agent = "npm/2.13.1 node/v0.12.7 darwin x64"

; node bin location = /Users/home/.nvm/versions/node/v0.12.7/bin/node
; cwd = /Users/home/DD/Svadhyaya
; HOME = /Users/home
; 'npm config ls -l' to show all defaults.

~/f/s$

**Comment by williamboman** [comment]
> jokeyrhyme: I'd rather not take an approach that's not compatible with new versions of nvm, but my current default prefix points to a home directory:

`nvm` installs stuff to `$HOME/.nvm` anyways which renders the `prefix` config fix redundant.

**Comment by vasudeva-chaynes** [comment]
Good to know. 

Brew is still not working, but now with a different error. No idea where to look for the Library/ referred to. Ruby does work, as installed by rvm. 

~$ brew update
error: The following untracked working tree files would be overwritten by merge:
	Library/Formula/appledoc.rb
Please move or remove them before you can merge.
Aborting
Error: Failure while executing: git pull --ff --no-rebase --quiet origin refs/heads/master:refs/remotes/origin/master
~$ which ruby
/Users/home/.rvm/rubies/ruby-2.2.3/bin/ruby

**Comment by williamboman** [comment]
@vasudeva-chaynes 

Try
```sh
$ pushd /usr/local/ && git fetch && git reset --hard origin/master && popd;
$ brew update;
```

(not really an `npm` issue anymore, but still)

**Comment by vasudeva-chaynes** [comment]
git fetch worked w/o complaint, but then do I really need to chown -R home /usr/local ?

/usr/local$ git reset --hard origin/master
error: unable to unlink old '.travis.yml' (Permission denied)
error: unable to unlink old 'CONTRIBUTING.md' (Permission denied)
error: unable to unlink old 'README.md' (Permission denied)
error: unable to unlink old 'SUPPORTERS.md' (Permission denied)
fatal: Could not reset index file to revision 'origin/master'.
/usr/local$ cd ~
~$ brew update
Error: The /usr/local directory is not writable.
Even if this directory was writable when you installed Homebrew, other
software may change permissions on this directory. Some versions of the
"InstantOn" component of Airfoil are known to do this.

You should probably change the ownership and permissions of /usr/local
back to your user account.
  sudo chown -R $(whoami):admin /usr/local
~$ sudo brew update
Password:
Error: Cowardly refusing to `sudo brew update`
You can use brew with sudo, but only if the brew executable is owned by root.
However, this is both not recommended and completely unsupported so do so at
your own risk.
~$ ls -ld /usr/local
0 drwxr-xr-x  27 root  wheel  918 Nov  5 11:07 /usr/local/
~$

**Comment by williamboman** [comment]
> git fetch worked w/o complaint, but then do I really need to chown -R home /usr/local ?

That's undoubtedly the easiest way to do it, I do it on all my OS X machines.

If you want to micromanage it, or if there are more than on OS X account that uses Homebrew on your machine you're gonna have to do some additional permissions management, see e.g. http://apple.stackexchange.com/a/45003.

**Comment by vasudeva-chaynes** [comment]
Thanks for staying with me on this. Different brew error now; not sure if it's critical.

~$ sudo chown -R home /usr/local
Password:
~$ brew update
Library/Aliases/0install already exists, no checkout
Library/Aliases/2ping already exists, no checkout
Library/Formula/aide.rb already exists, no checkout
Library/Formula/airspy.rb already exists, no checkout
Library/Formula/amazon-ecs-cli.rb already exists, no checkout
Library/Formula/ammonite-repl.rb already exists, no checkout
Library/Formula/ansiweather.rb already exists, no checkout
Library/Formula/appledoc.rb already exists, no checkout
Library/Formula/archivemail.rb already exists, no checkout
Library/Formula/asio.rb already exists, no checkout
Library/Formula/autocode.rb already exists, no checkout
Library/Formula/bee.rb already exists, no checkout
Library/Formula/carina.rb already exists, no checkout
Library/Formula/chaiscript.rb already exists, no checkout
Library/Formula/consul-template.rb already exists, no checkout
Library/Formula/coturn.rb already exists, no checkout
Library/Formula/crystal-lang.rb already exists, no checkout
Library/Formula/dbxml.rb already exists, no checkout
Library/Formula/devd.rb already exists, no checkout
Library/Formula/dfmt.rb already exists, no checkout
Library/Formula/dnstwist.rb already exists, no checkout
Library/Formula/docker-compose.rb already exists, no checkout
Library/Formula/docker-machine-parallels.rb already exists, no checkout
Library/Formula/doctl.rb already exists, no checkout
Library/Formula/dspdfviewer.rb already exists, no checkout
Library/Formula/fluent-bit.rb already exists, no checkout
Library/Formula/fmpp.rb already exists, no checkout
Library/Formula/fprobe.rb already exists, no checkout
Library/Formula/fstar.rb already exists, no checkout
Library/Formula/gdub.rb already exists, no checkout
Library/Formula/generate-json-schema.rb already exists, no checkout
Library/Formula/gitlab-ci-multi-runner.rb already exists, no checkout
Library/Formula/glslang.rb already exists, no checkout
Library/Formula/glyr.rb already exists, no checkout
Library/Formula/godep.rb already exists, no checkout
Library/Formula/gom.rb already exists, no checkout
Library/Formula/icmake.rb already exists, no checkout
Library/Formula/iproute2mac.rb already exists, no checkout
Library/Formula/jsonnet.rb already exists, no checkout
Library/Formula/jsonschema2pojo.rb already exists, no checkout
Library/Formula/ldid.rb already exists, no checkout
Library/Formula/libagar.rb already exists, no checkout
Library/Formula/libbladerf.rb already exists, no checkout
Library/Formula/libfabric.rb already exists, no checkout
Library/Formula/libfixposix.rb already exists, no checkout
Library/Formula/libgdata.rb already exists, no checkout
Library/Formula/libgraphqlparser.rb already exists, no checkout
Library/Formula/libmill.rb already exists, no checkout
Library/Formula/librest.rb already exists, no checkout
Library/Formula/libsoundio.rb already exists, no checkout
Library/Formula/libstatgrab.rb already exists, no checkout
Library/Formula/libuecc.rb already exists, no checkout
Library/Formula/mailhog.rb already exists, no checkout
Library/Formula/mbedtls.rb already exists, no checkout
Library/Formula/mdds.rb already exists, no checkout
Library/Formula/mg3a.rb already exists, no checkout
Library/Formula/miller.rb already exists, no checkout
Library/Formula/mstch.rb already exists, no checkout
Library/Formula/ne.rb already exists, no checkout
Library/Formula/nim.rb already exists, no checkout
Library/Formula/node-build.rb already exists, no checkout
Library/Formula/nodeenv.rb already exists, no checkout
Library/Formula/nomad.rb already exists, no checkout
Library/Formula/otto.rb already exists, no checkout
Library/Formula/owamp.rb already exists, no checkout
Library/Formula/pgroonga.rb already exists, no checkout
Library/Formula/postgrest.rb already exists, no checkout
Library/Formula/prefixsuffix.rb already exists, no checkout
Library/Formula/procmail.rb already exists, no checkout
Library/Formula/psql2csv.rb already exists, no checkout
Library/Formula/rancher-compose.rb already exists, no checkout
Library/Formula/ratfor.rb already exists, no checkout
Library/Formula/rgxg.rb already exists, no checkout
Library/Formula/sdedit.rb already exists, no checkout
Library/Formula/shairport-sync.rb already exists, no checkout
Library/Formula/shairport.rb already exists, no checkout
Library/Formula/sickrage.rb already exists, no checkout
Library/Formula/sift.rb already exists, no checkout
Library/Formula/sphinx-doc.rb already exists, no checkout
Library/Formula/sqliteodbc.rb already exists, no checkout
Library/Formula/ssllabs-scan.rb already exists, no checkout
Library/Formula/swagger-codegen.rb already exists, no checkout
Library/Formula/swiftgen.rb already exists, no checkout
Library/Formula/tailor.rb already exists, no checkout
Library/Formula/tcpstat.rb already exists, no checkout
Library/Formula/twoping.rb already exists, no checkout
Library/Formula/unicorn.rb already exists, no checkout
Library/Formula/vdirsyncer.rb already exists, no checkout
Library/Formula/viennacl.rb already exists, no checkout
Library/Formula/viewvc.rb already exists, no checkout
Library/Formula/walkmod.rb already exists, no checkout
Library/Formula/whatmp3.rb already exists, no checkout
Library/Formula/wiki.rb already exists, no checkout
Library/Formula/wolfssl.rb already exists, no checkout
Library/Formula/woof.rb already exists, no checkout
Library/Formula/xalan-c.rb already exists, no checkout
Library/Formula/xxhash.rb already exists, no checkout
Library/Formula/yank.rb already exists, no checkout
Library/Formula/ykneomgr.rb already exists, no checkout
Library/Formula/z3.rb already exists, no checkout
Library/Formula/zanata-client.rb already exists, no checkout
Library/Formula/zero-install.rb already exists, no checkout
Library/Homebrew/compat/dependency_collector.rb already exists, no checkout
Library/Homebrew/compat/keg.rb already exists, no checkout
Library/Homebrew/compat/pathname.rb already exists, no checkout
Library/Homebrew/os/mac/mach.rb already exists, no checkout
Library/Homebrew/os/mac/pathname.rb already exists, no checkout
Could not restore untracked files from stash
Error: Failure while executing: git stash pop --quiet
~$

**Comment by williamboman** [comment]
@vasudeva-chaynes What does `$ brew --prefix` produce?

**Comment by vasudeva-chaynes** [comment]
/usr/local

**Comment by williamboman** [comment]
Try 

```sh
$ sudo chown -R $(whoami) /usr/local
$ brew update
```

again.

**Comment by vasudeva-chaynes** [comment]
Strange needing to run the chown twice, but second time was charming :) Looks like it's working now. Many thanks!

~$ sudo chown -R $(whoami) /usr/local
Password:
~$ brew update
Updated 1 tap (homebrew/versions).
==> New Formulae
homebrew/versions/android-ndk-r10d       homebrew/versions/lz4r117
homebrew/versions/apache-spark141        homebrew/versions/mysql56
homebrew/versions/elasticsearch17        homebrew/versions/nifi021
homebrew/versions/gradle26               homebrew/versions/node4-lts
homebrew/versions/gradle27               homebrew/versions/saxon6
homebrew/versions/gradle28               homebrew/versions/zeromq405
homebrew/versions/iojs
==> Updated Formulae
homebrew/versions/glfw3                  homebrew/versions/libmongoclient-legacy
homebrew/versions/gnupg21                homebrew/versions/libpng12
homebrew/versions/gnutls34               homebrew/versions/play13
homebrew/versions/jenkins-lts            homebrew/versions/tomcat7
~$

**Comment by williamboman** [comment]
> Strange needing to run the chown twice

The first time you ran it as `$ sudo chown -R home /usr/local`, I assume your username isn't `home` :smile:

**Comment by vasudeva-chaynes** [comment]
It is home, that's why it's strange. But hey, it works now!
