### ISSUE TITLE
HTTP 400 on `npm login`

### ISSUE THREAD

**Issue by mrmch** [npm/npm#9434]
Getting an unknown error when trying to login from the command line. Credentials work on the website.

See `npm-debug.log` below:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'login' ]
2 info using npm@2.12.1
3 info using node@v0.12.7
4 verbose node symlink /usr/local/bin/node
5 verbose adduser before first PUT { _id: 'org.couchdb.user:sendwithus',
5 verbose adduser   name: 'sendwithus',
5 verbose adduser   password: 'XXXXX',
5 verbose adduser   email: 'login@sendwithus.com',
5 verbose adduser   type: 'user',
5 verbose adduser   roles: [],
5 verbose adduser   date: '2015-08-28T18:42:10.351Z' }
6 verbose request uri https://registry.npmjs.org/-/user/org.couchdb.user:sendwithus
7 verbose request new user, so can't send auth
8 info attempt registry request try #1 at 11:42:10
9 verbose request id 7b4a400e2b21b6ed
10 http request PUT https://registry.npmjs.org/-/user/org.couchdb.user:sendwithus
11 http 400 https://registry.npmjs.org/-/user/org.couchdb.user:sendwithus
12 verbose headers { 'content-type': 'application/json',
12 verbose headers   'cache-control': 'max-age=60',
12 verbose headers   'content-length': '57',
12 verbose headers   'accept-ranges': 'bytes',
12 verbose headers   date: 'Fri, 28 Aug 2015 18:42:10 GMT',
12 verbose headers   via: '1.1 varnish',
12 verbose headers   connection: 'keep-alive',
12 verbose headers   'x-served-by': 'cache-sjc3129-SJC',
12 verbose headers   'x-cache': 'MISS',
12 verbose headers   'x-cache-hits': '0',
12 verbose headers   'x-timer': 'S1440787330.674680,VS0,VE173' }
13 verbose request invalidating /Users/mattharris/.npm/registry.npmjs.org/-/user/org.couchdb.user_3Asendwithus on PUT
14 verbose adduser back [ { [Error: Unknown error while authenticating : -/user/org.couchdb.user:sendwithus] statusCode: 400, code: 'E400' },
14 verbose adduser   { ok: false, error: 'Unknown error while authenticating' },
14 verbose adduser   '{"ok":false,"error":"Unknown error while authenticating"}' ]
15 verbose stack Error: Unknown error while authenticating : -/user/org.couchdb.user:sendwithus
15 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:247:14)
15 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
15 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:197:22)
15 verbose stack     at Request.emit (events.js:110:17)
15 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1050:14)
15 verbose stack     at Request.emit (events.js:129:20)
15 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:996:12)
15 verbose stack     at IncomingMessage.emit (events.js:129:20)
15 verbose stack     at _stream_readable.js:908:16
15 verbose stack     at process._tickCallback (node.js:355:11)
16 verbose statusCode 400
17 verbose cwd /Users/mattharris/dev/sendwithus/grunt-sendwithus
18 error Darwin 14.3.0
19 error argv "node" "/usr/local/bin/npm" "login"
20 error node v0.12.7
21 error npm  v2.12.1
22 error code E400
23 error Unknown error while authenticating : -/user/org.couchdb.user:sendwithus
24 error If you need help, you may report this error at:
24 error     <https://github.com/npm/npm/issues>
25 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
We've made a couple changes to the registry recently, and it's possible you got stuck on a rough edge. @bcoe is taking a look at this right now, and we'll let you know what we find out. Thanks for filing this!

**Comment by mrmch** [comment]
thanks @othiym23

**Comment by bcoe** [comment]
@mrmch we've hunted down this problem to a regression with the password reset flow -- whoops, we're working quickly to get a patch out.

Although it felt like you changed your account password to a new password, your account is actually still using the password that was randomly assigned during the password reset flow.

You should be able to use this randomly assigned password to login from the CLI in the short term. One of the wonderful members of our www team (CC @rockbot, @jefflembeck, @aredridel) will have a patch out for this shortly and follow up.

**Comment by mrmch** [comment]
@bcoe so I need to reset our password again, get a new randomly assigned password, and use that to login?

**Comment by bcoe** [comment]
@mrmch I think that should work for you in the short term, we'll update this thread as soon as we've deployed a fix.

**Comment by mrmch** [comment]
Rad, just pushed our package: https://www.npmjs.com/package/grunt-sendwithus

Thanks ya'll.

**Comment by bjconlan** [comment]
Yeah, when I'm trying to reset my password, I too am presented (with a slightly different error) of a 
`not found
https://www.npmjs.com/ does not exist. time to go outside.

Have you seen this wombat?`

(the console has a nice ole' `HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
POST - https://www.npmjs.com/` error)

**Comment by ehsalazar** [comment]
@mrmch Good to hear. I'll close this for now as we’re trying to clean up some solved issues. We’ll be happy to reopen if necessary.

@bjconlan If this is still an issue for you, please reach out to us at `support@npmjs.com`. We'll be happy to help you regain access to your account.

**Comment by paddyduke** [comment]
It appears I am still encountering this issue or something like it. Any update on this fix?

```
npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:paddyduke
npm http 400 https://registry.npmjs.org/-/user/org.couchdb.user:paddyduke
npm ERR! Error: Unknown error while authenticating : -/user/org.couchdb.user:paddyduke
npm ERR!     at RegClient.<anonymous> (/usr/local/Cellar/node/0.10.26/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:237:14)
npm ERR!     at Request.self.callback (/usr/local/Cellar/node/0.10.26/lib/node_modules/npm/node_modules/request/request.js:123:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/Cellar/node/0.10.26/lib/node_modules/npm/node_modules/request/request.js:893:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/Cellar/node/0.10.26/lib/node_modules/npm/node_modules/request/request.js:844:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.5.0
npm ERR! command "/usr/local/Cellar/node/0.10.26/bin/node" "/usr/local/bin/npm" "login"
npm ERR! cwd /Users/paddy/dev/fa/origin
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/paddy/dev/fa/origin/npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
@paddyduke Please try [updating `npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) first.

**Comment by paddyduke** [comment]
@KenanY Thanks. That's worked.
